---
permalink: audit/audit-log-file-rotation.html 
sidebar: sidebar 
keywords: storagegrid, audit, log file, audit.log, audit.log file, rotation, save, autosave, auto save, auto-save 
summary: I file dei registri di controllo vengono salvati nella directory /var/local/audit/export/ di un nodo di amministrazione.  I file di registro di controllo attivi sono denominati audit.log. 
---
= Controllo della rotazione del file di log
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se StorageGRID è configurato per *Nodi amministrativi/nodi locali* o *Nodo amministrativo e server syslog esterno*, i file dei registri di controllo vengono salvati nel nodo amministrativo `/var/local/audit/export/` elenco.  I file di registro di controllo attivi sono denominati `audit.log` .


NOTE: Facoltativamente, è possibile modificare la destinazione dei log di controllo e inviare le informazioni di controllo a un server syslog esterno.  I registri locali dei record di controllo continuano a essere generati e archiviati quando viene configurato un server syslog esterno. Fare riferimento a link:../monitor/configure-audit-messages.html["Configurare i messaggi di controllo e il server syslog esterno"] .

Una volta al giorno, il file attivo `audit.log` viene salvato e viene avviato un nuovo `audit.log` file. Il nome del file salvato indica quando è stato salvato, nel formato `_yyyy-mm-dd.txt_`. Se in un solo giorno vengono creati più log di controllo, i nomi dei file utilizzano la data in cui il file è stato salvato, seguita da un numero, nel formato `_yyyy-mm-dd.txt.n_`. Ad esempio, `2018-04-15.txt` e `2018-04-15.txt.1` sono il primo e il secondo file di registro creati e salvati il 15 aprile 2018.

Dopo un giorno, il file salvato viene compresso e rinominato, nel formato `_yyyy-mm-dd.txt.gz_` , che conserva la data originale.  Nel tempo, lo spazio di archiviazione del nodo di amministrazione assegnato ai registri di controllo viene consumato.  Uno script monitora il consumo di spazio del registro di controllo ed elimina i file di registro se necessario per liberare spazio nel `/var/local/audit/export/` elenco.  I registri di controllo vengono eliminati in base alla data in cui sono stati creati.  I registri più vecchi vengono eliminati per primi.  È possibile monitorare le azioni dello script nel seguente file: `/var/local/log/manage-audit.log` .

Questo esempio mostra il file attivo `audit.log`, il file del giorno precedente (`2018-04-15.txt`) e il file compresso per il giorno precedente (`2018-04-14.txt.gz`).

[listing]
----
audit.log
2018-04-15.txt
2018-04-14.txt.gz
----