---
permalink: audit/audit-message-format.html 
sidebar: sidebar 
keywords: storagegrid, audit, message formats, message format 
summary: 'I messaggi di audit scambiati all"interno del sistema StorageGRID includono informazioni standard comuni a tutti i messaggi e contenuti specifici che descrivono l"evento o l"attività da segnalare.' 
---
= Formato del messaggio di audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I messaggi di audit scambiati all'interno del sistema StorageGRID includono informazioni standard comuni a tutti i messaggi e contenuti specifici che descrivono l'evento o l'attività da segnalare.

Se le informazioni di riepilogo fornite dagli link:using-audit-explain-tool.html["audit-spiegare"]strumenti e link:using-audit-sum-tool.html["audit-sum"]non sono sufficienti, fare riferimento a questa sezione per comprendere il formato generale di tutti i messaggi di controllo.

Di seguito viene riportato un esempio di messaggio di audit che potrebbe essere visualizzato nel file di log dell'audit:

[listing]
----
2014-07-17T03:50:47.484627
[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][ATYP(FC32):SYSU][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
Ogni messaggio di audit contiene una stringa di elementi di attributo. L'intera stringa è racchiusa tra parentesi (`[ ]`( ), e ogni elemento attribute nella stringa ha le seguenti caratteristiche:

* Racchiuso tra parentesi `[ ]`
* Introdotta dalla stringa `AUDT`, che indica un messaggio di controllo
* Senza delimitatori (senza virgole o spazi) prima o dopo
* Terminato da un carattere di avanzamento riga `\n`


Ogni elemento include un codice di attributo, un tipo di dati e un valore che vengono riportati in questo formato:

[listing]
----
[ATTR(type):value][ATTR(type):value]...
[ATTR(type):value]\n
----
Il numero di elementi di attributo nel messaggio dipende dal tipo di evento del messaggio. Gli elementi dell'attributo non sono elencati in un ordine specifico.

L'elenco seguente descrive gli elementi degli attributi:

* `ATTR` è un codice di quattro caratteri per l'attributo riportato. Esistono alcuni attributi comuni a tutti i messaggi di audit e ad altri specifici degli eventi.
* `type` È un identificatore di quattro caratteri del tipo di dati di programmazione del valore, come UI64, FC32 e così via. Il tipo è racchiuso tra parentesi `( )`.
* `value` è il contenuto dell'attributo, in genere un valore numerico o di testo. I valori seguono sempre i due punti (`:`). I valori del tipo di dati CSTR sono racchiusi tra virgolette doppie " ".

