---
permalink: audit/client-write-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, client write, OVWR, SDEL, SPOS, SPUT, SUPD, WDEL, WPUT, S3 
summary: 'I messaggi di controllo in scrittura del client vengono registrati quando un"applicazione client S3 richiede di creare o modificare un oggetto.' 
---
= Messaggi di audit di scrittura del client
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I messaggi di controllo in scrittura del client vengono registrati quando un'applicazione client S3 richiede di creare o modificare un oggetto.

[cols="1a,3a,1a,1a"]
|===
| Codice | Descrizione | Utilizzato da | Vedere 


 a| 
OVWR
 a| 
Object Overwrite: Registra una transazione per sovrascrivere un oggetto con un altro oggetto.
 a| 
S3 e Swift
 a| 
link:ovwr-object-overwrite.html["OVWR: Sovrascrittura degli oggetti"]



 a| 
SDEL
 a| 
S3 DELETE (ELIMINA S3): Registra una transazione riuscita per eliminare un oggetto o un bucket.

*Nota:* se la transazione opera su una sottorisorsa, il messaggio di audit includerà il campo S3SR.
 a| 
Client S3
 a| 
link:sdel-s3-delete.html["SDEL: ELIMINAZIONE S3"]



 a| 
SPOS
 a| 
S3 POST: Registra una transazione riuscita per ripristinare un oggetto dallo storage AWS Glacier a un Cloud Storage Pool.
 a| 
Client S3
 a| 
link:spos-s3-post.html["SPOS: POST S3"]



 a| 
SPUT
 a| 
S3 PUT: Registra una transazione riuscita per creare un nuovo oggetto o bucket.

*Nota:* se la transazione opera su una sottorisorsa, il messaggio di audit includerà il campo S3SR.
 a| 
Client S3
 a| 
link:sput-s3-put.html["SPUT: S3 PUT"]



 a| 
SUPD
 a| 
S3 Metadata Updated: Registra una transazione riuscita per aggiornare i metadati di un oggetto o bucket esistente.
 a| 
Client S3
 a| 
link:supd-s3-metadata-updated.html["SUPD: Metadati S3 aggiornati"]



 a| 
WDEL
 a| 
Eliminazione rapida: Registra una transazione riuscita per eliminare un oggetto o un container.
 a| 
Client Swift
 a| 
link:wdel-swift-delete.html["WDEL: ELIMINAZIONE rapida"]



 a| 
WPUT
 a| 
Swift PUT: Registra una transazione riuscita per creare un nuovo oggetto o container.
 a| 
Client Swift
 a| 
link:wput-swift-put.html["WPUT: MESSA rapida"]

|===