---
permalink: audit/index.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, log, structure, content 
summary: 'Queste istruzioni contengono informazioni sulla struttura e sul contenuto dei messaggi di audit e dei registri di audit di StorageGRID. È possibile utilizzare queste informazioni per leggere e analizzare il registro di controllo dell"attività del sistema.' 
---
= Messaggi e registri di controllo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Queste istruzioni contengono informazioni sulla struttura e sul contenuto dei messaggi di audit e dei registri di audit di StorageGRID. È possibile utilizzare queste informazioni per leggere e analizzare il registro di controllo dell'attività del sistema.

Queste istruzioni sono destinate agli amministratori responsabili della produzione di report sull'attività e sull'utilizzo del sistema che richiedono l'analisi dei messaggi di audit del sistema StorageGRID.

Per utilizzare il file di log di testo, è necessario disporre dell'accesso alla condivisione di audit configurata nel nodo di amministrazione.

Per informazioni sulla configurazione dei livelli dei messaggi di controllo e sull'utilizzo di un server syslog esterno, vederelink:../monitor/configure-log-management.html["Configurare la gestione dei log e il server syslog esterno"] .
