---
permalink: audit/object-ingest-transactions.html 
sidebar: sidebar 
keywords: object ingest transaction, S3 ingest, SPUT, ORLM, WPUT 
summary: 'Nell"audit log, puoi identificare le transazioni di acquisizione dei client individuando S3 messaggi di audit specifici di API.' 
---
= Transazioni di acquisizione degli oggetti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nell'audit log, puoi identificare le transazioni di acquisizione dei client individuando S3 messaggi di audit specifici di API.

Non tutti i messaggi di audit generati durante una transazione di acquisizione sono elencati nelle tabelle seguenti. Sono inclusi solo i messaggi necessari per tracciare la transazione di acquisizione.



== S3: Acquisizione di messaggi di audit

[cols="1a,1a,2a,1a,2a"]
|===
| Codice | Nome | Descrizione | Traccia | Vedere 


 a| 
SPUT
 a| 
Transazione S3 PUT
 a| 
Una transazione S3 PUT ingest è stata completata correttamente.
 a| 
CBID, S3BK, S3KY
 a| 
link:sput-s3-put.html["SPUT: S3 PUT"]



 a| 
ORLM
 a| 
Regole oggetto soddisfatte
 a| 
Il criterio ILM è stato soddisfatto per questo oggetto.
 a| 
CBID
 a| 
link:orlm-object-rules-met.html["ORLM: Regole oggetto soddisfatte"]

|===


== Acquisizione rapida di messaggi di audit

[cols="1a,1a,2a,1a,2a"]
|===
| Codice | Nome | Descrizione | Traccia | Vedere 


 a| 
WPUT
 a| 
Transazione SWIFT PUT
 a| 
Una transazione Swift PUT Ingest è stata completata correttamente.
 a| 
CBID, WCON, WOBJ
 a| 
link:wput-swift-put.html["WPUT: MESSA rapida"]



 a| 
ORLM
 a| 
Regole oggetto soddisfatte
 a| 
Il criterio ILM è stato soddisfatto per questo oggetto.
 a| 
CBID
 a| 
link:orlm-object-rules-met.html["ORLM: Regole oggetto soddisfatte"]

|===


== Esempio: Acquisizione di oggetti S3

La serie di messaggi di controllo riportata di seguito è un esempio dei messaggi di controllo generati e salvati nel registro di controllo quando un client S3 acquisisce un oggetto in un nodo di storage (servizio LDR).

In questo esempio, il criterio ILM attivo include la regola ILM Make 2 Copies.


NOTE: Non tutti i messaggi di audit generati durante una transazione sono elencati nell'esempio seguente. Vengono elencati solo quelli relativi alla transazione di acquisizione S3 (SPUT).

Questo esempio presuppone che sia stato precedentemente creato un bucket S3.



=== SPUT: S3 PUT

Il messaggio SPUT viene generato per indicare che è stata emessa una transazione S3 PUT per creare un oggetto in un bucket specifico.

[listing, subs="specialcharacters,quotes"]
----
2017-07-17T21:17:58.959669[AUDT:[RSLT(FC32):SUCS][TIME(UI64):25771][SAIP(IPAD):"10.96.112.29"][S3AI(CSTR):"70899244468554783528"][SACC(CSTR):"test"][S3AK(CSTR):"SGKHyalRU_5cLflqajtaFmxJn946lAWRJfBF33gAOg=="][SUSR(CSTR):"urn:sgws:identity::70899244468554783528:root"][SBAI(CSTR):"70899244468554783528"][SBAC(CSTR):"test"][S3BK(CSTR):"example"][S3KY(CSTR):"testobject-0-3"][CBID\(UI64\):0x8EF52DF8025E63A8][CSIZ(UI64):30720][AVER(UI32):10][ATIM(UI64):150032627859669][ATYP\(FC32\):SPUT][ANID(UI32):12086324][AMID(FC32):S3RQ][ATID(UI64):14399932238768197038]]
----


=== ORLM: Regole oggetto soddisfatte

Il messaggio ORLM indica che il criterio ILM è stato soddisfatto per questo oggetto. Il messaggio include il CBID dell'oggetto e il nome della regola ILM applicata.

Per gli oggetti replicati, il campo LOCS include l'ID del nodo LDR e l'ID del volume delle posizioni degli oggetti.

[listing, subs="specialcharacters,quotes"]
----
2019-07-17T21:18:31.230669[AUDT:[CBID\(UI64\):0x50C4F7AC2BC8EDF7][RULE(CSTR):"Make 2 Copies"][STAT(FC32):DONE][CSIZ(UI64):0][UUID(CSTR):"0B344E18-98ED-4F22-A6C8-A93ED68F8D3F"][LOCS(CSTR):"CLDI 12828634 2148730112, CLDI 12745543 2147552014"][RSLT(FC32):SUCS][AVER(UI32):10][ATYP\(FC32\):ORLM][ATIM(UI64):1563398230669][ATID(UI64):15494889725796157557][ANID(UI32):13100453][AMID(FC32):BCMS]]
----
Per gli oggetti sottoposti a erasure coding, il campo LOCS include l'ID del profilo di erasure coding e l'ID del gruppo di erasure coding

[listing, subs="specialcharacters,quotes"]
----
2019-02-23T01:52:54.647537 [AUDT:[CBID(UI64):0xFA8ABE5B5001F7E2][RULE(CSTR):"EC_2_plus_1"][STAT(FC32):DONE][CSIZ(UI64):10000][UUID(CSTR):"E291E456-D11A-4701-8F51-D2F7CC9AFECA"][LOCS(CSTR):"CLEC 1 A471E45D-A400-47C7-86AC-12E77F229831"][RSLT(FC32):SUCS][AVER(UI32):10][ATIM(UI64):1550929974537]\[ATYP\(FC32\):ORLM\][ANID(UI32):12355278][AMID(FC32):ILMX][ATID(UI64):4168559046473725560]]
----
Il campo PATH include informazioni sul bucket S3 e sulla chiave o informazioni sul container Swift e sull'oggetto, a seconda dell'API utilizzata.

[listing]
----
2019-09-15.txt:2018-01-24T13:52:54.131559 [AUDT:[CBID(UI64):0x82704DFA4C9674F4][RULE(CSTR):"Make 2 Copies"][STAT(FC32):DONE][CSIZ(UI64):3145729][UUID(CSTR):"8C1C9CAC-22BB-4880-9115-CE604F8CE687"][PATH(CSTR):"frisbee_Bucket1/GridDataTests151683676324774_1_1vf9d"][LOCS(CSTR):"CLDI 12525468, CLDI 12222978"][RSLT(FC32):SUCS][AVER(UI32):10][ATIM(UI64):1568555574559][ATYP(FC32):ORLM][ANID(UI32):12525468][AMID(FC32):OBDI][ATID(UI64):344833886538369336]]
----