---
permalink: audit/sdel-s3-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SDEL, S3 DELETE 
summary: 'Quando un client S3 esegue una transazione DI ELIMINAZIONE, viene inviata una richiesta per rimuovere l"oggetto o il bucket specificato. Questo messaggio viene emesso dal server se la transazione ha esito positivo.' 
---
= SDEL: ELIMINAZIONE S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando un client S3 esegue una transazione DI ELIMINAZIONE, viene effettuata una richiesta per rimuovere l'oggetto o il bucket specificato o per rimuovere una sottorisorsa bucket/oggetto. Questo messaggio viene emesso dal server se la transazione ha esito positivo.

[cols="1a,1a,4a"]
|===
| Codice | Campo | Descrizione 


 a| 
CBID
 a| 
Identificatore del blocco di contenuto
 a| 
L'identificatore univoco del blocco di contenuto richiesto. Se il CBID non è noto, questo campo viene impostato su 0. Le operazioni sui bucket non includono questo campo.



 a| 
CNCH
 a| 
Intestazione del controllo di coerenza
 a| 
Il valore dell'intestazione della richiesta HTTP Consistency-Control, se presente nella richiesta.



 a| 
CNID
 a| 
Identificatore di connessione
 a| 
Identificatore univoco del sistema per la connessione TCP/IP.



 a| 
CSIZ
 a| 
Dimensione contenuto
 a| 
La dimensione dell'oggetto cancellato in byte. Le operazioni sui bucket non includono questo campo.



 a| 
DMRK
 a| 
Elimina ID versione marker
 a| 
L'ID versione del marker di eliminazione creato quando si elimina un oggetto da un bucket con versione. Le operazioni sui bucket non includono questo campo.



 a| 
GFID
 a| 
ID connessione Grid Federation
 a| 
L'ID di connessione della connessione a federazione di griglie associato a una richiesta di eliminazione della replica a griglia incrociata. Incluso solo nei registri di controllo nella griglia di destinazione.



 a| 
GFSA
 a| 
ID account di origine Grid Federation
 a| 
L'ID account del tenant sulla griglia di origine per una richiesta di eliminazione della replica cross-grid. Incluso solo nei registri di controllo nella griglia di destinazione.



 a| 
HTRH
 a| 
Intestazione richiesta HTTP
 a| 
Elenco dei nomi e dei valori delle intestazioni delle richieste HTTP registrati selezionati durante la configurazione.

 `X-Forwarded-For` Viene incluso automaticamente se è presente nella richiesta e se il `X-Forwarded-For` valore è diverso dall'indirizzo IP del mittente della richiesta (campo di controllo SAIP).

`x-amz-bypass-governance-retention` viene incluso automaticamente se è presente nella richiesta.



 a| 
MTME
 a| 
Ora dell'ultima modifica
 a| 
Data e ora di Unix, in microsecondi, che indica quando l'oggetto è stato modificato per l'ultima volta.



 a| 
RSLT
 a| 
Codice risultato
 a| 
Risultato della transazione DI ELIMINAZIONE. Il risultato è sempre:

SUC: Riuscito



 a| 
S3AI
 a| 
ID account tenant S3 (richiesta mittente)
 a| 
L'ID account tenant dell'utente che ha inviato la richiesta. Un valore vuoto indica l'accesso anonimo.



 a| 
S3AK
 a| 
ID chiave di accesso S3 (richiesta mittente)
 a| 
L'ID della chiave di accesso S3 hash per l'utente che ha inviato la richiesta. Un valore vuoto indica l'accesso anonimo.



 a| 
S3BK
 a| 
Bucket S3
 a| 
Il nome del bucket S3.



 a| 
S3KY
 a| 
Chiave S3
 a| 
Il nome della chiave S3, senza il nome del bucket. Le operazioni sui bucket non includono questo campo.



 a| 
S3SR
 a| 
S3 Subresource
 a| 
Il bucket o la sottorisorsa oggetto su cui viene eseguita, se applicabile.



 a| 
SACC
 a| 
Nome account tenant S3 (mittente della richiesta)
 a| 
Il nome dell'account tenant per l'utente che ha inviato la richiesta. Vuoto per richieste anonime.



 a| 
SAIP
 a| 
Indirizzo IP (Request sender)
 a| 
L'indirizzo IP dell'applicazione client che ha eseguito la richiesta.



 a| 
SBAC
 a| 
Nome account tenant S3 (proprietario bucket)
 a| 
Il nome dell'account tenant per il proprietario del bucket. Utilizzato per identificare l'accesso anonimo o multiaccount.



 a| 
SBAI
 a| 
ID account tenant S3 (proprietario bucket)
 a| 
L'ID account tenant del proprietario del bucket di destinazione. Utilizzato per identificare l'accesso anonimo o multiaccount.



 a| 
SGRP
 a| 
Sito (gruppo)
 a| 
Se presente, l'oggetto è stato eliminato nel sito specificato, che non è il sito in cui è stato acquisito l'oggetto.



 a| 
SUSR
 a| 
S3 User URN (richiesta mittente)
 a| 
L'ID account tenant e il nome utente dell'utente che effettua la richiesta. L'utente può essere un utente locale o LDAP. Ad esempio: `urn:sgws:identity::03393893651506583485:root`

Vuoto per richieste anonime.



 a| 
ORA
 a| 
Ora
 a| 
Tempo totale di elaborazione della richiesta in microsecondi.



 a| 
TLIP
 a| 
Indirizzo IP del bilanciamento del carico attendibile
 a| 
Se la richiesta è stata instradata da un bilanciamento del carico di livello 7 attendibile, l'indirizzo IP del bilanciamento del carico.



 a| 
UDM
 a| 
Identificatore univoco universale per un marcatore di cancellazione
 a| 
L'identificatore di un marcatore di eliminazione. I messaggi del registro di controllo specificano UUDM o UUID, dove UUDM indica un marcatore di eliminazione creato come risultato di una richiesta di eliminazione dell'oggetto e UUID indica un oggetto.



 a| 
UUID
 a| 
Universally Unique Identifier
 a| 
L'identificatore dell'oggetto all'interno del sistema StorageGRID.



 a| 
VSID
 a| 
ID versione
 a| 
L'ID versione della versione specifica di un oggetto eliminato. Le operazioni su bucket e oggetti in bucket senza versione non includono questo campo.

|===