---
permalink: audit/srem-object-store-remove.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SREM, Object Store Remove 
summary: Questo messaggio viene inviato quando il contenuto viene rimosso dallo storage persistente e non è più accessibile tramite API regolari. 
---
= SREM: Rimozione dell'archivio di oggetti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo messaggio viene inviato quando il contenuto viene rimosso dallo storage persistente e non è più accessibile tramite API regolari.

[cols="1a,1a,4a"]
|===
| Codice | Campo | Descrizione 


 a| 
CBID
 a| 
Identificatore del blocco di contenuto
 a| 
Identificatore univoco del blocco di contenuto cancellato dallo storage permanente.



 a| 
RSLT
 a| 
Codice risultato
 a| 
Indica il risultato delle operazioni di rimozione del contenuto. L'unico valore definito è:

SUC: Contenuto rimosso dallo storage persistente

|===
Questo messaggio di audit indica che un dato blocco di contenuto è stato cancellato da un nodo e non può più essere richiesto direttamente. Il messaggio può essere utilizzato per tenere traccia del flusso di contenuti cancellati all'interno del sistema.
