---
permalink: audit/sysd-node-stop.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SYSD, Node Stop 
summary: 'Quando un servizio viene arrestato correttamente, viene generato questo messaggio per indicare che è stato richiesto lo shutdown. In genere, questo messaggio viene inviato solo dopo un riavvio successivo, in quanto la coda dei messaggi di controllo non viene cancellata prima dell"arresto. Se il servizio non è stato riavviato, cercare il messaggio SYST inviato all"inizio della sequenza di arresto.' 
---
= SYSD: Interruzione nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando un servizio viene arrestato correttamente, viene generato questo messaggio per indicare che è stato richiesto lo shutdown. In genere, questo messaggio viene inviato solo dopo un riavvio successivo, in quanto la coda dei messaggi di controllo non viene cancellata prima dell'arresto. Se il servizio non è stato riavviato, cercare il messaggio SYST inviato all'inizio della sequenza di arresto.

[cols="1a,1a,4a"]
|===
| Codice | Campo | Descrizione 


 a| 
RSLT
 a| 
Pulizia dello spegnimento
 a| 
La natura dello shutdown:

SUCS: Il sistema è stato spento in modo pulito.

|===
Il messaggio non indica se il server host viene arrestato, ma solo il servizio di reporting. L'RSLT di un SYSD non può indicare uno shutdown "anomalo", perché il messaggio viene generato solo dagli shutdown "puliti".
