---
permalink: audit/using-audit-explain-tool.html 
sidebar: sidebar 
keywords: storagegrid, audit, tool, audit-explain, audit explain, translate audit messages, translate messages, translate audit message, translate message 
summary: 'È possibile utilizzare lo strumento di spiegazione dell"audit per tradurre i messaggi di audit nel log di audit in in un formato di facile lettura.' 
---
= Utilizzare lo strumento di verifica e spiegazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `audit-explain` lo strumento per convertire i messaggi di controllo nel registro di controllo in un formato di facile lettura.

.Prima di iniziare
* Si dispone di link:../admin/admin-group-permissions.html["autorizzazioni di accesso specifiche"].
* È necessario disporre del `Passwords.txt` file.
* È necessario conoscere l'indirizzo IP del nodo di amministrazione primario.


.A proposito di questa attività
 `audit-explain`Lo strumento, disponibile sul nodo amministrativo principale, fornisce riepiloghi semplificati dei messaggi di controllo in un registro di controllo.


NOTE:  `audit-explain`Lo strumento è destinato principalmente all'uso da parte del supporto tecnico durante le operazioni di risoluzione dei problemi. Le query di elaborazione `audit-explain` possono consumare una grande quantità di potenza della CPU, che potrebbe avere un impatto sulle operazioni StorageGRID.

Questo esempio mostra l'output tipico `audit-explain` dello strumento. Questi quattro link:sput-s3-put.html["SPUT"]messaggi di controllo sono stati generati quando il tenant S3 con ID account 92484777680322627870 utilizzava S3 richieste PUT per creare un bucket denominato "bucket1" e aggiungere tre oggetti a quel bucket.

[listing]
----
SPUT S3 PUT bucket bucket1 account:92484777680322627870 usec:124673
SPUT S3 PUT object bucket1/part1.txt tenant:92484777680322627870  cbid:9DCB157394F99FE5 usec:101485
SPUT S3 PUT object bucket1/part2.txt tenant:92484777680322627870  cbid:3CFBB07AB3D32CA9 usec:102804
SPUT S3 PUT object bucket1/part3.txt tenant:92484777680322627870  cbid:5373D73831ECC743 usec:93874
----
Lo `audit-explain` strumento può effettuare le seguenti operazioni:

* Elaborazione di registri di audit semplici o compressi. Ad esempio:
+
`audit-explain audit.log`

+
`audit-explain 2019-08-12.txt.gz`

* Elaborazione simultanea di più file. Ad esempio:
+
`audit-explain audit.log 2019-08-12.txt.gz 2019-08-13.txt.gz`

+
`audit-explain /var/local/log/*`

* Accettare l'input da una pipe, che consente di filtrare e pre-elaborare l'input utilizzando il `grep` comando o altri mezzi. Ad esempio:
+
`grep SPUT audit.log | audit-explain`

+
`grep bucket-name audit.log | audit-explain`



Poiché i registri di controllo possono essere molto grandi e lenti da analizzare, è possibile risparmiare tempo filtrando le parti che si desidera esaminare ed eseguire `audit-explain` sulle parti, anziché sull'intero file.

[NOTE]
====
 `audit-explain`Lo strumento non accetta file compressi come input di pipeline. Per elaborare i file compressi, fornire i nomi dei file come argomenti della riga di comando o utilizzare `zcat` lo strumento per decomprimere prima i file. Ad esempio:

`zcat audit.log.gz | audit-explain`

====
Utilizzare l' `help (-h)`opzione per visualizzare le opzioni disponibili. Ad esempio:

`$ audit-explain -h`

.Fasi
. Accedere al nodo di amministrazione principale:
+
.. Immettere il seguente comando: `ssh admin@_primary_Admin_Node_IP_`
.. Immettere la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla directory principale: `su -`
.. Immettere la password elencata nel `Passwords.txt` file.
+
Quando si è collegati come root, il prompt cambia da `$` a `#`.



. Immettere il seguente comando, dove `/var/local/log/audit.log` rappresenta il nome e la posizione del file o dei file che si desidera analizzare:
+
`$ audit-explain /var/local/log/audit.log`

+
 `audit-explain`Lo strumento stampa interpretazioni leggibili di tutti i messaggi nel file o nei file specificati.

+

NOTE: Per ridurre le lunghezze delle linee e agevolare la leggibilità, i timestamp non vengono visualizzati per impostazione predefinita. Se si desidera visualizzare i timestamp, utilizzare l'(`-t`opzione timestamp ).


