---
permalink: swnodes/collecting-information-about-your-deployment-environment.html 
sidebar: sidebar 
keywords: how to collect information about your vmware deployment environment 
summary: 'Prima di implementare i nodi grid, è necessario raccogliere informazioni sulla configurazione di rete e sull"ambiente VMware.' 
---
= Raccogli informazioni sul tuo ambiente di distribuzione (VMware)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di implementare i nodi grid, è necessario raccogliere informazioni sulla configurazione di rete e sull'ambiente VMware.


NOTE: È più efficiente eseguire una singola installazione di tutti i nodi, piuttosto che installare alcuni nodi ora e alcuni nodi successivamente.



== Informazioni VMware

È necessario accedere all'ambiente di implementazione e raccogliere informazioni sull'ambiente VMware, sulle reti create per Grid, Admin e Client Network e sui tipi di volumi di storage che si intende utilizzare per i nodi di storage.

È necessario raccogliere informazioni sull'ambiente VMware, tra cui:

* Il nome utente e la password di un account VMware vSphere che dispone delle autorizzazioni appropriate per completare l'implementazione.
* Informazioni sulla configurazione di rete, datastore e host per ogni macchina virtuale a nodi StorageGRID.



NOTE: VMware Live vMotion fa saltare il tempo di clock della macchina virtuale e non è supportato per i nodi grid di qualsiasi tipo. Anche se rari, tempi di clock errati possono causare la perdita di dati o aggiornamenti della configurazione.



== Informazioni Grid Network

È necessario raccogliere informazioni sulla rete VMware creata per la rete grid StorageGRID (richiesta), tra cui:

* Il nome della rete.
* Metodo utilizzato per assegnare indirizzi IP, statici o DHCP.
+
** Se si utilizzano indirizzi IP statici, i dettagli di rete richiesti per ciascun nodo della griglia (indirizzo IP, gateway, maschera di rete).
** Se si utilizza DHCP, l'indirizzo IP del nodo amministrativo primario sulla rete Grid. Per ulteriori informazioni, vedere link:how-grid-nodes-discover-primary-admin-node.html["In che modo i nodi della griglia rilevano il nodo di amministrazione primario"] .






== Admin Network Information (informazioni di rete amministratore

Per i nodi che saranno connessi alla rete amministrativa StorageGRID opzionale, è necessario raccogliere informazioni sulla rete VMware creata per questa rete, tra cui:

* Il nome della rete.
* Metodo utilizzato per assegnare indirizzi IP, statici o DHCP.
+
** Se si utilizzano indirizzi IP statici, i dettagli di rete richiesti per ciascun nodo della griglia (indirizzo IP, gateway, maschera di rete).
** Se si utilizza DHCP, l'indirizzo IP del nodo amministrativo primario sulla rete Grid. Per ulteriori informazioni, vedere link:how-grid-nodes-discover-primary-admin-node.html["In che modo i nodi della griglia rilevano il nodo di amministrazione primario"] .


* L'elenco di subnet esterne (ESL) per la rete di amministrazione.




== Informazioni di rete del client

Per i nodi che saranno connessi alla rete client StorageGRID opzionale, è necessario raccogliere informazioni sulla rete VMware creata per questa rete, tra cui:

* Il nome della rete.
* Metodo utilizzato per assegnare indirizzi IP, statici o DHCP.
* Se si utilizzano indirizzi IP statici, i dettagli di rete richiesti per ciascun nodo della griglia (indirizzo IP, gateway, maschera di rete).




== Informazioni su interfacce aggiuntive

È possibile aggiungere interfacce di accesso o trunk alla macchina virtuale in vCenter dopo aver installato il nodo. Ad esempio, è possibile aggiungere un'interfaccia di linea a un nodo Admin o Gateway, in modo da poter utilizzare le interfacce VLAN per separare il traffico che appartiene a diverse applicazioni o tenant. In alternativa, è possibile aggiungere un'interfaccia di accesso da utilizzare in un gruppo ad alta disponibilità (ha).

Le interfacce aggiunte vengono visualizzate nella pagina delle interfacce VLAN e nella pagina dei gruppi ha in Grid Manager.

* Se si aggiunge un'interfaccia di linea, configurare una o più interfacce VLAN per ogni nuova interfaccia principale. Vedere link:../admin/configure-vlan-interfaces.html["Configurare le interfacce VLAN"].
* Se si aggiunge un'interfaccia di accesso, è necessario aggiungerla direttamente ai gruppi ha. Vedere link:../admin/configure-high-availability-group.html["configurare i gruppi ad alta disponibilità"].




== Volumi di storage per nodi di storage virtuali

Per i nodi di storage basati su macchine virtuali, è necessario raccogliere le seguenti informazioni:

* Il numero e le dimensioni dei volumi di archiviazione (LUN di archiviazione) che si intende aggiungere. Vedere link:storage-and-performance-requirements.html["Requisiti di storage e performance"].




== Informazioni sulla configurazione della griglia

È necessario raccogliere informazioni per configurare la griglia:

* Licenza Grid
* Indirizzi IP del server NTP (Network Time Protocol)
* Indirizzi IP del server DNS

