---
permalink: swnodes/configuring-docker-storage-volume.html 
sidebar: sidebar 
keywords: how to configure container engine storage volume, Docker, Podman 
summary: Prima di installare il motore del contenitore Docker o Podman, potrebbe essere necessario formattare il volume di archiviazione e montarlo. 
---
= Configurare il volume di archiviazione del motore del contenitore (Linux)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare il motore del contenitore Docker o Podman, potrebbe essere necessario formattare il volume di archiviazione e montarlo.


NOTE: Il supporto di Docker come motore container per implementazioni solo software è obsoleto. In una release futura, Docker sostituirà un altro motore per container.


NOTE: "Linux" si riferisce a una distribuzione RHEL, Ubuntu o Debian.  Per un elenco delle versioni supportate, vedere https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità NetApp (IMT)"^] .

.A proposito di questa attività
È possibile saltare questi passaggi se si prevede di utilizzare il volume root per il volume di archiviazione Docker o Podman e si dispone di spazio sufficiente sulla partizione host contenente:

* Podman: `/var/lib/containers`
* Docker: `/var/lib/docker`


.Fasi
. Creare un file system sul volume di storage del motore dei container:
+
[role="tabbed-block"]
====
.RHEL
--
[listing]
----
sudo mkfs.ext4 container-engine-storage-volume-device
----
--
.Ubuntu o Debian
--
[listing]
----
sudo mkfs.ext4 docker-storage-volume-device
----
--
====
. Montare il volume di storage del motore dei container:
+
[role="tabbed-block"]
====
.RHEL
--
** Per Docker:
+
[listing]
----
sudo mkdir -p /var/lib/docker
sudo mount container-storage-volume-device /var/lib/docker
----
** Per Podman:
+
[listing]
----
sudo mkdir -p /var/lib/containers
sudo mount container-storage-volume-device /var/lib/containers
----


--
.Ubuntu o Debian
--
[listing]
----
sudo mkdir -p /var/lib/docker
sudo mount docker-storage-volume-device /var/lib/docker
----
** Per Podman:
+
[listing]
----
sudo mkdir -p /var/lib/podman
sudo mount container-storage-volume-device /var/lib/podman
----


--
====
. Aggiungere una voce per il dispositivo del volume di archiviazione del contenitore a /etc/fstab.
+
** RHEL: dispositivo di archiviazione del volume del contenitore
** Ubuntu o Debian: docker-storage-volume-device
+
Questo passaggio garantisce che il volume di storage venga rimontato automaticamente dopo il riavvio dell'host.







== Installare Docker

Il sistema StorageGRID può essere eseguito su Linux come una raccolta di contenitori.

* Prima di poter installare StorageGRID per Ubuntu o Debian, è necessario installare Docker.
* Se hai scelto di utilizzare il motore del contenitore Docker, segui questi passaggi per installare Docker.  Altrimenti,<<install-podman-rhel,Installare Podman>> .



NOTE: Il supporto di Docker come motore container per implementazioni solo software è obsoleto. In una release futura, Docker sostituirà un altro motore per container.

.Fasi
. Installare Docker seguendo le istruzioni per la distribuzione Linux.
+

NOTE: Se Docker non è incluso nella distribuzione Linux, è possibile scaricarlo dal sito Web di Docker.

. Assicurarsi che Docker sia stato attivato e avviato eseguendo i seguenti due comandi:
+
[listing]
----
sudo systemctl enable docker
----
+
[listing]
----
sudo systemctl start docker
----
. Verificare di aver installato la versione prevista di Docker inserendo quanto segue:
+
[listing]
----
sudo docker version
----
+
Le versioni Client e Server devono essere 1.11.0 o successive.





== Installare Podman

Il sistema StorageGRID funziona come una raccolta di contenitori.  Se hai scelto di utilizzare il motore contenitore Podman, segui questi passaggi per installare Podman.  Altrimenti,<<Installare Docker,Installare Docker>> .

.Fasi
. Installare Podman e Podman-Docker seguendo le istruzioni per la distribuzione Linux.
+

NOTE: Devi anche installare il pacchetto Podman-Docker quando installi Podman.

. Verificare di aver installato la versione prevista di Podman e Podman-Docker inserendo quanto segue:
+
[listing]
----
sudo docker version
----
+

NOTE: Il pacchetto Podman-Docker consente di utilizzare i comandi Docker.

+
Le versioni Client e Server devono essere 3.2.3 o successive.

+
[listing]
----
Version: 3.2.3
API Version: 3.2.3
Go Version: go1.15.7
Built: Tue Jul 27 03:29:39 2021
OS/Arch: linux/amd64
----


.Informazioni correlate
link:configuring-host-storage.html["Configurare lo storage host"]
