---
permalink: swnodes/cpu-and-ram-requirements.html 
sidebar: sidebar 
keywords: cpu, ram, cpu cores 
summary: 'Prima di installare il software StorageGRID, verificare e configurare l"hardware in modo che sia pronto per il supporto del sistema StorageGRID.' 
---
= Requisiti di CPU e RAM per StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare il software StorageGRID, verificare e configurare l'hardware in modo che sia pronto per il supporto del sistema StorageGRID.

Ogni nodo StorageGRID richiede le seguenti risorse minime:

* Core CPU: 8 per nodo
* RAM: A seconda della RAM totale disponibile e della quantità di software non StorageGRID in esecuzione sul sistema
+
** In genere, almeno 24 GB per nodo e da 2 a 16 GB in meno rispetto alla RAM totale del sistema
** Se più tenant hanno ciascuno fino a 5.000 bucket, almeno 64 GB per nodo
+

NOTE: Il sistema StorageGRID supporta un massimo di 20.000 bucket per ogni account tenant S3.





Le risorse dei nodi di solo metadati basate su software devono corrispondere alle risorse dei nodi di storage esistenti. Ad esempio:

* Se il sito StorageGRID esistente utilizza appliance SG6000 o SG6100, i nodi basati solo sui metadati software devono soddisfare i seguenti requisiti minimi:
+
** 128 GB DI RAM
** CPU a 8 core
** SSD da 8 TB o storage equivalente per il database Cassandra (rangedb/0)


* Se il sito StorageGRID esistente utilizza nodi di archiviazione virtuali con 24 GB di RAM, CPU a 8 core e 3 TB o 4 TB di spazio di archiviazione dei metadati, i nodi basati solo su software devono utilizzare risorse simili (24 GB di RAM, CPU a 8 core e 4 TB di spazio di archiviazione dei metadati (rangedb/0)).


Quando si aggiunge un nuovo sito StorageGRID, la capacità totale dei metadati del nuovo sito deve almeno StorageGRID corrispondere ai nodi storage dei siti StorageGRID esistenti e alle nuove risorse del sito.


NOTE: "Linux" si riferisce a una distribuzione RHEL, Ubuntu o Debian.  Per un elenco delle versioni supportate, vedere https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità NetApp (IMT)"^] .

[role="tabbed-block"]
====
.Linux
--
Assicurarsi che il numero di nodi StorageGRID che si intende eseguire su ciascun host fisico o virtuale non superi il numero di core CPU o la RAM fisica disponibile. Se gli host non sono dedicati all'esecuzione di StorageGRID (non consigliato), assicurarsi di prendere in considerazione i requisiti di risorse delle altre applicazioni.

--
.VMware
--
VMware supporta un nodo per macchina virtuale. Assicurarsi che il nodo StorageGRID non superi la RAM fisica disponibile. Ciascuna macchina virtuale deve essere dedicata all'esecuzione di StorageGRID.

--
====

CAUTION: Monitora regolarmente l'utilizzo di CPU e memoria per assicurarti che queste risorse continuino a supportare il tuo carico di lavoro. Ad esempio, raddoppiare l'allocazione di RAM e CPU per i nodi di archiviazione virtuali fornirebbe risorse simili a quelle fornite per i nodi appliance StorageGRID. Inoltre, se la quantità di metadati per nodo supera 500 GB, valuta di aumentare la RAM per nodo a 48 GB o più. Per informazioni sulla gestione dell'archiviazione dei metadati degli oggetti, sull'aumento dell'impostazione Spazio riservato ai metadati e sul monitoraggio dell'utilizzo di CPU e memoria, consulta le istruzioni per link:../admin/index.html["amministrazione"], link:../monitor/index.html["monitoraggio"] e link:../upgrade/index.html["aggiornamento in corso"] StorageGRID.

Se l'hyperthreading è attivato sugli host fisici sottostanti, è possibile fornire 8 core virtuali (4 core fisici) per nodo. Se l'hyperthreading non è attivato sugli host fisici sottostanti, è necessario fornire 8 core fisici per nodo.

Se si utilizzano macchine virtuali come host e si ha il controllo sulle dimensioni e sul numero di macchine virtuali, è necessario utilizzare una singola macchina virtuale per ciascun nodo StorageGRID e dimensionare di conseguenza la macchina virtuale.

(Solo RHEL, Debian e Ubuntu) Per le distribuzioni di produzione, non dovresti eseguire più nodi di archiviazione sullo stesso hardware di archiviazione fisico o host virtuale.  Ogni nodo di archiviazione in una singola distribuzione StorageGRID dovrebbe trovarsi nel proprio dominio di errore isolato.  È possibile massimizzare la durabilità e la disponibilità dei dati degli oggetti se ci si assicura che un singolo guasto hardware possa avere un impatto solo su un singolo nodo di archiviazione.

Consulta link:storage-and-performance-requirements.html["Requisiti di storage e performance"].
