---
permalink: swnodes/overview-of-installation-rest-api.html 
sidebar: sidebar 
keywords: installation REST API 
summary: 'StorageGRID fornisce l"API di installazione di StorageGRID per eseguire le attività di installazione.' 
---
= Scopri l'API REST di installazione di StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID fornisce l'API di installazione di StorageGRID per eseguire le attività di installazione.

L'API utilizza la piattaforma API open source Swagger per fornire la documentazione API. Swagger consente agli sviluppatori e ai non sviluppatori di interagire con l'API in un'interfaccia utente che illustra il modo in cui l'API risponde a parametri e opzioni. La presente documentazione presuppone che l'utente abbia familiarità con le tecnologie Web standard e il formato dati JSON.


CAUTION: Tutte le operazioni API eseguite utilizzando la pagina Web documentazione API sono operazioni in tempo reale. Fare attenzione a non creare, aggiornare o eliminare per errore i dati di configurazione o altri dati.

Ogni comando REST API include l'URL dell'API, un'azione HTTP, qualsiasi parametro URL richiesto o opzionale e una risposta API prevista.



[[storagegrid-installation-api]]
== API di installazione StorageGRID

L'API di installazione di StorageGRID è disponibile solo quando si configura inizialmente il sistema StorageGRID e se è necessario eseguire un ripristino primario del nodo di amministrazione. È possibile accedere all'API di installazione tramite HTTPS da Grid Manager.

Per accedere alla documentazione API, accedere alla pagina Web di installazione nel nodo di amministrazione principale e selezionare *Guida* > *documentazione API* dalla barra dei menu.

L'API di installazione di StorageGRID include le seguenti sezioni:

* *config*: Operazioni relative alla release del prodotto e alle versioni dell'API. Puoi elencare la versione della release del prodotto e le versioni principali dell'API supportate da quella release.
* *griglia*: Operazioni di configurazione a livello di griglia. Puoi ottenere e aggiornare le impostazioni della griglia, inclusi i dettagli della griglia, le subnet della Grid Network, le password della griglia e gli indirizzi IP dei server NTP e DNS server.
* *nodi*: Operazioni di configurazione a livello di nodo. Puoi recuperare un elenco di nodi della griglia, eliminare un nodo della griglia, configurare un nodo della griglia, visualizzare un nodo della griglia e reimpostare la configurazione di un nodo della griglia.
* *provision*: Operazioni di provisioning. Puoi avviare l'operazione di provisioning e visualizzarne lo stato.
* *recovery*: Operazioni di ripristino del nodo Admin primario. Puoi reimpostare le informazioni, caricare il Recovery Package, avviare il ripristino e visualizzare lo stato dell'operazione di ripristino.
* *recovery-package*: Operazioni per scaricare il pacchetto di ripristino.
* *siti*: Operazioni di configurazione a livello di sito. Puoi creare, visualizzare, eliminare e modificare un sito.
* *password temporanea*: Operazioni sulla password temporanea per proteggere la mgmt-api durante l'installazione.

