---
permalink: swnodes/required-materials.html 
sidebar: sidebar 
keywords: installation materials 
summary: Prima di installare StorageGRID, raccogliere e preparare le informazioni e il materiale necessari. 
---
= Informazioni e materiali richiesti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare StorageGRID, raccogliere e preparare le informazioni e il materiale necessari.



== Informazioni richieste

Piano di rete:: Quali reti intendi collegare a ogni nodo StorageGRID? StorageGRID supporta più reti per la separazione del traffico, la sicurezza e la convenienza amministrativa.
+
--
Vedere StorageGRID link:../network/index.html["Linee guida per il networking"].

--
Informazioni di rete:: Indirizzi IP da assegnare a ciascun nodo di rete e indirizzi IP dei server DNS e NTP.
Server per i nodi grid:: Identificare un insieme di server (fisici, virtuali o entrambi) che, in aggregato, forniscono risorse sufficienti per supportare il numero e il tipo di nodi StorageGRID che si intende implementare.
+
--

NOTE: Se l'installazione di StorageGRID non utilizza nodi di storage (hardware) dell'appliance StorageGRID, è necessario utilizzare lo storage RAID hardware con cache di scrittura supportata dalla batteria (BBWC). StorageGRID non supporta l'utilizzo di reti VSAN (Virtual Storage Area Network), RAID software o nessuna protezione RAID.

--
Migrazione dei nodi (solo Ubuntu e Debian, se necessario):: Comprendere il link:node-container-migration-requirements.html["requisiti per la migrazione dei nodi"], se si desidera eseguire la manutenzione pianificata sugli host fisici senza alcuna interruzione del servizio.
Informazioni correlate:: https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità NetApp"^]




== Materiali richiesti

Licenza NetApp StorageGRID:: È necessario disporre di una licenza NetApp valida con firma digitale.



NOTE: Nell'archivio di installazione di StorageGRID è inclusa una licenza non di produzione, che può essere utilizzata per test e griglie di prova.

Archivio di installazione di StorageGRID:: link:downloading-and-extracting-storagegrid-installation-files.html["Scaricare l'archivio di installazione di StorageGRID ed estrarre i file"].
Laptop di assistenza:: Il sistema StorageGRID viene installato tramite un laptop di assistenza.
+
--
Il laptop di assistenza deve disporre di:

* Porta di rete
* Client SSH (ad esempio, putty)
* link:../admin/web-browser-requirements.html["Browser Web supportato"]


--
Documentazione StorageGRID::
+
--
* link:../release-notes/index.html["Note di rilascio"]
* link:../admin/index.html["Istruzioni per l'amministrazione di StorageGRID"]


--

