---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: StorageGRID 12.0 utilizza la versione 4 della Grid Management API.  La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate. 
---
= Modifiche all'API Grid Management
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.0 utilizza la versione 4 della Grid Management API.  La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.


NOTE: È possibile continuare a utilizzare le versioni obsolete dell'API di gestione con StorageGRID 12.0; tuttavia, il supporto per queste versioni dell'API verrà rimosso in una futura versione di StorageGRID.  Dopo l'aggiornamento a StorageGRID 12.0, è possibile disattivare le API deprecate utilizzando `PUT /grid/config/management` API.

Per ulteriori informazioni, visitare il sito Web all'indirizzo link:../admin/using-grid-management-api.html["Utilizzare l'API Grid Management"].



== Nuovi endpoint per i bucket di filiale

Sono stati aggiunti i seguenti endpoint per consentirti dilink:../tenant/what-is-branch-bucket.html["gestire i bucket delle filiali"] :

`GET /org/containers/{branchBucketName}/branch`

`PUT /org/containers/{branchBucketName}/branch`



== Nuovi endpoint privati per Move ADC

Sono stati aggiunti i seguenti endpoint privati per consentirti dilink:../maintain/move-adc-service.html["spostare il servizio ADC"] da un nodo di archiviazione a un altro nello stesso sito:

`/private/move-adc`

`/private/move-adc/start`

`/private/move-adc/retry`



== Nuovi endpoint privati per la conversione in nodo solo dati

Sono stati aggiunti i seguenti endpoint privati per consentirti dilink:../maintain/convert-to-data-only-node.html["convertire uno o più nodi di archiviazione combinati"] che non contengono il servizio ADC in nodi solo dati.

`/private/convert-to-data-only-node`

`/private/convert-to-data-only-node/start`

`/private/convert-to-data-only-node/retry`
