---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: 'StorageGRID 11,9 utilizza la versione 4 dell"API di gestione dei tenant. La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.' 
---
= Modifiche all'API di gestione del tenant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11,9 utilizza la versione 4 dell'API di gestione dei tenant. La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.


NOTE: È possibile continuare a utilizzare le versioni obsolete dell'API di gestione dei tenant con StorageGRID 11,9; tuttavia, il supporto per queste versioni dell'API verrà rimosso in una versione futura di StorageGRID. Dopo l'aggiornamento a StorageGRID 11,9, è possibile disattivare le API obsolete utilizzando l' `PUT /grid/config/management`API.

Per ulteriori informazioni, visitare il sito Web all'indirizzo link:../tenant/understanding-tenant-management-api.html["Comprendere l'API di gestione dei tenant"].



== Nuova API per il limite di capacità della benna

Puoi utilizzare l' `/org/containers/{bucketName}/quota-object-bytes`API con operazioni GET/PUT per ottenere e impostare il limite di capacità dello storage per un bucket.
