---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: 'StorageGRID 11,9 utilizza la versione 4 dell"API di gestione delle griglie. La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.' 
---
= Modifiche all'API Grid Management
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11,9 utilizza la versione 4 dell'API di gestione delle griglie. La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.


NOTE: È possibile continuare a utilizzare versioni obsolete dell'API di gestione con StorageGRID 11,9; tuttavia, il supporto per queste versioni dell'API verrà rimosso in una versione futura di StorageGRID. Dopo l'aggiornamento a StorageGRID 11,9, è possibile disattivare le API obsolete utilizzando l' `PUT /grid/config/management`API.

Per ulteriori informazioni, visitare il sito Web all'indirizzo link:../admin/using-grid-management-api.html["Utilizzare l'API Grid Management"].



== Rivedere le impostazioni di conformità dopo l'attivazione del blocco oggetti S3 globale

Rivedere le impostazioni di conformità dei tenant esistenti dopo aver attivato l'impostazione blocco oggetto S3 globale. Quando si attiva questa impostazione, le impostazioni di blocco degli oggetti S3 per tenant dipendono dalla release di StorageGRID al momento della creazione del tenant.



== Richieste api di gestione legacy rimosse

Queste richieste legacy sono state rimosse:

`/grid/server-types`

`/grid/ntp-roles`



== Modifiche all' `GET /private/storage-usage`API

* Una nuova proprietà, `usageCacheDuration`, è stata aggiunta al corpo della risposta. Questa proprietà specifica la durata (in secondi) per la quale la cache di ricerca dell'utilizzo rimane valida. Questo valore si applica al momento di verificare l'utilizzo rispetto ai limiti di quota di storage del tenant e di capacità del bucket.
* Il `GET /api/v4/private/storage-usage` comportamento è stato corretto in modo che corrisponda al nesting dallo schema.
* Queste modifiche si applicano solo all'API privata.




== Modifiche all' `GET cross-grid-replication`API

L'API di RECUPERO */org/containers/:name/cross-grid-Replication* non richiede più l'(`rootAccess`autorizzazione di accesso root ); tuttavia, è necessario appartenere a un gruppo di utenti che dispone dell'(`viewAllContainers`autorizzazione Gestisci tutti i bucket (`manageAllContainers`) o Visualizza tutti i bucket ).

L'API PUT */org/containers/:name/cross-grid-Replication* è invariata e richiede comunque l'(`rootAccess`autorizzazione root access ).
