---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: 'StorageGRID 12,0 utilizza la versione 4 dell"API di gestione delle griglie. La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.' 
---
= Modifiche all'API Grid Management
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12,0 utilizza la versione 4 dell'API di gestione delle griglie. La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.


NOTE: È possibile continuare a utilizzare versioni obsolete dell'API di gestione con StorageGRID 12,0; tuttavia, il supporto per queste versioni dell'API verrà rimosso in una versione futura di StorageGRID. Dopo l'aggiornamento a StorageGRID 12,0, è possibile disattivare le API obsolete utilizzando l' `PUT /grid/config/management`API.

Per ulteriori informazioni, visitare il sito Web all'indirizzo link:../admin/using-grid-management-api.html["Utilizzare l'API Grid Management"].



== Nuovi endpoint privati per spostare ADC

Sono stati aggiunti i seguenti endpoint privati per consentire di passare link:../maintain/move-adc-service.html["Spostare il servizio ADC"] da un nodo di storage a un altro nello stesso sito:

`/private/move-adc`

`/private/move-adc/start`

`/private/move-adc/retry`
