---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: 'StorageGRID 12.0 utilizza la versione 4 dell"API Tenant Management.  La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.' 
---
= Modifiche all'API di gestione del tenant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.0 utilizza la versione 4 dell'API Tenant Management.  La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.


NOTE: È possibile continuare a utilizzare le versioni obsolete dell'API Tenant Management con StorageGRID 12.0; tuttavia, il supporto per queste versioni dell'API verrà rimosso in una futura versione di StorageGRID.  Dopo l'aggiornamento a StorageGRID 12.0, è possibile disattivare le API deprecate utilizzando `PUT /grid/config/management` API.

Per ulteriori informazioni, visitare il sito Web all'indirizzo link:../tenant/understanding-tenant-management-api.html["Comprendere l'API di gestione dei tenant"].



== Nuova API per la replicazione degli oggetti

Puoi usare il `/org/cross-grid-replication/{versionId}/replicate` API per replicare manualmente gli oggetti su un bucket esistente con replica tra griglie appena configurata.
