---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: 'Prima di aggiornare un sistema StorageGRID, verificare che il sistema sia pronto per l"aggiornamento. Verificare che il sistema funzioni normalmente e che tutti i nodi della griglia siano operativi.' 
---
= Controlla le condizioni del tuo sistema StorageGRID prima di eseguire l'aggiornamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di aggiornare un sistema StorageGRID, verificare che il sistema sia pronto per l'aggiornamento. Verificare che il sistema funzioni normalmente e che tutti i nodi della griglia siano operativi.

.Fasi
. Accedere a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
. Verificare la presenza di eventuali avvisi attivi e risolverli.
. Consulta link:../network/internal-grid-node-communications.html["Comunicazioni interne al nodo di rete"] e link:../network/external-communications.html["Comunicazioni esterne"] per assicurarti che tutte le porte richieste per StorageGRID 12.1 siano aperte prima di eseguire l'upgrade.
+

NOTE: Non sono necessarie porte aggiuntive per l'aggiornamento a StorageGRID 12.1.


