---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: 'Prima di aggiornare un sistema StorageGRID, verificare che il sistema sia pronto per l"aggiornamento. Verificare che il sistema funzioni normalmente e che tutti i nodi della griglia siano operativi.' 
---
= Controllare le condizioni del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di aggiornare un sistema StorageGRID, verificare che il sistema sia pronto per l'aggiornamento. Verificare che il sistema funzioni normalmente e che tutti i nodi della griglia siano operativi.

.Fasi
. Accedere a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
. Verificare la presenza di eventuali avvisi attivi e risolverli.
. Fare riferimento alink:../network/internal-grid-node-communications.html["Comunicazioni interne al nodo di rete"] Elink:../network/external-communications.html["Comunicazioni esterne"] per garantire che tutte le porte richieste per StorageGRID 12.0 siano aperte prima dell'aggiornamento.
+

NOTE: Non sono necessarie porte aggiuntive durante l'aggiornamento a StorageGRID 12.0.


