---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: 'Prima di aggiornare un sistema StorageGRID, verificare che il sistema sia pronto per l"aggiornamento. Verificare che il sistema funzioni normalmente e che tutti i nodi della griglia siano operativi.' 
---
= Controllare le condizioni del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di aggiornare un sistema StorageGRID, verificare che il sistema sia pronto per l'aggiornamento. Verificare che il sistema funzioni normalmente e che tutti i nodi della griglia siano operativi.

.Fasi
. Accedere a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
. Verificare la presenza di eventuali avvisi attivi e risolverli.
. Verificare che non vi siano attività della griglia in conflitto attive o in sospeso.
+
.. Selezionare *SUPPORT* > *Tools* > *Grid topology*.
.. Selezionare *_Site_* > *_Primary Admin Node_* > *CMN* > *Grid Tasks* > *Configuration*.
+
I task ILME (Information Lifecycle Management Evaluation) sono gli unici task grid che possono essere eseguiti contemporaneamente all'aggiornamento del software.

.. Se altre attività della griglia sono attive o in sospeso, attendere il completamento o rilasciare il blocco.
+

NOTE: Contattare il supporto tecnico se un'attività non termina o non rilascia il blocco.



. Prima di eseguire l'aggiornamento, consultare la link:../network/internal-grid-node-communications.html["Comunicazioni interne al nodo di rete"] e link:../network/external-communications.html["Comunicazioni esterne"]la per assicurarsi che tutte le porte richieste per StorageGRID 11,9 siano aperte.
+

NOTE: Non sono richieste porte aggiuntive per l'upgrade a StorageGRID 11,9.

+
La seguente porta richiesta è stata aggiunta in StorageGRID 11,7. Assicurarsi che sia disponibile prima di eseguire l'aggiornamento a StorageGRID 11,9.

+
[cols="1a,2a"]
|===
| Porta | Descrizione 


 a| 
18086
 a| 
Porta TCP utilizzata per le richieste S3 dal bilanciamento del carico StorageGRID a LDR e al nuovo servizio LDR.

Prima di eseguire l'aggiornamento, verificare che la porta sia aperta da tutti i nodi della griglia a tutti i nodi di archiviazione.

Il blocco di questa porta causerà S3 interruzioni del servizio dopo l'aggiornamento a StorageGRID 11,9.

|===



CAUTION: Se sono state aperte porte firewall personalizzate, viene inviata una notifica durante la verifica preliminare dell'aggiornamento. È necessario contattare il supporto tecnico prima di procedere con l'aggiornamento.
