---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 'Scopri in che modo il tuo sistema StorageGRID sarà influenzato durante l"aggiornamento.' 
---
= Impatto del sistema durante l'aggiornamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri in che modo il tuo sistema StorageGRID sarà influenzato durante l'aggiornamento.



== L'accesso SSH esterno è consentito fino al completamento dell'aggiornamento

Durante l'aggiornamento è consentito l'accesso SSH esterno.  Al termine dell'aggiornamento, l'accesso SSH esterno viene bloccato per impostazione predefinita.  Dopo l'aggiornamento, puoi utilizzare la scheda *Blocca SSH* disponibile nella pagina *Gestione griglia* > *Impostazioni di sicurezza* perlink:../admin/manage-external-ssh-access.html["gestire l'accesso SSH esterno"] .  L'accesso SSH tra i nodi della griglia non è interessato.



== Gli aggiornamenti di StorageGRID sono senza interruzioni

Il sistema StorageGRID è in grado di acquisire e recuperare i dati dalle applicazioni client durante l'intero processo di aggiornamento. Se si approvano tutti i nodi dello stesso tipo per l'aggiornamento (ad esempio, i nodi di storage), i nodi vengono disattivati uno alla volta, in modo che non vi sia tempo in cui tutti i nodi di griglia o tutti i nodi di griglia di un determinato tipo non siano disponibili.

Per consentire la disponibilità continua, assicurarsi che il criterio ILM contenga regole che specificano la memorizzazione di più copie di ciascun oggetto. È inoltre necessario assicurarsi che tutti i client S3 esterni siano configurati per inviare richieste a uno dei seguenti:

* Un indirizzo IP virtuale del gruppo ad alta disponibilità (ha)
* Bilanciamento del carico di terze parti ad alta disponibilità
* Nodi gateway multipli per ogni client
* Più nodi di storage per ogni client




== Le applicazioni client potrebbero riscontrare interruzioni a breve termine

Il sistema StorageGRID può acquisire e recuperare i dati dalle applicazioni client durante tutto il processo di upgrade, tuttavia le connessioni client a singoli nodi di gateway o nodi storage potrebbero essere temporaneamente interrotte se l'upgrade deve riavviare i servizi su tali nodi. La connettività viene ripristinata al termine del processo di upgrade e i servizi vengono ripristinati nei singoli nodi.

Potrebbe essere necessario pianificare i tempi di inattività per applicare un aggiornamento se la perdita di connettività per un breve periodo non è accettabile. È possibile utilizzare l'approvazione selettiva per pianificare l'aggiornamento di determinati nodi.


NOTE: È possibile utilizzare più gateway e gruppi di alta disponibilità (ha) per fornire il failover automatico durante il processo di upgrade. Vedere le istruzioni per link:../admin/configure-high-availability-group.html["configurazione di gruppi ad alta disponibilità"].



== Le riparazioni in background non verranno eseguite su griglie con nodi di versione mista

Le riparazioni in background non vengono eseguite durante l'aggiornamento quando la griglia contiene nodi con versioni miste.  Eventuali incongruenze che si verificano durante un'interruzione del sito non verranno riparate fino al completamento dell'aggiornamento.



== Il firmware dell'appliance viene aggiornato

Durante l'aggiornamento StorageGRID 12.0:

* Tutti i nodi dell'appliance StorageGRID vengono automaticamente aggiornati alla versione 12.0 del firmware StorageGRID Appliance Installer.
* Gli apparecchi SG6060 e SGF6024 vengono aggiornati automaticamente alla versione firmware BIOS 3B08.EX e alla versione firmware BMC 4.01.07.
* Gli apparecchi SG100 e SG1000 vengono automaticamente aggiornati alla versione firmware BIOS 3B13.EC e alla versione firmware BMC 4.75.07.
* Gli apparecchi SGF6112, SG6160, SG110 e SG1100 vengono automaticamente aggiornati alla versione firmware BIOS 3A14.QD e alla versione firmware BMC 3.19.07.




== Le policy ILM vengono gestite in modo diverso in base al loro stato

* Il criterio attivo rimane lo stesso dopo l'aggiornamento.
* Solo le ultime 10 politiche storiche vengono mantenute al momento dell'aggiornamento.
* Se esiste una policy proposta, verrà eliminata durante l'aggiornamento.




== Potrebbero essere attivati degli avvisi

Gli avvisi potrebbero essere attivati all'avvio e all'arresto dei servizi e quando il sistema StorageGRID funziona come ambiente a versione mista (alcuni nodi di griglia che eseguono una versione precedente, mentre altri sono stati aggiornati a una versione successiva). Al termine dell'aggiornamento potrebbero essere attivati altri avvisi.

Ad esempio, potresti visualizzare l'avviso *Impossibile comunicare con il nodo* quando i servizi sono arrestati oppure l'avviso *Errore di comunicazione Cassandra* quando alcuni nodi sono stati aggiornati a StorageGRID 12.0 ma altri nodi eseguono ancora StorageGRID 11.9.  In genere, questi avvisi scompariranno al termine dell'aggiornamento.

L'avviso *Posizionamento ILM non realizzabile* potrebbe essere attivato quando i nodi di archiviazione vengono arrestati durante l'aggiornamento a StorageGRID 12.0.  Questo avviso potrebbe persistere per 1 giorno dopo il completamento dell'aggiornamento.

Una volta completato l'aggiornamento, è possibile rivedere gli avvisi relativi all'aggiornamento selezionando *Avvisi risolti di recente* o *Avvisi correnti* dalla dashboard di Grid Manager.



== Le modifiche alla configurazione sono limitate


NOTE: Questo elenco si applica specificamente agli aggiornamenti da StorageGRID 11.9 a StorageGRID 12.0.  Se si esegue l'aggiornamento a un'altra versione StorageGRID , fare riferimento all'elenco delle modifiche limitate nelle istruzioni di aggiornamento per quella versione.

Fino al completamento dell'attività *Enable New Feature*:

* Non apportare modifiche alla configurazione della griglia.
* Non attivare o disattivare nuove funzioni.
* Non aggiornare la configurazione ILM. In caso contrario, potrebbe verificarsi un comportamento ILM inconsistente e imprevisto.
* Non applicare una correzione rapida o ripristinare un nodo della griglia.
+

NOTE: Contattare il supporto tecnico se è necessario ripristinare un nodo durante l'aggiornamento.

* Non dovresti gestire gruppi HA, interfacce VLAN o endpoint del bilanciatore del carico durante l'aggiornamento a StorageGRID 12.0.
* Non eliminare alcun gruppo HA finché non sarà completato l'aggiornamento a StorageGRID 12.0.  Gli indirizzi IP virtuali in altri gruppi HA potrebbero diventare inaccessibili.


Fino al completamento dell'attività *fasi finali dell'aggiornamento*:

* Non eseguire una procedura di espansione.
* Non eseguire una procedura di decommissionamento.

