---
permalink: upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html 
sidebar: sidebar 
keywords: upgrade, linux, rpm, deb, 
summary: 'Se un qualsiasi nodo StorageGRID viene distribuito su host Linux, installare un pacchetto RPM o DEB aggiuntivo su ciascuno di questi host prima di avviare l"aggiornamento.' 
---
= Linux: Scaricare e installare il pacchetto RPM o DEB su tutti gli host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se un qualsiasi nodo StorageGRID viene distribuito su host Linux, scaricare e installare un pacchetto RPM o DEB aggiuntivo su ciascuno di questi host prima di avviare l'aggiornamento.



== Scarica i file di aggiornamento, Linux e hotfix

Quando si esegue un aggiornamento StorageGRID da Grid Manager, viene richiesto di scaricare l'archivio di aggiornamento e le correzioni rapide necessarie come primo passaggio. Tuttavia, se è necessario scaricare i file per aggiornare gli host Linux, è possibile risparmiare tempo scaricando tutti i file richiesti in anticipo.

.Fasi
. Andare a https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Download NetApp: StorageGRID"^].
. Selezionare il pulsante per scaricare l'ultima versione oppure selezionare un'altra versione dal menu a discesa e selezionare *Go*.
+
Le versioni del software StorageGRID hanno questo formato: 11._x.y_. Le hotfix StorageGRID hanno questo formato: 11._x.a. .z_.

. Accedi con il nome utente e la password del tuo account NetApp.
. Se viene visualizzato un avviso di attenzione/MustRead, annotare il numero della correzione rapida e selezionare la casella di controllo.
. Leggere il Contratto di licenza con l'utente finale (EULA), selezionare la casella di controllo, quindi selezionare *Accetta e continua*.
+
Viene visualizzata la pagina dei download per la versione selezionata. La pagina contiene tre colonne.

. Dalla seconda colonna (*Upgrade StorageGRID*), scaricare due file:
+
** L'archivio di aggiornamento per l'ultima release (questo è il file nella sezione denominata *VMware, SG1000 o SG100 Primary Admin Node*). Sebbene questo file non sia necessario fino a quando non si esegue l'aggiornamento, il download di questo file consente di risparmiare tempo.
** Un archivio RPM o DEB in `.tgz` formato o. `.zip` Selezionare il `.zip` file se sul laptop di assistenza è in esecuzione Windows.
+
*** RHEL +
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip` +
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz`
*** Ubuntu o Debian + +
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip`
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz`




. Se è necessario accettare un avviso di attenzione/MustRead a causa di una correzione rapida richiesta, scaricare la correzione rapida:
+
.. Tornare a https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Download NetApp: StorageGRID"^].
.. Selezionare il numero della correzione rapida dall'elenco a discesa.
.. Accettare nuovamente l'avviso di attenzione e l'EULA.
.. Scaricare e salvare la correzione rapida e il relativo README.
+
Quando si avvia l'aggiornamento, viene richiesto di caricare il file hotfix nella pagina aggiornamento StorageGRID.



. La verifica della firma del codice è manuale su un nodo Linux.  Facoltativamente, verificare l'archivio di installazione:
+
.. Scaricare il pacchetto di verifica della firma del codice StorageGRID. Il nome del file per questo pacchetto utilizza il formato `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz`, dove `<version-number>` è la versione del software StorageGRID.
.. Segui i passaggi perlink:../swnodes/download-files-verify.html["verificare manualmente i file di installazione"] .






== Installare l'archivio su tutti gli host Linux

Eseguire questa procedura prima di aggiornare il software StorageGRID.

.Fasi
. Estrarre i pacchetti RPM o DEB dal file di installazione.
. Installare i pacchetti RPM o DEB su tutti gli host Linux.
+
Consultare i passaggi per l'installazione dei servizi host StorageGRID per Linux inlink:../swnodes/installing-storagegrid-webscale-host-services.html["Installare i servizi host StorageGRID"] .

+
I nuovi pacchetti vengono installati come pacchetti aggiuntivi.





== Rimuovere gli archivi di installazione per le versioni precedenti

Per liberare spazio sugli host Linux, è possibile rimuovere gli archivi di installazione delle versioni precedenti di StorageGRID che non sono più necessari.

.Fasi
. Rimuovere i vecchi archivi di installazione di StorageGRID.


[role="tabbed-block"]
====
.RHEL
--
. Catturare l'elenco dei pacchetti StorageGRID installati: `dnf list | grep -i storagegrid`.
+
Esempio:

+
[listing]
----
[root@rhel-example ~]# dnf list | grep -i storagegrid
StorageGRID-Webscale-Images-11-6-0.x86_64 11.6.0-20220210.0232.8d56cfe @System
StorageGRID-Webscale-Images-11-7-0.x86_64 11.7.0-20230424.2238.1a2cf8c @System
StorageGRID-Webscale-Images-11-8-0.x86_64 11.8.0-20240131.0139.e3e0c87 @System
StorageGRID-Webscale-Images-11-9-0.x86_64 11.9.0-20240826.1753.4aeeb70 @System
StorageGRID-Webscale-Service-11-6-0.x86_64 11.6.0-20220210.0232.8d56cfe @System
StorageGRID-Webscale-Service-11-7-0.x86_64 11.7.0-20230424.2238.1a2cf8c @System
StorageGRID-Webscale-Service-11-8-0.x86_64 11.8.0-20240131.0139.e3e0c87 @System
StorageGRID-Webscale-Service-11-9-0.x86_64 11.9.0-20240826.1753.4aeeb70 @System
[root@rhel-example ~]#
----
. Rimuovere i pacchetti StorageGRID precedenti: `dnf remove _images-package_ _service-package_`
+

CAUTION: Non rimuovere gli archivi di installazione per la versione di StorageGRID attualmente in esecuzione o per le versioni di StorageGRID a cui si intende eseguire l'aggiornamento.

+
È possibile ignorare in modo sicuro gli avvisi visualizzati. Si riferiscono ai file che sono stati sostituiti quando si installano pacchetti StorageGRID più recenti.

+
Esempio:

+
[listing]
----
[root@rhel-example ~]# dnf remove StorageGRID-Webscale-Images-11-6-0.x86_64 StorageGRID-Webscale-Service-11-6-0.x86_64
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Dependencies resolved.
============================================================================
Package            Architecture      Version           Repository  Size
============================================================================
Removing:
StorageGRID-Webscale-Images-11-6-0 x86_64 11.6.0-20220210.0232.8d56cfe @System 2.7 G
StorageGRID-Webscale-Service-11-6-0 x86_64 11.6.0-20220210.0232.8d56cfe @System 7.5 M

Transaction Summary
============================================================================
Remove 2 Packages

Freed space: 2.8 G
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing: 1/1
  Running scriptlet: StorageGRID-Webscale-Service-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64  1/2
  Erasing: StorageGRID-Webscale-Service-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64  1/2
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/ipv6.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/ipv4.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/eui64.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/eui48.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/__init__.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/sets.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/rfc1924.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/nmap.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/iana.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/glob.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/__init__.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/fbsocket.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/eui/ieee.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/eui/__init__.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/core.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/contrib/subnet_splitter.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/contrib/__init__.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/compat.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/__init__.pyc: remove failed: No such file or directory

  Erasing: StorageGRID-Webscale-Images-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64   2/2
  Verifying: StorageGRID-Webscale-Images-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64  1/2
  Verifying: StorageGRID-Webscale-Service-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64  2/2
Installed products updated.

Removed:
  StorageGRID-Webscale-Images-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64
  StorageGRID-Webscale-Service-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64

Complete!
[root@rhel-example ~]#
----


--
.Ubuntu e Debian
--
. Acquisire l'elenco dei pacchetti StorageGRID installati: `dpkg -l | grep storagegrid`
+
Esempio:

+
[listing]
----
root@debian-example:~# dpkg -l | grep storagegrid
ii  storagegrid-webscale-images-11-6-0  11.6.0-20220210.0232.8d56cfe amd64 StorageGRID Webscale docker images for 11.6.0
ii  storagegrid-webscale-images-11-7-0  11.7.0-20230424.2238.1a2cf8c.dev-signed amd64 StorageGRID Webscale docker images for 11.7.0
ii  storagegrid-webscale-images-11-8-0  11.8.0-20240131.0139.e3e0c87 amd64 StorageGRID Webscale docker images for 11.8.0
ii  storagegrid-webscale-images-11-9-0  11.9.0-20240826.1753.4aeeb70 amd64 StorageGRID Webscale docker images for 11.9.0
ii  storagegrid-webscale-service-11-6-0 11.6.0-20220210.0232.8d56cfe amd64 StorageGRID Webscale host services for 11.6.0
ii  storagegrid-webscale-service-11-7-0 11.7.0-20230424.2238.1a2cf8c amd64 StorageGRID Webscale host services for 11.7.0
ii  storagegrid-webscale-service-11-8-0 11.8.0-20240131.0139.e3e0c87 amd64 StorageGRID Webscale host services for 11.8.0
ii  storagegrid-webscale-service-11-9-0 11.9.0-20240826.1753.4aeeb70 amd64 StorageGRID Webscale host services for 11.9.0
root@debian-example:~#
----
. Rimuovere i pacchetti StorageGRID precedenti: `dpkg -r _images-package_ _service-package_`
+

CAUTION: Non rimuovere gli archivi di installazione per la versione di StorageGRID attualmente in esecuzione o per le versioni di StorageGRID a cui si intende eseguire l'aggiornamento.

+
Esempio:

+
[listing]
----
root@debian-example:~# dpkg -r storagegrid-webscale-service-11-6-0 storagegrid-webscale-images-11-6-0
(Reading database ... 38190 files and directories currently installed.)
Removing storagegrid-webscale-service-11-6-0 (11.6.0-20220210.0232.8d56cfe) ...
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
dpkg: warning: while removing storagegrid-webscale-service-11-6-0, directory '/usr/lib/python2.7/dist-packages/netapp/storagegrid/vendor/latest' not empty so not removed
Removing storagegrid-webscale-images-11-6-0 (11.6.0-20220210.0232.8d56cfe) ...
root@debian-example:~#
----


--
====
. Rimuovere le immagini del contenitore StorageGRID.


[role="tabbed-block"]
====
.Docker
--
. Acquisire l'elenco delle immagini contenitore installate: `docker images`
+
Esempio:

+
[listing]
----
[root@docker-example ~]# docker images
REPOSITORY           TAG            IMAGE ID       CREATED         SIZE
storagegrid-11.9.0   Admin_Node     610f2595bcb4   2 days ago      2.77GB
storagegrid-11.9.0   Storage_Node   7f73d33eb880   2 days ago      2.65GB
storagegrid-11.9.0   API_Gateway    2f0bb79526e9   2 days ago      1.82GB
storagegrid-11.8.0   Storage_Node   7125480de71b   7 months ago    2.54GB
storagegrid-11.8.0   Admin_Node     404e9f1bd173   7 months ago    2.63GB
storagegrid-11.8.0   Archive_Node   c3294a29697c   7 months ago    2.39GB
storagegrid-11.8.0   API_Gateway    1f88f24b9098   7 months ago    1.74GB
storagegrid-11.7.0   Storage_Node   1655350eff6f   16 months ago   2.51GB
storagegrid-11.7.0   Admin_Node     872258dd0dc8   16 months ago   2.48GB
storagegrid-11.7.0   Archive_Node   121e7c8b6d3b   16 months ago   2.41GB
storagegrid-11.7.0   API_Gateway    5b7a26e382de   16 months ago   1.77GB
storagegrid-11.6.0   Admin_Node     ee39f71a73e1   2 years ago     2.38GB
storagegrid-11.6.0   Storage_Node   f5ef895dcad0   2 years ago     2.08GB
storagegrid-11.6.0   Archive_Node   5782de552db0   2 years ago     1.95GB
storagegrid-11.6.0   API_Gateway    cb480ed37eea   2 years ago     1.35GB
[root@docker-example ~]#
----
. Rimuovere le immagini contenitore per le versioni precedenti di StorageGRID: `docker rmi _image id_`
+

CAUTION: Non rimuovere le immagini contenitore per la versione di StorageGRID attualmente in esecuzione o per le versioni di StorageGRID a cui si intende eseguire l'aggiornamento.

+
Esempio:

+
[listing]
----
[root@docker-example ~]# docker rmi cb480ed37eea
Untagged: storagegrid-11.6.0:API_Gateway
Deleted: sha256:cb480ed37eea0ae9cf3522de1dadfbff0075010d89c1c0a2337a3178051ddf02
Deleted: sha256:5f269aabf15c32c1fe6f36329c304b6c6ecb563d973794b9b59e8e5ab8cccafa
Deleted: sha256:47c2b2c295a77b312b8db69db58a02d8e09e929e121352bec713fa12dae66bde
[root@docker-example ~]#
----


--
.Podman
--
. Acquisire l'elenco delle immagini contenitore installate: `podman images`
+
Esempio:

+
[listing]
----
[root@podman-example ~]# podman images
REPOSITORY                    TAG           IMAGE ID      CREATED        SIZE
localhost/storagegrid-11.8.0  Storage_Node  7125480de71b  7 months ago   2.57 GB
localhost/storagegrid-11.8.0  Admin_Node    404e9f1bd173  7 months ago   2.67 GB
localhost/storagegrid-11.8.0  Archive_Node  c3294a29697c  7 months ago   2.42 GB
localhost/storagegrid-11.8.0  API_Gateway   1f88f24b9098  7 months ago   1.77 GB
localhost/storagegrid-11.7.0  Storage_Node  1655350eff6f  16 months ago  2.54 GB
localhost/storagegrid-11.7.0  Admin_Node    872258dd0dc8  16 months ago  2.51 GB
localhost/storagegrid-11.7.0  Archive_Node  121e7c8b6d3b  16 months ago  2.44 GB
localhost/storagegrid-11.7.0  API_Gateway   5b7a26e382de  16 months ago  1.8 GB
localhost/storagegrid-11.6.0  Admin_Node    ee39f71a73e1  2 years ago    2.42 GB
localhost/storagegrid-11.6.0  Storage_Node  f5ef895dcad0  2 years ago    2.11 GB
localhost/storagegrid-11.6.0  Archive_Node  5782de552db0  2 years ago    1.98 GB
localhost/storagegrid-11.6.0  API_Gateway   cb480ed37eea  2 years ago    1.38 GB
[root@podman-example ~]#
----
. Rimuovere le immagini contenitore per le versioni precedenti di StorageGRID: `podman rmi _image id_`
+

CAUTION: Non rimuovere le immagini contenitore per la versione di StorageGRID attualmente in esecuzione o per le versioni di StorageGRID a cui si intende eseguire l'aggiornamento.

+
Esempio:

+
[listing]
----
[root@podman-example ~]# podman rmi f5ef895dcad0
Untagged: localhost/storagegrid-11.6.0:Storage_Node
Deleted: f5ef895dcad0d78d0fd21a07dd132d7c7f65f45d80ee7205a4d615494e44cbb7
[root@podman-example ~]#
----


--
====