---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.0 
summary: Questa versione di StorageGRID introduce le seguenti funzionalità e modifiche funzionali. 
---
= Novità di StorageGRID 12.0
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questa versione di StorageGRID introduce le seguenti funzionalità e modifiche funzionali.



== Appliance

* La capacità di stoccaggio e l'efficienza dei costi sono aumentate in modo significativo.
* Gli aggiornamenti automatici del firmware dell'unità migliorano l'affidabilità del sistema e riducono i costi di manutenzione.




== Intelligenza artificiale (IA) e apprendimento automatico (ML)

* link:../tenant/what-is-branch-bucket.html["Secchi per rami"]consentono versioni point-in-time dei bucket che facilitano un ripristino più rapido del ransomware e set di dati isolati per test e sperimentazioni.
* Un livello di caching S3 migliora le prestazioni per la formazione AI/ML.




== Capacità

StorageGRID ora supporta mille miliardi di oggetti, ovvero più del doppio del limite precedente.  Fare riferimento al https://fusion.netapp.com/["Strumento NetApp Fusion"^] per dimensionare e progettare StorageGRID.



== Aggiornamenti su Cassandra

StorageGRID ora utilizza una versione più recente di Cassandra per l'archiviazione dei metadati.  Questa versione di Cassandra utilizza lo spazio su disco in modo più efficiente per archiviare più metadati.

Dopo di telink:../upgrade/index.html["aggiornamento da StorageGRID 11.9 a 12.0"] , un aggiornamento del formato dei metadati avverrà in background per uno o tre giorni.  Durante questo periodo, alcune procedure di manutenzione che implicano lo streaming di metadati, come l'espansione, saranno disabilitate.

Fare riferimento a link:../upgrade/performing-upgrade.html#upgrade-other-nodes["Aggiornare altri nodi"] .



== Federazione

* Ora puoilink:../admin/managing-users.html#import-federated-users["importa fino a 100 utenti federati"] in StorageGRID.
* Ora puoilink:../ilm/configuring-regions-optional-and-s3-only.html["modificare la regione predefinita"] per i bucket S3.  Questa funzionalità garantisce una maggiore flessibilità nella gestione delle impostazioni locali e della conformità dei dati.
* Ora è possibile configurare la replica tra griglie tra bucket con S3 Object Lock abilitato. Fare riferimento a link:../admin/grid-federation-what-is-cross-grid-replication.html#cgr-with-ol["Replicazione cross-grid con S3 Object Lock"] .
+
NetApp consiglia di utilizzare questa funzionalità solo tra i bucket di origine e di destinazione StorageGRID 12.0.  Tuttavia, questa funzionalità è supportata tra i bucket di origine StorageGRID 11.9 con S3 Object Lock disabilitato e i bucket di destinazione StorageGRID 12.0 con S3 Object Lock abilitato.





== Gestibilità

* Miglioratolink:../maintain/decommission-procedure.html["procedura di dismissione"] riduce i tempi e la complessità per migliorare l'efficienza operativa.
* Il comportamento migliorato per una coerenza globale forte fornisce tolleranza agli errori del sito per le richieste dei client quando le griglie hanno tre o più siti.
+
** Le nuove installazioni di StorageGRID 12.0 e successive utilizzeranno per impostazione predefinita la semantica Quorum quandolink:../s3/consistency.html["coerenza globale forte"] è impostato.
** Se si esegue l'aggiornamento da StorageGRID 11.9 a StorageGRID 12.0, le griglie aggiornate manterranno il comportamento precedente per garantire una coerenza globale elevata.





NOTE: Se è necessario ripristinare il comportamento precedente per una coerenza globale forte, fare riferimento a https://kb.netapp.com/hybrid/StorageGRID/Object_Mgmt/Configuring_StorageGRID_quorum_semantics_for_strong-global_consistency["Configurazione della semantica del quorum StorageGRID per una coerenza globale forte"^] per istruzioni.

* La possibilità di avviare caricamenti di log sulink:../admin/configure-autosupport-grid-manager.html["AutoSupport"] aiuta a migliorare la reattività del supporto.
* Ridotto https://docs.netapp.com/us-en/storagegrid-appliances/index.html["apparecchio"^] il tempo di riavvio riduce al minimo i tempi di inattività per migliorare la disponibilità complessiva del sistema.
* link:../maintain/move-adc-service.html["La possibilità di spostare il servizio ADC"]a un altro nodo di archiviazione aumenta la flessibilità e la resilienza nella gestione dei nodi di archiviazione che ospitano il servizio ADC.  È possibile spostare il servizio ADC prima di dismettere un nodo di archiviazione o di convertire un nodo di archiviazione in un nodo solo dati.
* Per massimizzare la capacità di archiviazione dei dati, è possibilelink:../maintain/convert-to-data-only-node.html["convertire un nodo di archiviazione in un nodo solo dati"] , che determina la migrazione dei metadati su quel nodo verso nodi di archiviazione combinati o solo metadati.
* La capacità di qualsiasi nodo di amministrazione dilink:../maintain/selecting-node-recovery-procedure.html["recuperare qualsiasi altro nodo"] (ad eccezione del nodo di amministrazione primario) migliora il ripristino del sistema e la tolleranza agli errori, migliorando l'affidabilità complessiva.
* Gli utenti possono ora utilizzare un bucket S3 perlink:../monitor/configure-log-management.html#use-a-bucket["conservare i registri di controllo per un lungo periodo di tempo"] .




== Sicurezza

* Una crittografia dei dati più efficace e una protezione dell'integrità più efficace garantiscono maggiore sicurezza e prestazioni migliori.
* Una maggiore sicurezza delle password memorizzate riduce il rischio di accessi non autorizzati.
* link:../admin/manage-external-ssh-access.html["SSH è bloccato per impostazione predefinita"]per aumentare la sicurezza consentendo al contempo un accesso controllato.




== gruppi di inquilini

* Ora puoilink:../tenant/manage-groups.html["configurare una nuova policy di trust S3"] per supportare l'API AssumeRole.  La funzione AssumeRole fornisce credenziali a breve termine per una maggiore sicurezza e un controllo flessibile degli accessi.
* La quota di conteggio degli oggetti per bucket consente un migliore controllo e una migliore gestione delle risorse di archiviazione.




== Interfaccia utente

* Le impostazioni del tema scuro e del tema di sistema sono disponibili nel menu Utente di Grid Manager e Tenant Manager.
* La pagina del server Audit e syslog, rinominatalink:../monitor/configure-log-management.html["Gestione dei log"] , è stato rifattorizzato con aggiunte per l'archiviazione dei log in un bucket di sistema a scopo di backup.
* La pagina legacy Topologia griglia è stata rimossa.  Nelle ultime versioni StorageGRID , le operazioni e le metriche disponibili da quella pagina sono state migrate ad altre pagine di Grid Manager, in particolare alink:../monitor/viewing-nodes-page.html["Pagina nodi"] .

