---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.0 
summary: Questa versione di StorageGRID introduce le seguenti funzionalità e modifiche funzionali. 
---
= Novità di StorageGRID 12,0
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questa versione di StorageGRID introduce le seguenti funzionalità e modifiche funzionali.



== Replica cross-grid con blocco degli oggetti S3

È possibile configurare la replica cross-grid tra bucket con blocco oggetti S3 abilitato. Fare riferimento alla link:../admin/grid-federation-what-is-cross-grid-replication.html#cgr-with-ol["Replica cross-grid con blocco degli oggetti S3"].

NetApp consiglia di utilizzare questa funzione solo tra bucket di origine e destinazione StorageGRID 12,0. Tuttavia, questa funzione è supportata tra i bucket di origine StorageGRID 11,9 con blocco oggetto S3 disattivato e i bucket di destinazione StorageGRID 12,0 con blocco oggetto S3 attivato.



== Sicurezza



=== Miglioramento della sicurezza per le password crittografate su disco

Sicurezza delle password migliorata, incluso un numero di hash migliorato per hash di SHA512 password.



== S3 bucket



=== Benne per filiali

Ora è possibile link:../tenant/manage-branch-bucket-html["creare bucket di filiali"]per un bucket S3. Un bucket di diramazione fornisce l'accesso a S3 oggetti bucket come esistevano in un determinato momento. Un bucket di filiale non è lo stesso di un backup.



== Interfaccia utente



=== Tema scuro

Le impostazioni del tema scuro e del tema di sistema sono disponibili nel menu utente di Grid Manager e Tenant Manager.



== Miglioramenti a Grid Manager



=== Configurare il miglioramento delle regioni

La pagina regioni in Grid Manager ora include una scheda *Area predefinita*. È possibile utilizzare questa scheda per modificare l'area predefinita definita per i bucket S3. link:../ilm/configuring-regions-optional-and-s3-only.html["Scopri di più"].
