---
permalink: ubuntu/automating-installation.html 
sidebar: sidebar 
keywords: how to automate ubuntu or debian installation 
summary: 'È possibile automatizzare l"installazione del servizio host StorageGRID e la configurazione dei nodi di rete.' 
---
= Automatizzare l'installazione (Ubuntu o Debian)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile automatizzare l'installazione del servizio host StorageGRID e la configurazione dei nodi di rete.

.A proposito di questa attività
L'automazione della distribuzione può essere utile in uno dei seguenti casi:

* Si utilizza già un framework di orchestrazione standard, ad esempio Ansible, Puppet o Chef, per implementare e configurare host fisici o virtuali.
* Si intende implementare più istanze di StorageGRID.
* Si sta implementando un'istanza di StorageGRID grande e complessa.


Il servizio host di StorageGRID viene installato da un pacchetto e gestito da file di configurazione che possono essere creati in modo interattivo durante un'installazione manuale o preparati in anticipo (o a livello di programmazione) per consentire l'installazione automatica utilizzando framework di orchestrazione standard. StorageGRID fornisce script Python opzionali per automatizzare la configurazione delle appliance StorageGRID e dell'intero sistema StorageGRID (il "grid"). È possibile utilizzare questi script direttamente o ispezionarli per scoprire come utilizzare l'API REST per l'installazione di StorageGRID nei tool di configurazione e distribuzione grid sviluppati da soli.



== Automatizzare l'installazione e la configurazione del servizio host StorageGRID

È possibile automatizzare l'installazione del servizio host StorageGRID utilizzando framework di orchestrazione standard come Ansible, Puppet, Chef, Fabric o SaltStack.

Il servizio host di StorageGRID è confezionato in un DEB ed è gestito da file di configurazione che possono essere preparati in anticipo (o a livello di programmazione) per consentire l'installazione automatica. Se si utilizza già un framework di orchestrazione standard per installare e configurare Ubuntu o Debian, aggiungere StorageGRID ai propri playbook o alle proprie ricette dovrebbe essere semplice.

È possibile automatizzare queste attività:

. Installazione di Linux
. Configurazione di Linux
. Configurazione delle interfacce di rete host per soddisfare i requisiti StorageGRID
. Configurazione dello storage host per soddisfare i requisiti StorageGRID
. Installazione di Docker
. Installazione del servizio host StorageGRID
. Creazione dei file di configurazione del nodo StorageGRID in `/etc/storagegrid/nodes`
. Convalida dei file di configurazione del nodo StorageGRID
. Avvio del servizio host StorageGRID




=== Esempio di Ansible role and playbook

Esempio di ruolo e playbook Ansible vengono forniti con l'archivio di installazione nella `/extras` cartella. Il manuale Ansible mostra come il `storagegrid` ruolo prepara gli host e installa StorageGRID sui server di destinazione. È possibile personalizzare il ruolo o il manuale in base alle esigenze.



== Automatizzare la configurazione di StorageGRID

Una volta implementati i nodi grid, è possibile automatizzare la configurazione del sistema StorageGRID.

.Prima di iniziare
* Si conosce la posizione dei seguenti file dall'archivio di installazione.
+
[cols="1a,1a"]
|===
| Nome file | Descrizione 


| configure-storagegrid.py  a| 
Script Python utilizzato per automatizzare la configurazione



| configure-storagegrid.sample.json  a| 
File di configurazione di esempio da utilizzare con lo script



| configure-storagegrid.blank.json  a| 
File di configurazione vuoto da utilizzare con lo script

|===
* È stato creato un `configure-storagegrid.json` file di configurazione. Per creare questo file, è possibile modificare il file di configurazione di esempio (`configure-storagegrid.sample.json`) o il file di configurazione vuoto (`configure-storagegrid.blank.json`).



CAUTION: Memorizzare la password di gestione e la passphrase di provisioning dalla sezione Password del file di configurazione modificato `configure-storagegrid.json` in un percorso sicuro. Queste password sono necessarie per le procedure di installazione, espansione e manutenzione. È inoltre necessario eseguire il backup del file di configurazione modificato `configure-storagegrid.json` e memorizzarlo in una posizione sicura.

.A proposito di questa attività
È possibile utilizzare `configure-storagegrid.py` lo script Python e il `configure-storagegrid.json` file di configurazione per automatizzare la configurazione del sistema StorageGRID.


NOTE: È inoltre possibile configurare il sistema utilizzando Grid Manager o l'API di installazione.

.Fasi
. Accedere alla macchina Linux in uso per eseguire lo script Python.
. Passare alla directory in cui è stato estratto l'archivio di installazione.
+
Ad esempio:

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
dove `platform` è `debs`, `rpms` o `vsphere`.

. Eseguire lo script Python e utilizzare il file di configurazione creato.
+
Ad esempio:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Risultato
Durante il processo di configurazione viene generato un file del pacchetto di ripristino `.zip` che viene scaricato nella directory in cui viene eseguito il processo di installazione e configurazione. È necessario eseguire il backup del file del pacchetto di ripristino in modo da poter ripristinare il sistema StorageGRID in caso di errore di uno o più nodi della griglia. Ad esempio, copiarla in una posizione di rete sicura e di backup e in una posizione di cloud storage sicura.


CAUTION: Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID.

Se è stata specificata la generazione di password casuali, aprire il `Passwords.txt` file e cercare le password necessarie per accedere al sistema StorageGRID.

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
Il sistema StorageGRID viene installato e configurato quando viene visualizzato un messaggio di conferma.

[listing]
----
StorageGRID has been configured and installed.
----
.Informazioni correlate
link:overview-of-installation-rest-api.html["API REST di installazione"]
