---
permalink: ubuntu/configuring-host-storage.html 
sidebar: sidebar 
keywords: how to configure host storage 
summary: È necessario allocare volumi di storage a blocchi a ciascun host. 
---
= Configurare lo storage host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario allocare volumi di storage a blocchi a ciascun host.

.Prima di iniziare
Sono stati esaminati i seguenti argomenti, che forniscono le informazioni necessarie per eseguire questa attività:

* link:storage-and-performance-requirements.html["Requisiti di storage e performance"]
* link:node-container-migration-requirements.html["Requisiti per la migrazione dei container di nodi"]


.A proposito di questa attività
Quando si allocano i volumi di storage a blocchi (LUN) agli host, utilizzare le tabelle in "requisiti di archiviazione" per determinare quanto segue:

* Numero di volumi richiesti per ciascun host (in base al numero e ai tipi di nodi che verranno implementati su tale host)
* Categoria di storage per ciascun volume (ovvero dati di sistema o dati oggetto)
* Dimensione di ciascun volume


Quando si distribuiscono i nodi StorageGRID sull'host, verranno utilizzate queste informazioni e il nome persistente assegnato da Linux a ciascun volume fisico.


NOTE: Non è necessario partizionare, formattare o montare nessuno di questi volumi; è sufficiente assicurarsi che siano visibili agli host.


NOTE: È necessaria una sola LUN per i dati degli oggetti per i nodi di storage basati solo sui metadati.

Evitare di utilizzare file speciali "RAW"(`/dev/sdb`, ad esempio) quando si compone l'elenco dei nomi dei volumi. Questi file possono cambiare durante i riavvii dell'host, il che avrà un impatto sul corretto funzionamento del sistema. Se si utilizzano LUN iSCSI e Device Mapper Multipathing, considerare l'utilizzo di alias multipath nella `/dev/mapper` directory, soprattutto se la topologia SAN include percorsi di rete ridondanti verso lo storage condiviso. In alternativa, è possibile utilizzare i collegamenti software creati dal sistema in `/dev/disk/by-path/` per i nomi dei dispositivi permanenti.

Ad esempio:

[listing]
----
ls -l
$ ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:00:07.1-ata-2 -> ../../sr0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
----
I risultati saranno diversi per ogni installazione.

Assegnare nomi descrittivi a ciascuno di questi volumi di storage a blocchi per semplificare l'installazione iniziale di StorageGRID e le future procedure di manutenzione. Se si utilizza il driver multipercorso device mapper per l'accesso ridondante ai volumi di storage condiviso, è possibile utilizzare il `alias` campo nel `/etc/multipath.conf` file.

Ad esempio:

[listing]
----
multipaths {
     multipath {
          wwid 3600a09800059d6df00005df2573c2c30
          alias docker-storage-volume-hostA
     }
     multipath {
          wwid 3600a09800059d6df00005df3573c2c30
          alias sgws-adm1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df4573c2c30
          alias sgws-adm1-audit-logs
     }
     multipath {
          wwid 3600a09800059d6df00005df5573c2c30
          alias sgws-adm1-tables
     }
     multipath {
          wwid 3600a09800059d6df00005df6573c2c30
          alias sgws-gw1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-rangedb-0
     }
     …
----
Utilizzando il campo alias in questo modo, gli alias vengono visualizzati come dispositivi di blocco nella `/dev/mapper` directory dell'host, consentendo di specificare un nome facile e facilmente validato ogni volta che un'operazione di configurazione o manutenzione richiede di specificare un volume di archiviazione del blocco.

Se si imposta lo storage condiviso per supportare la migrazione dei nodi StorageGRID e si utilizza il multipathing di Device Mapper, è possibile creare e installare un comune `/etc/multipath.conf` su tutti gli host in co-location. Assicurati di utilizzare un volume di storage Docker diverso su ciascun host. L'utilizzo di alias e l'inclusione del nome host di destinazione nell'alias per ogni LUN del volume di storage Docker renderà questa operazione facile da ricordare ed è consigliabile.


NOTE: Il supporto di Docker come motore container per implementazioni solo software è obsoleto. In una release futura, Docker sostituirà un altro motore per container.

.Informazioni correlate
* link:storage-and-performance-requirements.html["Requisiti di storage e performance"]
* link:node-container-migration-requirements.html["Requisiti per la migrazione dei container di nodi"]

