---
permalink: ubuntu/example-node-configuration-files.html 
sidebar: sidebar 
keywords: example node configuration files 
summary: È possibile utilizzare i file di configurazione dei nodi di esempio per configurare i file di configurazione dei nodi per il sistema StorageGRID. Gli esempi mostrano i file di configurazione dei nodi per tutti i tipi di nodi griglia. 
---
= File di configurazione del nodo di esempio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare i file di configurazione dei nodi di esempio per configurare i file di configurazione dei nodi per il sistema StorageGRID. Gli esempi mostrano i file di configurazione dei nodi per tutti i tipi di nodi griglia.

Per la maggior parte dei nodi, è possibile aggiungere le informazioni di indirizzamento di Admin e Client Network (IP, mask, gateway e così via) quando si configura la griglia utilizzando Grid Manager o l'API di installazione. L'eccezione è il nodo di amministrazione principale. Se si desidera accedere all'indirizzo IP Admin Network del nodo di amministrazione principale per completare la configurazione della griglia (ad esempio perché la rete di griglia non viene instradata), è necessario configurare la connessione Admin Network per il nodo di amministrazione primario nel relativo file di configurazione del nodo. Questo è illustrato nell'esempio.


NOTE: Negli esempi, la destinazione di rete client è stata configurata come Best practice, anche se la rete client è disattivata per impostazione predefinita.



== Esempio per nodo amministratore primario

*Nome file di esempio*: `/etc/storagegrid/nodes/dc1-adm1.conf`

*Esempio di contenuto del file:*

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Primary
TEMPORARY_PASSWORD_TYPE = Use custom password
CUSTOM_TEMPORARY_PASSWORD = Passw0rd
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-adm1-var-local
BLOCK_DEVICE_AUDIT_LOGS = /dev/mapper/dc1-adm1-audit-logs
BLOCK_DEVICE_TABLES = /dev/mapper/dc1-adm1-tables
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.2
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1

ADMIN_NETWORK_CONFIG = STATIC
ADMIN_NETWORK_IP = 192.168.100.2
ADMIN_NETWORK_MASK = 255.255.248.0
ADMIN_NETWORK_GATEWAY = 192.168.100.1
ADMIN_NETWORK_ESL = 192.168.100.0/21,172.16.0.0/21,172.17.0.0/21
----


== Esempio per nodo di storage

*Nome file di esempio:* `/etc/storagegrid/nodes/dc1-sn1.conf`

*Esempio di contenuto del file:*

[listing]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-sn1-var-local
BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/dc1-sn1-rangedb-0
BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/dc1-sn1-rangedb-1
BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/dc1-sn1-rangedb-2
BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/dc1-sn1-rangedb-3
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----


== Esempio per Gateway Node

*Nome file di esempio:* `/etc/storagegrid/nodes/dc1-gw1.conf`

*Esempio di contenuto del file:*

[listing]
----
NODE_TYPE = VM_API_Gateway
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-gw1-var-local
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.5
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----


== Esempio di nodo amministrativo non primario

*Nome file di esempio:* `/etc/storagegrid/nodes/dc1-adm2.conf`

*Esempio di contenuto del file:*

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Non-Primary
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-adm2-var-local
BLOCK_DEVICE_AUDIT_LOGS = /dev/mapper/dc1-adm2-audit-logs
BLOCK_DEVICE_TABLES = /dev/mapper/dc1-adm2-tables
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.6
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----