---
permalink: ubuntu/installing-linux.html 
sidebar: sidebar 
keywords: how to install Linux 
summary: È necessario installare StorageGRID su tutti i grid host Ubuntu o Debian. Per un elenco delle versioni supportate, utilizza lo strumento matrice di interoperabilità NetApp. 
---
= Installare Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario installare StorageGRID su tutti i grid host Ubuntu o Debian. Per un elenco delle versioni supportate, utilizza lo strumento matrice di interoperabilità NetApp.

.Prima di iniziare
Verificare che il sistema operativo soddisfi i requisiti minimi di versione del kernel di StorageGRID, come indicato di seguito. Utilizzare il comando `uname -r` per ottenere la versione del kernel del sistema operativo o consultare il fornitore del sistema operativo.

*Nota:* il supporto per Ubuntu versione 18,04 e 20,04 è stato obsoleto e verrà rimosso in una versione futura.

[cols="1a,2a,3a"]
|===
| Versione Ubuntu | Versione minima del kernel | Nome del pacchetto kernel 


 a| 
18.04.6 (obsoleto)
 a| 
5,4.0-150-generico
 a| 
linux-image-5,4.0-150-generic/bionic-updates,bionic-security,now 5,4.0-150,167~18.04.1



 a| 
20.04.5 (obsoleto)
 a| 
5,4.0-131-generico
 a| 
linux-image-5,4.0-131-generic/focal-updates,now 5,4.0-131,147



 a| 
22.04.1
 a| 
5.15.0-47-generico
 a| 
linux-image-5.15.0-47-generic/jammy-updates,jammy-security,now 5.15.0-47,51



 a| 
24,04
 a| 
6,8.0-31-generico
 a| 
linux-image-6,8.0-31-generic/noble,now 6,8.0-31,31

|===
*Nota:* il supporto per Debian versione 11 è stato deprecato e sarà rimosso in una versione futura.

[cols="1a,2a,2a"]
|===
| Versione Debian | Versione minima del kernel | Nome del pacchetto kernel 


 a| 
11 (obsoleto)
 a| 
5.10.0-18-amd64
 a| 
linux-image-5.10.0-18-amd64/stable,ora 5.10.150-1



 a| 
12
 a| 
6,1.0-9-amd64
 a| 
linux-image-6,1.0-9-amd64/stable,now 6,1.27-1

|===
.Fasi
. Installare Linux su tutti gli host grid fisici o virtuali in base alle istruzioni del distributore o alla procedura standard.
+

NOTE: Non installare ambienti desktop grafici. Quando si installa Ubuntu, è necessario selezionare *utility di sistema standard*. Si consiglia di selezionare *OpenSSH server* per abilitare l'accesso ssh agli host Ubuntu. Tutte le altre opzioni possono rimanere deselezionate.

. Assicurarsi che tutti gli host abbiano accesso ai repository dei pacchetti di Ubuntu o Debian.
. Se lo swap è attivato:
+
.. Eseguire il seguente comando: `$ sudo swapoff --all`
.. Rimuovere tutte le voci di swap da `/etc/fstab` per mantenere le impostazioni.
+

NOTE: La mancata disattivazione completa dello swap può ridurre notevolmente le performance.




