---
permalink: ubuntu/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot ubuntu or debian installation 
summary: 'Se si verificano problemi durante l"installazione del sistema StorageGRID, è possibile accedere ai file di log dell"installazione. Per risolvere i problemi, potrebbe essere necessario utilizzare anche i file di log dell"installazione.' 
---
= Risolvere i problemi di installazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si verificano problemi durante l'installazione del sistema StorageGRID, è possibile accedere ai file di log dell'installazione. Per risolvere i problemi, potrebbe essere necessario utilizzare anche i file di log dell'installazione.

I seguenti file di log per l'installazione sono disponibili dal container che esegue ciascun nodo:

* `/var/local/log/install.log` (trovato su tutti i nodi griglia)
* `/var/local/log/gdu-server.log` (Trovato sul nodo amministrativo primario)


I seguenti file di log per l'installazione sono disponibili dall'host:

* `/var/log/storagegrid/daemon.log`
* `/var/log/storagegrid/nodes/<node-name>.log`


Per informazioni su come accedere ai file di registro, vedere link:../monitor/collecting-log-files-and-system-data.html["Raccogliere i file di log e i dati di sistema"].

.Informazioni correlate
link:../troubleshoot/index.html["Risolvere i problemi di un sistema StorageGRID"]
