= 
:allow-uri-read: 


[role="tabbed-block"]
====
.Dati replicati
--
* Per ottenere un completamento percentuale stimato per la riparazione replicata, aggiungere `show-replicated-repair-status` l'opzione al comando Repair-data.
+
`repair-data show-replicated-repair-status`

* Per determinare se le riparazioni sono state completate:
+
.. Selezionare *NODI* > *_nodo di storage in riparazione_* > *ILM*.
.. Esaminare gli attributi nella sezione Valutazione. Al termine delle riparazioni, l'attributo *in attesa - tutto* indica 0 oggetti.


* Per monitorare la riparazione in modo più dettagliato:
+
.. Selezionare *NODI*.
.. Selezionare *_grid name_* > *ILM*.
.. Posizionare il cursore sul grafico della coda ILM per visualizzare il valore dell'attributo *velocità di scansione (oggetti/sec)*, ovvero la velocità con cui gli oggetti nella griglia vengono sottoposti a scansione e accodati per ILM.
.. Nella sezione coda ILM, osservare i seguenti attributi:
+
*** *Periodo di scansione - stimato*: Il tempo stimato per completare una scansione ILM completa di tutti gli oggetti.
+
Una scansione completa non garantisce che ILM sia stato applicato a tutti gli oggetti.

*** *Riparazioni tentate*: Il numero totale di operazioni di riparazione degli oggetti per i dati replicati che sono stati tentati. Questo numero aumenta ogni volta che un nodo di storage tenta di riparare un oggetto ad alto rischio. Le riparazioni ILM ad alto rischio hanno la priorità se la rete diventa occupata.
+
La stessa riparazione dell'oggetto potrebbe aumentare di nuovo se la replica non è riuscita dopo la riparazione. + questi attributi possono essere utili quando si monitora l'avanzamento del ripristino del volume del nodo di archiviazione. Se il numero di riparazioni tentate ha smesso di aumentare ed è stata completata una scansione completa, la riparazione probabilmente è stata completata.



.. In alternativa, inviare una richiesta Prometheus per `storagegrid_ilm_scan_period_estimated_minutes` e `storagegrid_ilm_repairs_attempted`.




--
.Dati con erasure coding (EC)
--
Per monitorare la riparazione dei dati con codifica erasure e riprovare eventuali richieste che potrebbero non essere riuscite:

. Determinare lo stato delle riparazioni dei dati con codice di cancellazione:
+
** Selezionare *SUPPORTO* > *Strumenti* > *metriche* per visualizzare il tempo stimato per il completamento e la percentuale di completamento per il lavoro corrente. Quindi, selezionare *EC Overview* (Panoramica EC) nella sezione Grafana. Esaminare le dashboard *Grid EC Job Estimated Time to Completion* (tempo stimato per il completamento della commessa EC) e *Grid EC Job Percentage Completed* (percentuale lavoro EC completata).
** Utilizzare questo comando per visualizzare lo stato di un'operazione specifica `repair-data`:
+
`repair-data show-ec-repair-status --repair-id repair ID`

** Utilizzare questo comando per elencare tutte le riparazioni:
+
`repair-data show-ec-repair-status`

+
L'output elenca le informazioni, tra cui `repair ID`, per tutte le riparazioni in esecuzione in precedenza e in corso.



. Se l'output mostra che l'operazione di riparazione non è riuscita, utilizzare `--repair-id` l'opzione per riprovare la riparazione.
+
Questo comando prova di nuovo una riparazione del nodo non riuscita, utilizzando l'ID riparazione 6949309319275667690:

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
Questo comando prova di nuovo una riparazione del volume non riuscita, utilizzando l'ID riparazione 6949309319275667690:

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====