---
permalink: tenant/deleting-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to delete access key for other user 
summary: 'Se si utilizza un tenant S3 e si dispone delle autorizzazioni appropriate, è possibile eliminare le chiavi di accesso S3 di un altro utente. Una volta eliminata, una chiave di accesso non può più essere utilizzata per accedere agli oggetti e ai bucket dell"account tenant.' 
---
= Eliminare le chiavi di accesso S3 di un altro utente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizza un tenant S3 e si dispone delle autorizzazioni appropriate, è possibile eliminare le chiavi di accesso S3 di un altro utente. Una volta eliminata, una chiave di accesso non può più essere utilizzata per accedere agli oggetti e ai bucket dell'account tenant.

.Prima di iniziare
* L'utente ha effettuato l'accesso al responsabile del tenant utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone di link:tenant-management-permissions.html["Autorizzazione di accesso root"].



CAUTION: È possibile accedere ai bucket S3 e agli oggetti appartenenti a un utente utilizzando l'ID della chiave di accesso e la chiave di accesso segreta visualizzati per tale utente in Tenant Manager. Per questo motivo, proteggere le chiavi di accesso come se si trattasse di una password. Ruotare regolarmente le chiavi di accesso, rimuovere eventuali chiavi inutilizzate dall'account e non condividerle mai con altri utenti.

.Fasi
. Selezionare *ACCESS MANAGEMENT* > *Users*.
. Nella pagina utenti, selezionare l'utente di cui si desidera gestire le chiavi di accesso S3.
. Nella pagina User details (Dettagli utente), selezionare *Access keys* (chiavi di accesso), quindi selezionare la casella di controllo per ogni chiave di accesso che si desidera eliminare.
. Selezionare *azioni* > *Elimina tasto selezionato*.
. Nella finestra di dialogo di conferma, selezionare *Elimina tasto*.
+
Viene visualizzato un messaggio di conferma nell'angolo superiore destro della pagina.


