---
permalink: tenant/enable-cross-origin-resource-sharing-for-management-interface.html 
sidebar: sidebar 
keywords: how to configure cross-origin resource sharing, cors, management, api, domain 
summary: 'È possibile abilitare la condivisione delle risorse tra origini (CORS) per le richieste API di gestione a StorageGRID, se si desidera che i dati in StorageGRID siano accessibili tramite API di gestione in un altro dominio.' 
---
= Attivare StorageGRID CORS per un'interfaccia di gestione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile abilitare la condivisione delle risorse tra origini (CORS) per le richieste API di gestione a StorageGRID, se si desidera che i dati in StorageGRID siano accessibili tramite API di gestione in un altro dominio.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* link:tenant-management-permissions.html["Autorizzazione di accesso root"]Fornisce l'accesso a tutte le richieste di configurazione CORS.


.A proposito di questa attività
CORS è un meccanismo di protezione che consente alle applicazioni Web client in un dominio di accedere alle risorse in un dominio diverso. Ad esempio, si supponga di voler creare un dashboard di monitoraggio per StorageGRID nel dominio `\http://www.example.com`. Abilitando CORS in StorageGRID per `\http://www.example.com` e "Gestione griglia", il dominio StorageGRID risponde alle richieste API di gestione griglia da `\http://www.example.com`.

Le richieste API di gestione (Mgmt-api) con `application/json` o `multipart/formdata` richieste di `Content-Type` sono supportate per CORS.

.Fasi
. In *rete* nella pagina Configurazione StorageGRID, selezionare *Impostazioni CORS interfaccia di gestione*.
. Selezionare *Grid Manager*, *Tenant Manager* o entrambe le opzioni.
+
** *Grid Manager*: Abilita CORS per le richieste API di Grid Management tra domini.
** *Tenant Manager*: Abilita CORS per le richieste API di gestione dei tenant a più domini.


. Immettere l'URL dell'altro dominio nel campo *Domini*.
+
Selezionare *Aggiungi un altro dominio* se si desidera attivare CORS in StorageGRID per più di un dominio.

. Selezionare *Salva*.


.Informazioni correlate
link:configuring-cross-origin-resource-sharing-for-buckets-and-objects.html["Configurare StorageGRID CORS per bucket e oggetti"]
