---
permalink: tenant/update-default-retention-settings.html 
sidebar: sidebar 
keywords: update default retention for s3 object lock bucket, default retention mode, default retention period, compliance, governance 
summary: 'Se al momento della creazione del bucket è stato attivato il blocco oggetti S3, è possibile modificare il bucket per modificare le impostazioni di conservazione predefinite. È possibile attivare (o disattivare) la conservazione predefinita e impostare una modalità di conservazione e un periodo di conservazione predefiniti.' 
---
= Aggiorna la conservazione predefinita del blocco oggetti S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se al momento della creazione del bucket è stato attivato il blocco oggetti S3, è possibile modificare il bucket per modificare le impostazioni di conservazione predefinite. È possibile attivare (o disattivare) la conservazione predefinita e impostare una modalità di conservazione e un periodo di conservazione predefiniti.

.Prima di iniziare
* L'utente ha effettuato l'accesso al responsabile del tenant utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* L'utente appartiene a un gruppo di utenti che dispone di link:tenant-management-permissions.html["Gestire tutti i bucket o le autorizzazioni di accesso root"]. Queste autorizzazioni sovrascrivono le impostazioni delle autorizzazioni nelle policy di gruppo o bucket.
* Il blocco oggetti S3 è attivato globalmente per il sistema StorageGRID e il blocco oggetti S3 è stato attivato quando è stato creato il bucket. Vedere link:using-s3-object-lock.html["USA il blocco oggetti S3 per conservare gli oggetti"].


.Fasi
. Selezionare *View bucket* (Visualizza bucket) dalla dashboard oppure selezionare *STORAGE (S3)* > *Bucket*.
. Selezionare il nome del bucket dalla tabella.
+
Viene visualizzata la pagina dei dettagli del bucket.

. Dalla scheda *Opzioni bucket*, selezionare la fisarmonica *S3 Object Lock*.
. Facoltativamente, attivare o disattivare *Default Retention* per questo bucket.
+
Le modifiche apportate a questa impostazione non si applicano agli oggetti già presenti nel bucket o a qualsiasi oggetto che potrebbe avere periodi di conservazione propri.

. Se l'opzione *Default Retention* (conservazione predefinita) è attivata, specificare una *modalità di conservazione predefinita* per il bucket.
+
[cols="1a,2a"]
|===
| Modalità di conservazione predefinita | Descrizione 


 a| 
Governance
 a| 
** Gli utenti con `s3:BypassGovernanceRetention` autorizzazione possono utilizzare l' `x-amz-bypass-governance-retention: true`intestazione della richiesta per ignorare le impostazioni di conservazione.
** Questi utenti possono eliminare una versione dell'oggetto prima che venga raggiunta la data di conservazione.
** Questi utenti possono aumentare, ridurre o rimuovere il mantenimento di un oggetto fino ad oggi.




 a| 
Conformità
 a| 
** L'oggetto non può essere eliminato fino a quando non viene raggiunta la data di conservazione.
** La conservazione dell'oggetto fino alla data odierna può essere aumentata, ma non può essere diminuita.
** La data di conservazione dell'oggetto non può essere rimossa fino al raggiungimento di tale data.


*Nota*: L'amministratore della griglia deve consentire l'utilizzo della modalità di conformità.

|===
. Se l'opzione *Default Retention* (conservazione predefinita) è attivata, specificare il *Default Retention Period* (periodo di conservazione predefinito) per il bucket.
+
Il *Default Retention Period* indica per quanto tempo i nuovi oggetti aggiunti a questo bucket devono essere conservati, a partire dal momento in cui vengono acquisiti. Specificare un valore inferiore o uguale al periodo di conservazione massimo per il tenant, come impostato dall'amministratore della griglia.

+
Un _massimo_ periodo di conservazione, che può essere un valore compreso tra 1 giorno e 100 anni, viene impostato quando l'amministratore di rete crea il tenant. Quando si imposta un periodo di conservazione _default_, non può superare il valore impostato per il periodo di conservazione massimo. Se necessario, chiedere all'amministratore di rete di aumentare o diminuire il periodo di conservazione massimo.

. Selezionare *Save Changes* (Salva modifiche).

