---
permalink: tenant/viewing-your-s3-access-keys.html 
sidebar: sidebar 
keywords: how to view your s3 access key 
summary: 'Se si utilizza un tenant S3 e si dispone delle autorizzazioni appropriate, è possibile visualizzare un elenco delle chiavi di accesso S3. È possibile ordinare l"elenco in base alla data di scadenza, in modo da determinare quali chiavi scadranno a breve. In base alle esigenze, è possibile creare nuove chiavi o eliminare chiavi che non vengono più utilizzate.' 
---
= Visualizzare le chiavi di accesso S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizza un locatario S3 e si dispone di link:tenant-management-permissions.html["autorizzazione appropriata"], è possibile visualizzare un elenco delle chiavi di accesso S3. È possibile ordinare l'elenco in base alla data di scadenza, in modo da determinare quali chiavi scadranno a breve. Se necessario, è possibile link:creating-your-own-s3-access-keys.html["creare nuove chiavi"] o link:deleting-your-own-s3-access-keys.html["eliminare le chiavi"] che non si sta più utilizzando.


CAUTION: È possibile accedere ai bucket S3 e agli oggetti appartenenti al tuo account utilizzando l'ID della chiave di accesso e la chiave di accesso segreta visualizzati per il tuo account in Tenant Manager. Per questo motivo, proteggere le chiavi di accesso come se si trattasse di una password. Ruotare regolarmente le chiavi di accesso, rimuovere eventuali chiavi inutilizzate dall'account e non condividerle mai con altri utenti.

.Prima di iniziare
* L'utente ha effettuato l'accesso al responsabile del tenant utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* L'utente appartiene a un gruppo di utenti che dispone delle credenziali Manage your own S3 link:tenant-management-permissions.html["permesso"](Gestisci le proprie credenziali 3D).


.Fasi
. Selezionare *STORAGE (S3)* > *My access key*.
. Dalla pagina My access keys (i miei tasti di accesso), ordinare le chiavi di accesso esistenti in base a *Expiration Time* (ora di scadenza) o *Access key ID* (ID chiave di accesso).
. Se necessario, creare nuove chiavi o eliminare le chiavi che non si stanno più utilizzando.
+
Se si creano nuove chiavi prima della scadenza delle chiavi esistenti, è possibile iniziare a utilizzare le nuove chiavi senza perdere temporaneamente l'accesso agli oggetti dell'account.

+
Le chiavi scadute vengono rimosse automaticamente.


