---
permalink: rhel/installing-linux.html 
sidebar: sidebar 
keywords: how to install on red hat linux 
summary: È necessario installare StorageGRID su tutti i grid host Red Hat Enterprise Linux. Per un elenco delle versioni supportate, utilizza lo strumento matrice di interoperabilità NetApp. 
---
= Installare Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario installare StorageGRID su tutti i grid host Red Hat Enterprise Linux. Per un elenco delle versioni supportate, utilizza lo strumento matrice di interoperabilità NetApp.

.Prima di iniziare
Verificare che il sistema operativo soddisfi i requisiti minimi di versione del kernel di StorageGRID, come indicato di seguito. Utilizzare il comando `uname -r` per ottenere la versione del kernel del sistema operativo o consultare il fornitore del sistema operativo.

[cols="1a,2a,2a"]
|===
| Versione di Red Hat Enterprise Linux | Versione minima del kernel | Nome del pacchetto kernel 


 a| 
8,8 (obsoleto)
 a| 
4.18.0-477.10.1.el8_8.x86_64
 a| 
kernel-4.18.0-477.10.1.el8_8.x86_64



 a| 
8,10
 a| 
4.18.0-553.el8_10.x86_64
 a| 
kernel-4.18.0-553.el8_10.x86_64



 a| 
9,0 (obsoleto)
 a| 
5.14.0-70.22.1.el9_0.x86_64
 a| 
kernel-5.14.0-70.22.1.el9_0.x86_64



 a| 
9,2 (obsoleto)
 a| 
5.14.0-284.11.1.el9_2.x86_64
 a| 
kernel-5.14.0-284.11.1.el9_2.x86_64



 a| 
9,4
 a| 
5.14.0-427.18.1.el9_4.x86_64
 a| 
kernel-5.14.0-427.18.1.el9_4.x86_64

|===
.Fasi
. Installare Linux su tutti gli host grid fisici o virtuali in base alle istruzioni del distributore o alla procedura standard.
+

NOTE: Se si utilizza l'installatore Linux standard, selezionare la configurazione del software "nodo di elaborazione", se disponibile, o l'ambiente di base "installazione minima". Non installare ambienti desktop grafici.

. Assicurarsi che tutti gli host abbiano accesso ai repository dei pacchetti, incluso il canale Extra.
+
Questi pacchetti aggiuntivi potrebbero essere necessari più avanti in questa procedura di installazione.

. Se lo swap è attivato:
+
.. Eseguire il seguente comando: `$ sudo swapoff --all`
.. Rimuovere tutte le voci di swap da `/etc/fstab` per mantenere le impostazioni.


+

NOTE: La mancata disattivazione completa dello swap può ridurre notevolmente le performance.


