---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Ogni nodo della griglia ha una password della console del nodo, che puoi utilizzare per accedere al nodo.  Per impostazione predefinita, ogni nodo ha una password univoca.  È possibile modificare ciascuna password con una nuova password univoca oppure è possibile modificare la password di ogni nodo per utilizzare una password globale.  Le password vengono memorizzate nel pacchetto di ripristino. 
---
= Modificare le password della console dei nodi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni nodo della griglia ha una password della console del nodo, che puoi utilizzare per accedere al nodo.  Per impostazione predefinita, ogni nodo ha una password univoca.  È possibile modificare ciascuna password con una nuova password univoca oppure è possibile modificare la password di ogni nodo per utilizzare una password globale.  Le password vengono memorizzate nel pacchetto di ripristino.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone di link:admin-group-permissions.html["Autorizzazione di manutenzione o di accesso root"].
* Si dispone della passphrase di provisioning corrente.


.A proposito di questa attività
Si utilizza una password della console del nodo per accedere a un nodo come "admin" tramite SSH oppure come utente root su una connessione alla console fisica/VM.  È possibile modificare le password della console del nodo utilizzando una di queste opzioni:

* Applica automaticamente password casuali a ciascun nodo
* Specificare e applicare una password globale a tutti i nodi
* Specificare e applicare una password univoca a uno o più nodi


Le password vengono memorizzate in un file aggiornato `Passwords.txt` file nel pacchetto di ripristino.  Le password sono elencate nella colonna Password del file.


NOTE: ILlink:../admin/change-ssh-access-passwords.html["Password di accesso SSH"] poiché le chiavi SSH utilizzate per la comunicazione tra i nodi sono separate dalle password della console del nodo.  Questa procedura non modifica le password di accesso SSH.



== Accedere alla procedura guidata

.Fasi
. Selezionare *Configurazione* > *Controllo accessi* > *Password griglia*.
. In *Cambia password console nodo*, selezionare *effettua una modifica*.




== [[download-current]]Scarica il pacchetto di ripristino corrente

Prima di modificare le password della console del nodo, scaricare il pacchetto di ripristino corrente.  È possibile utilizzare le password contenute in questo file se il processo di modifica della password non riesce per un nodo.

.Fasi
. Inserire la passphrase di provisioning per la griglia.
. Selezionare *Download recovery package* (Scarica pacchetto di ripristino).
. Copia il file del pacchetto di ripristino(`.zip` ) in due luoghi sicuri, protetti e separati.
+

CAUTION: Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID .

. Selezionare *continua*.




== Fornire nuove password

. Seleziona il metodo di modifica della password che desideri utilizzare.
+
** *Automatico*: StorageGRID assegna automaticamente una nuova password casuale della console a tutti i nodi.
** *Personalizzato*: fornisci le password della console.




[role="tabbed-block"]
====
.Automatico
--
. Selezionare *continua*.


--
.Personalizzato
--
. Selezionare una delle seguenti opzioni:
+
** *Password console globale*: applica la stessa password console a tutti i nodi.
** *Password univoche della console*: applica una password diversa su uno o più nodi.


. Se hai selezionato *Password console globale*, inserisci la password che desideri utilizzare per tutti i nodi.
. Se hai selezionato *Password console univoche*, inserisci una password univoca per uno o più nodi.
. Selezionare *continua*.


--
====


== Completa la modifica della password

. Quando viene visualizzata la finestra di dialogo di conferma, selezionare *Sì* se si è pronti affinché StorageGRID inizi a modificare le password della console del nodo.
+

NOTE: Non puoi annullare questo processo dopo l'avvio.

+
StorageGRID genera un nuovo pacchetto di ripristino contenente la nuova password.

. Quando il nuovo pacchetto di ripristino è pronto, seleziona *Scarica nuovo pacchetto di ripristino* e salva il pacchetto di ripristino.
. Aprire il `.zip` file.
. Verificare che sia possibile accedere al contenuto, incluso il `Passwords.txt` file, che contiene le nuove password della console del nodo.
. Copia il nuovo file del pacchetto di ripristino(`.zip` ) in due luoghi sicuri, protetti e separati.
+

CAUTION: Non sovrascrivere il vecchio pacchetto di ripristino.

+
È necessario proteggere il file di ripristino, poiché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID .

. Seleziona la casella di controllo per indicare che hai scaricato il nuovo pacchetto di ripristino e ne hai verificato il contenuto.
. Selezionare *continua*.
+
StorageGRID aggiorna la password per ciascun nodo.

+
Se si verifica un errore durante il processo di aggiornamento, la barra di avanzamento elenca il numero di nodi le cui password non sono state modificate.  Il sistema riproverà automaticamente il processo su qualsiasi nodo la cui password non è riuscita a cambiare.  Se il processo termina con alcuni nodi che non hanno ancora modificato la password, viene visualizzato il pulsante *Riprova*.

. Se l'aggiornamento della password non è riuscito per uno o più nodi:
+
.. Esaminare i messaggi di errore elencati nella tabella.
.. Risolvere i problemi.
.. Selezionare *Riprova*.
+

NOTE: Il nuovo tentativo modifica solo le password della console dei nodi sui nodi che non sono riusciti durante i precedenti tentativi di modifica della password.



. Quando la barra di avanzamento indica che non ci sono aggiornamenti rimanenti, selezionare *Fine*.
. Dopo aver modificato le password della console del nodo per tutti i nodi, eliminare il<<download-current,primo pacchetto di ripristino scaricato>> .

