---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: 'La modifica delle password di accesso SSH per i nodi Admin aggiorna anche i set univoci di chiavi SSH interne per ogni nodo nella griglia. Il nodo amministrativo primario utilizza queste chiavi SSH per accedere ai nodi utilizzando un"autenticazione protetta e senza password.' 
---
= Modificare le password di accesso SSH per i nodi Admin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La modifica delle password di accesso SSH per i nodi Admin aggiorna anche i set univoci di chiavi SSH interne per ogni nodo nella griglia. Il nodo amministrativo primario utilizza queste chiavi SSH per accedere ai nodi utilizzando un'autenticazione protetta e senza password.

Utilizzare una chiave SSH per accedere a un nodo come `admin` o all'utente root su una connessione VM o console fisica.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone di link:admin-group-permissions.html["Autorizzazione di manutenzione o di accesso root"].
* Si dispone della passphrase di provisioning corrente.


.A proposito di questa attività
Le nuove password di accesso per i nodi di amministrazione e le nuove chiavi interne per ciascun nodo sono memorizzate nel `Passwords.txt` file nel pacchetto di ripristino.  Le chiavi sono elencate nella colonna Password di quel file.

Esistono password di accesso SSH separate per le chiavi SSH utilizzate per la comunicazione tra i nodi. Questi non vengono modificati da questa procedura.



== Accedere alla procedura guidata

.Fasi
. Selezionare *Configurazione* > *Controllo accessi* > *Password griglia*.
. In *Cambia chiavi SSH*, selezionare *effettua una modifica*.




== [[download-current]]Scarica il pacchetto di ripristino corrente

Prima di modificare le chiavi di accesso SSH, scaricare il pacchetto di ripristino corrente.  È possibile utilizzare le chiavi contenute in questo file se il processo di modifica delle chiavi non riesce per un nodo.

.Fasi
. Inserire la passphrase di provisioning per la griglia.
. Selezionare *Download recovery package* (Scarica pacchetto di ripristino).
. Copia il file del pacchetto di ripristino(`.zip` ) in due luoghi sicuri, protetti e separati.
+

CAUTION: Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID .

. Selezionare *continua*.
. Quando viene visualizzata la finestra di dialogo di conferma, selezionare *Sì* se si è pronti a cambiare le chiavi di accesso SSH.
+

CAUTION: Non puoi annullare questo processo dopo l'avvio.





== Modificare le chiavi di accesso SSH

Quando viene avviato il processo di modifica delle chiavi di accesso SSH, viene generato un nuovo pacchetto di ripristino che include le nuove chiavi.  Quindi, le chiavi vengono aggiornate su ciascun nodo.

.Fasi
. Attendi che venga generato il nuovo pacchetto di ripristino, operazione che potrebbe richiedere alcuni minuti.
. Quando il pulsante Scarica nuovo pacchetto di ripristino è abilitato, seleziona *Scarica nuovo pacchetto di ripristino* e salva il nuovo file del pacchetto di ripristino(`.zip` ) in due luoghi sicuri, protetti e separati.
. Al termine del download:
+
.. Aprire il `.zip` file.
.. Verificare che sia possibile accedere al contenuto, incluso il `Passwords.txt` file, che contiene le nuove chiavi di accesso SSH.
.. Copia il nuovo file del pacchetto di ripristino(`.zip` ) in due luoghi sicuri, protetti e separati.
+

CAUTION: Non sovrascrivere il vecchio pacchetto di ripristino.

+
Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID .



. Attendere l'aggiornamento delle chiavi su ciascun nodo, operazione che potrebbe richiedere alcuni minuti.
+
Se le chiavi vengono modificate per tutti i nodi, viene visualizzato un banner di successo verde.

+
Se si verifica un errore durante il processo di aggiornamento, un messaggio di intestazione elenca il numero di nodi che non sono riusciti a modificare le chiavi. Il sistema ritenta automaticamente il processo su qualsiasi nodo che non ha modificato la chiave. Se il processo termina con alcuni nodi che non hanno ancora una chiave modificata, viene visualizzato il pulsante *Riprova*.

+
Se l'aggiornamento della chiave non è riuscito per uno o più nodi:

+
.. Esaminare i messaggi di errore elencati nella tabella.
.. Risolvere i problemi.
.. Selezionare *Riprova*.
+
Il nuovo tentativo modifica solo le chiavi di accesso SSH sui nodi che hanno avuto esito negativo durante i precedenti tentativi di modifica della chiave.



. Dopo aver modificato le chiavi di accesso SSH per tutti i nodi, eliminare<<download-current,primo pacchetto di ripristino scaricato>> .
. Facoltativamente, selezionare *Manutenzione* > *Sistema* > *Pacchetto di ripristino* per scaricare una copia aggiuntiva del nuovo pacchetto di ripristino.

