---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Ogni nodo nella griglia dispone di una password della console di nodo, che viene utilizzata per accedere al nodo. Per impostazione predefinita, ogni nodo dispone di una password univoca. È possibile modificare ogni password in una nuova password univoca oppure modificare la password per ogni nodo per utilizzare una password globale. Le password vengono memorizzate nel pacchetto di ripristino. 
---
= Modificare le password della console dei nodi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni nodo nella griglia dispone di una password della console di nodo, che viene utilizzata per accedere al nodo. Per impostazione predefinita, ogni nodo dispone di una password univoca. È possibile modificare ogni password in una nuova password univoca oppure modificare la password per ogni nodo per utilizzare una password globale. Le password vengono memorizzate nel pacchetto di ripristino.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone di link:admin-group-permissions.html["Autorizzazione di manutenzione o di accesso root"].
* Si dispone della passphrase di provisioning corrente.


.A proposito di questa attività
Si utilizza una password della console del nodo per accedere a un nodo come "admin" utilizzando SSH o all'utente root su una connessione VM/console fisica. È possibile modificare le password della console dei nodi utilizzando una delle seguenti opzioni:

* Applica automaticamente password casuali a ciascun nodo
* Specificare e applicare una password globale a tutti i nodi
* Specificare e applicare una password univoca a uno o più nodi


Le password vengono memorizzate in un file aggiornato `Passwords.txt` nel pacchetto di ripristino. Le password sono elencate nella colonna Password del file.


NOTE: Le link:../admin/change-ssh-access-passwords.html["Password di accesso SSH"]chiavi SSH utilizzate per la comunicazione tra i nodi sono separate dalle password della console del nodo. Questa procedura non modifica le password di accesso SSH.



== Accedere alla procedura guidata

.Fasi
. Selezionare *CONFIGURATION* > *Access control* > *Grid passwords*.
. In *Cambia password console nodo*, selezionare *effettua una modifica*.




== [[download-current]]Scarica il pacchetto di ripristino corrente

Prima di modificare le password della console dei nodi, scaricare il pacchetto di ripristino corrente. È possibile utilizzare le password in questo file se il processo di modifica della password non riesce per qualsiasi nodo.

.Fasi
. Inserire la passphrase di provisioning per la griglia.
. Selezionare *Download recovery package* (Scarica pacchetto di ripristino).
. Copiare il file del pacchetto di ripristino (`.zip`) in due posizioni sicure, sicure e separate.
+

CAUTION: Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID.

. Selezionare *continua*.




== Fornire nuove password

. Selezionare il metodo di modifica della password che si desidera utilizzare.
+
** *Automatico*: StorageGRID assegna automaticamente una nuova password di console casuale a tutti i nodi.
** *Personalizzato*: Vengono fornite le password della console.




[role="tabbed-block"]
====
.Automatico
--
. Selezionare *continua*.


--
.Personalizzato
--
. Selezionare una delle seguenti opzioni:
+
** *Global console password*: Applica la stessa password della console a tutti i nodi.
** *Password univoche della console*: Applica una password diversa su uno o più nodi.


. Se si seleziona *Global console password*, immettere la password che si desidera utilizzare per tutti i nodi.
. Se è stata selezionata l'opzione *password console univoche*, immettere una password univoca per uno o più nodi.
. Selezionare *continua*.


--
====


== Completare la modifica della password

. Quando viene visualizzata la finestra di dialogo di conferma, selezionare *Sì* se si è pronti per StorageGRID a modificare le password della console del nodo.
+

NOTE: Non puoi annullare questo processo dopo l'avvio.

+
StorageGRID genera un nuovo pacchetto di ripristino contenente la nuova password.

. Quando il nuovo pacchetto di ripristino è pronto, selezionare *Scarica nuovo pacchetto di ripristino* e salvare il pacchetto di ripristino.
. Aprire il `.zip` file.
. Verificare che sia possibile accedere al contenuto, incluso il `Passwords.txt` file, che contiene le nuove password della console del nodo.
. Copiare il nuovo file del pacchetto di ripristino (`.zip`) in due posizioni sicure, sicure e separate.
+

CAUTION: Non sovrascrivere il vecchio pacchetto di ripristino.

+
È necessario proteggere il file di ripristino, poiché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID.

. Seleziona la casella di controllo per indicare che hai scaricato il nuovo pacchetto di ripristino e verificato il contenuto.
. Selezionare *continua*.
+
StorageGRID aggiorna la password per ogni nodo.

+
Se si verifica un errore durante il processo di aggiornamento, la barra di avanzamento elenca il numero di nodi che non sono riusciti a modificare le password. Il sistema riprova automaticamente il processo su qualsiasi nodo che non ha modificato la password. Se il processo termina con alcuni nodi che non hanno ancora una password modificata, viene visualizzato il pulsante *Riprova*.

. Se l'aggiornamento della password non è riuscito per uno o più nodi:
+
.. Esaminare i messaggi di errore elencati nella tabella.
.. Risolvere i problemi.
.. Selezionare *Riprova*.
+

NOTE: Il nuovo tentativo modifica solo le password della console dei nodi sui nodi che non sono riusciti durante i precedenti tentativi di modifica della password.



. Quando la barra di avanzamento indica che non sono rimasti aggiornamenti, selezionare *fine*.
. Dopo aver modificato le password della console del nodo per tutti i nodi, eliminare <<download-current,primo pacchetto di ripristino scaricato>>.

