---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Ogni nodo della griglia dispone di una password univoca per la console del nodo, che è necessario accedere al nodo. Seguire questa procedura per modificare la password della console dei nodi per ciascun nodo della griglia. Le password vengono memorizzate nel pacchetto di ripristino. 
---
= Modificare le password della console dei nodi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni nodo della griglia dispone di una password univoca per la console del nodo, che è necessario accedere al nodo. Seguire questa procedura per modificare ogni password univoca della console dei nodi per ciascun nodo della griglia.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone di link:admin-group-permissions.html["Autorizzazione di manutenzione o di accesso root"].
* Si dispone della passphrase di provisioning corrente.


.A proposito di questa attività
Utilizzare la password della console del nodo per accedere a un nodo come "admin" utilizzando SSH o all'utente root su una connessione VM/console fisica. Il processo di modifica della password della console del nodo crea nuove password per ogni nodo nella griglia e memorizza le password in un file aggiornato `Passwords.txt` nel pacchetto di ripristino. Le password sono elencate nella colonna Password del file Passwords.txt.


NOTE: Esistono password di accesso SSH separate per le chiavi SSH utilizzate per la comunicazione tra i nodi. Questa procedura non modifica le password di accesso SSH.



== Accedere alla procedura guidata

.Fasi
. Selezionare *CONFIGURATION* > *Access control* > *Grid passwords*.
. In *Cambia password console nodo*, selezionare *effettua una modifica*.




== Inserire la passphrase di provisioning

.Fasi
. Inserire la passphrase di provisioning per la griglia.
. Selezionare *continua*.




== [[download-current]]Scarica il pacchetto di ripristino corrente

Prima di modificare le password della console dei nodi, scaricare il pacchetto di ripristino corrente. È possibile utilizzare le password in questo file se il processo di modifica della password non riesce per qualsiasi nodo.

.Fasi
. Selezionare *Download recovery package* (Scarica pacchetto di ripristino).
. Copiare il file del pacchetto di ripristino (`.zip`) in due posizioni sicure, sicure e separate.
+

CAUTION: Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID.

. Selezionare *continua*.
. Quando viene visualizzata la finestra di dialogo di conferma, selezionare *Yes* (Sì) se si desidera iniziare a modificare le password della console del nodo.
+
Non puoi annullare questo processo dopo l'avvio.





== Modificare le password della console dei nodi

All'avvio del processo di password della console dei nodi, viene generato un nuovo pacchetto di ripristino che include le nuove password. Quindi, le password vengono aggiornate su ciascun nodo.

.Fasi
. Attendere che venga generato il nuovo pacchetto di ripristino, che potrebbe richiedere alcuni minuti.
. Selezionare *Scarica nuovo pacchetto di ripristino*.
. Al termine del download:
+
.. Aprire il `.zip` file.
.. Verificare che sia possibile accedere al contenuto, incluso il `Passwords.txt` file, che contiene le nuove password della console del nodo.
.. Copiare il nuovo file del pacchetto di ripristino (`.zip`) in due posizioni sicure, protette e separate.
+

CAUTION: Non sovrascrivere il vecchio pacchetto di ripristino.

+
Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID.



. Selezionare la casella di controllo per indicare che è stato scaricato il nuovo pacchetto di ripristino e che il contenuto è stato verificato.
. Selezionare *Change node console passwords* (Modifica password console nodi) e attendere che tutti i nodi vengano aggiornati con le nuove password. L'operazione potrebbe richiedere alcuni minuti.
+
Se le password vengono modificate per tutti i nodi, viene visualizzato un banner verde di successo. Passare alla fase successiva.

+
Se si verifica un errore durante il processo di aggiornamento, un messaggio di intestazione indica il numero di nodi che non sono riusciti a modificare le password. Il sistema riprova automaticamente il processo su qualsiasi nodo che non ha modificato la password. Se il processo termina con alcuni nodi che non hanno ancora una password modificata, viene visualizzato il pulsante *Riprova*.

+
Se l'aggiornamento della password non è riuscito per uno o più nodi:

+
.. Esaminare i messaggi di errore elencati nella tabella.
.. Risolvere i problemi.
.. Selezionare *Riprova*.
+

NOTE: Il nuovo tentativo modifica solo le password della console dei nodi sui nodi che non sono riusciti durante i precedenti tentativi di modifica della password.



. Dopo aver modificato le password della console del nodo per tutti i nodi, eliminare <<download-current,Primo pacchetto di ripristino scaricato>>.
. Facoltativamente, utilizzare il collegamento *Recovery package* per scaricare una copia aggiuntiva del nuovo Recovery Package.

