---
permalink: admin/configure-sso.html 
sidebar: sidebar 
keywords: use sandbox mode for sso, how to test single sign-on 
summary: 'È possibile seguire la procedura guidata Configura SSO e accedere alla modalità sandbox per configurare e verificare il single sign-on \(SSO\) prima di attivarlo per tutti gli utenti StorageGRID. Una volta attivato SSO, è possibile tornare alla modalità sandbox quando necessario per modificare o ripetere il test della configurazione.' 
---
= Configure SSO (Configura SNMP)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile seguire la procedura guidata Configura SSO e accedere alla modalità sandbox per configurare e testare il single sign-on (SSO) prima di attivarlo per tutti gli utenti StorageGRID. Dopo aver attivato SSO, è possibile tornare alla modalità sandbox quando è necessario modificare o ripetere il test della configurazione.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone di link:admin-group-permissions.html["Autorizzazione di accesso root"].
* Hai configurato la federazione delle identità per il tuo sistema StorageGRID.
* Per il tipo di servizio federazione identità *LDAP*, è stato selezionato Active Directory o Entra ID, in base al provider di identità SSO che si intende utilizzare.
+
[cols="1a,1a"]
|===
| Tipo di servizio LDAP configurato | Opzioni per il provider di identità SSO 


 a| 
Active Directory Federation Service (ad FS)
 a| 
** Active Directory
** ID entra
** PingFederate




 a| 
ID entra
 a| 
ID entra

|===


.A proposito di questa attività
Quando SSO è attivato e un utente tenta di accedere a un nodo amministratore, StorageGRID invia una richiesta di autenticazione al provider di identità SSO. A sua volta, il provider di identità SSO invia una risposta di autenticazione a StorageGRID, indicando se la richiesta di autenticazione ha avuto esito positivo. Per le richieste riuscite:

* La risposta di Active Directory o PingFederate include un UUID (Universally Unique Identifier) per l'utente.
* La risposta da Entra ID include un User Principal Name (UPN).


Per consentire a StorageGRID (il provider di servizi) e al provider di identità SSO di comunicare in modo sicuro sulle richieste di autenticazione degli utenti, è necessario completare le seguenti attività:

. Configurare le impostazioni in StorageGRID.
. Utilizzare il software del provider di identità SSO per creare un trust per le parti di fiducia (ad FS), un'applicazione aziendale (Entra ID) o un provider di servizi (PingFederate) per ogni nodo amministrativo.
. Tornare a StorageGRID per attivare SSO.


La modalità sandbox semplifica l'esecuzione di questa configurazione e il test di tutte le impostazioni prima di attivare SSO. Quando si utilizza la modalità sandbox, gli utenti non possono accedere utilizzando SSO.



== Accedere alla procedura guidata

.Fasi
. Selezionare *CONFIGURATION* > *Access control* > *Single Sign-on*. Viene visualizzata la pagina Single Sign-on (accesso singolo).
+

NOTE: Se il pulsante Configura impostazioni SSO è disattivato, verificare di aver configurato il provider di identità come origine identità federated. Fare riferimento alla link:requirements-for-sso.html["Requisiti e considerazioni per il single sign-on"].

. Selezionare *Configura impostazioni SSO*. Viene visualizzata la pagina specifica i dettagli del provider di identità.




== Fornire i dettagli del provider di identità

.Fasi
. Selezionare *tipo SSO* dall'elenco a discesa.
. Se è stato selezionato Active Directory come tipo SSO, immettere il nome del servizio *Federation* per il provider di identità, esattamente come appare in Active Directory Federation Service (ad FS).
+

NOTE: Per individuare il nome del servizio federativo, accedere a Gestione server Windows. Selezionare *Tools* > *ad FS Management*. Dal menu Action (azione), selezionare *Edit Federation Service Properties* (Modifica proprietà servizio federazione). Il nome del servizio della federazione viene visualizzato nel secondo campo.

. Specificare il certificato TLS da utilizzare per proteggere la connessione quando il provider di identità invia le informazioni di configurazione SSO in risposta alle richieste StorageGRID.
+
** *Usa certificato CA del sistema operativo*: Utilizzare il certificato CA predefinito installato sul sistema operativo per proteggere la connessione.
** *Usa certificato CA personalizzato*: Utilizza un certificato CA personalizzato per proteggere la connessione.
+
Se si seleziona questa impostazione, copiare il testo del certificato personalizzato e incollarlo nella casella di testo *certificato CA*.

** *Non utilizzare TLS*: Non utilizzare un certificato TLS per proteggere la connessione.
+

CAUTION: Se si modifica il certificato CA, eseguire immediatamente link:../maintain/starting-or-restarting-service.html["Riavviare il servizio Mgmt-api sui nodi Admin"]il test di un SSO corretto in Grid Manager.



. Selezionare *continua*. Viene visualizzata la pagina Fornisci identificatore del soggetto che si affida.




== [[ENTER-sandbox-mode]]fornire l'identificatore della parte che si affida

. Completare i campi nella pagina Fornisci identificatore parte in base al tipo di SSO selezionato.
+
[role="tabbed-block"]
====
.Active Directory
--
.. Specificare l'identificatore * della parte che si basa su StorageGRID. Questo valore controlla il nome utilizzato per ciascun trust di parte che si basa in ad FS.
+
*** Ad esempio, se la griglia dispone di un solo nodo amministrativo e non si prevede di aggiungere altri nodi amministrativi in futuro, immettere `SG` o `StorageGRID`.
*** Se la griglia include più di un nodo amministrativo, includere la stringa `[HOSTNAME]` nell'identificatore. Ad esempio, `SG-[HOSTNAME]`. L'inclusione di questa stringa genera una tabella che mostra l'identificatore della parte di affidamento per ogni nodo Admin nella griglia, in base al nome host del nodo.
+

NOTE: È necessario creare un trust per ciascun nodo amministratore nel sistema StorageGRID. La disponibilità di un trust per ciascun nodo di amministrazione garantisce che gli utenti possano accedere e uscire in modo sicuro da qualsiasi nodo di amministrazione.



.. Selezionare *Salva e accedere alla modalità sandbox*.


--
.ID entra
--
.. Nella sezione applicazione aziendale, specificare *Nome applicazione aziendale* per StorageGRID. Questo valore controlla il nome utilizzato per ogni applicazione aziendale in Entra ID.
+
*** Ad esempio, se la griglia dispone di un solo nodo amministrativo e non si prevede di aggiungere altri nodi amministrativi in futuro, immettere `SG` o `StorageGRID`.
*** Se la griglia include più di un nodo amministrativo, includere la stringa `[HOSTNAME]` nell'identificatore. Ad esempio, `SG-[HOSTNAME]`. Se si include questa stringa, viene visualizzata una tabella che mostra il nome di un'applicazione aziendale per ogni nodo amministrativo del sistema, in base al nome host del nodo.
+

NOTE: È necessario creare un'applicazione aziendale per ciascun nodo amministratore nel sistema StorageGRID. La disponibilità di un'applicazione aziendale per ciascun nodo di amministrazione garantisce che gli utenti possano accedere e uscire in modo sicuro da qualsiasi nodo di amministrazione.



.. Per creare un'applicazione aziendale per ciascun nodo amministrativo elencato nella tabella, attenersi alla procedura descritta inlink:../admin/creating-enterprise-application-entra-id.html["Creare applicazioni aziendali in Entra ID"].
.. Da Entra ID, copiare l'URL dei metadati della federazione per ogni applicazione aziendale. Quindi, incolla questo URL nel corrispondente campo *URL metadati federazione* in StorageGRID.
.. Dopo aver copiato e incollato un URL dei metadati della federazione per tutti i nodi Admin, selezionare *Salva e accedere alla modalità sandbox*.


--
.PingFederate
--
.. Nella sezione Provider di servizi (SP), specificare *ID connessione SP* per StorageGRID. Questo valore controlla il nome utilizzato per ogni connessione SP in PingFederate.
+
*** Ad esempio, se la griglia dispone di un solo nodo amministrativo e non si prevede di aggiungere altri nodi amministrativi in futuro, immettere `SG` o `StorageGRID`.
*** Se la griglia include più di un nodo amministrativo, includere la stringa `[HOSTNAME]` nell'identificatore. Ad esempio, `SG-[HOSTNAME]`. L'inclusione di questa stringa genera una tabella che mostra l'ID di connessione SP per ogni nodo amministrativo nel sistema, in base al nome host del nodo.
+

NOTE: È necessario creare una connessione SP per ciascun nodo amministratore nel sistema StorageGRID. La disponibilità di una connessione SP per ciascun nodo di amministrazione garantisce che gli utenti possano accedere e uscire in modo sicuro da qualsiasi nodo di amministrazione.



.. Specificare l'URL dei metadati della federazione per ciascun nodo amministratore nel campo *URL metadati federazione*.
+
Utilizzare il seguente formato:

+
[listing]
----
https://<Federation Service Name>:<port>/pf/federation_metadata.ping?PartnerSpId=<SP Connection ID>
----
.. Selezionare *Salva e accedere alla modalità sandbox*.


--
====




== Configurare i trust, le applicazioni aziendali o le connessioni SP della parte che si basa

Una volta salvata la configurazione e attivata la modalità sandbox, è possibile completare e testare la configurazione per il tipo SSO selezionato.

StorageGRID può rimanere in modalità sandbox per tutto il tempo necessario. Tuttavia, solo gli utenti federated e gli utenti locali possono accedere.

[role="tabbed-block"]
====
.Active Directory
--
.Fasi
. Accedere a Active Directory Federation Services (ad FS).
. Creare uno o più trust per StorageGRID, utilizzando ogni identificatore di parte attendibile mostrato nella tabella nella pagina Configura SSO.
+
È necessario creare un trust per ciascun nodo di amministrazione mostrato nella tabella.

+
Per istruzioni, vedere link:../admin/creating-relying-party-trusts-in-ad-fs.html["Creazione di trust di parti di base in ad FS"].



--
.ID entra
--
.Fasi
. Dalla pagina Single Sign-on (accesso singolo) per il nodo di amministrazione a cui si è attualmente connessi, selezionare il pulsante per scaricare e salvare i metadati SAML.
. Quindi, per tutti gli altri nodi di amministrazione della griglia, ripetere questi passaggi:
+
.. Accedere al nodo.
.. Selezionare *CONFIGURATION* > *Access control* > *Single Sign-on*.
.. Scaricare e salvare i metadati SAML per quel nodo.


. Vai al portale Azure.
. Seguire la procedura descritta in link:../admin/creating-enterprise-application-entra-id.html["Creare applicazioni aziendali in Entra ID"] per caricare il file di metadati SAML di ogni nodo amministrativo nella relativa applicazione Enterprise Entra ID corrispondente.


--
.PingFederate
--
.Fasi
. Dalla pagina Single Sign-on (accesso singolo) per il nodo di amministrazione a cui si è attualmente connessi, selezionare il pulsante per scaricare e salvare i metadati SAML.
. Quindi, per tutti gli altri nodi di amministrazione della griglia, ripetere questi passaggi:
+
.. Accedere al nodo.
.. Selezionare *CONFIGURATION* > *Access control* > *Single Sign-on*.
.. Scaricare e salvare i metadati SAML per quel nodo.


. Accedere a PingFederate.
. link:../admin/creating-sp-connection-ping.html["Creare una o più connessioni del provider di servizi (SP) per StorageGRID"]. Utilizzare l'ID di connessione SP per ogni nodo amministrativo (mostrato nella tabella nella pagina Configura SSO) e i metadati SAML scaricati per quel nodo amministrativo.
+
È necessario creare una connessione SP per ciascun nodo di amministrazione mostrato nella tabella.



--
====


== [[test-sso]]Test della configurazione

Prima di applicare l'uso del single sign-on per l'intero sistema StorageGRID, verificare che il single sign-on e il single logout siano configurati correttamente per ogni nodo amministrativo.

[role="tabbed-block"]
====
.Active Directory
--
.Fasi
. Nella pagina Configura SSO, individuare il collegamento nella fase di configurazione di prova della procedura guidata.
+
L'URL deriva dal valore immesso nel campo *Federation service name*.

. Selezionare il collegamento oppure copiare e incollare l'URL in un browser per accedere alla pagina di accesso del provider di identità.
. Per confermare che è possibile utilizzare SSO per accedere a StorageGRID, selezionare *Accedi a uno dei seguenti siti*, selezionare l'identificativo della parte di base per il nodo di amministrazione principale e selezionare *Accedi*.
. Immettere il nome utente e la password federated.
+
** Se le operazioni di accesso e disconnessione SSO hanno esito positivo, viene visualizzato un messaggio di esito positivo.
** Se l'operazione SSO non riesce, viene visualizzato un messaggio di errore. Risolvere il problema, eliminare i cookie del browser e riprovare.


. Ripetere questa procedura per verificare la connessione SSO per ciascun nodo di amministrazione nella griglia.


--
.ID entra
--
.Fasi
. Vai alla pagina Single Sign-on nel portale Azure.
. Selezionare *Test dell'applicazione*.
. Immettere le credenziali di un utente federated.
+
** Se le operazioni di accesso e disconnessione SSO hanno esito positivo, viene visualizzato un messaggio di esito positivo.
** Se l'operazione SSO non riesce, viene visualizzato un messaggio di errore. Risolvere il problema, eliminare i cookie del browser e riprovare.


. Ripetere questa procedura per verificare la connessione SSO per ciascun nodo di amministrazione nella griglia.


--
.PingFederate
--
.Fasi
. Nella pagina Configura SSO, selezionare il primo collegamento nel messaggio in modalità Sandbox.
+
Selezionare e verificare un collegamento alla volta.

. Immettere le credenziali di un utente federated.
+
** Se le operazioni di accesso e disconnessione SSO hanno esito positivo, viene visualizzato un messaggio di esito positivo.
** Se l'operazione SSO non riesce, viene visualizzato un messaggio di errore. Risolvere il problema, eliminare i cookie del browser e riprovare.


. Selezionare il collegamento successivo per verificare la connessione SSO per ciascun nodo di amministrazione nella griglia.
+
Se viene visualizzato un messaggio Page Expired (pagina scaduta), selezionare il pulsante *Back* (Indietro) nel browser e inviare nuovamente le credenziali.



--
====


== Attiva single sign-on

Una volta confermata la possibilità di utilizzare SSO per accedere a ciascun nodo amministrativo, è possibile attivare SSO per l'intero sistema StorageGRID.


TIP: Quando SSO è attivato, tutti gli utenti devono utilizzare SSO per accedere a Grid Manager, Tenant Manager, Grid Management API e Tenant Management API. Gli utenti locali non possono più accedere a StorageGRID.

.Fasi
. Dal passaggio di configurazione del test della configurazione guidata SSO, selezionare *attiva SSO*.
. Rivedere il messaggio di avviso e selezionare *attiva SSO*.
+
Il Single Sign-on è ora attivato. Viene visualizzata la pagina Single Sign-on (accesso singolo) che ora include i dettagli relativi all'SSO appena configurato.

. Per modificare la configurazione, selezionare *Modifica*.
. Per disattivare l'accesso singolo, selezionare *Disabilita SSO*.



TIP: Se si utilizza il portale di Azure e si accede a StorageGRID dallo stesso computer utilizzato per accedere a Entra ID, assicurarsi che l'utente del portale di Azure sia anche un utente StorageGRID autorizzato (un utente in un gruppo federato importato in StorageGRID o disconnesso dal portale di Azure prima di tentare l'accesso a StorageGRID.
