---
permalink: admin/creating-enterprise-application-entra-id.html 
sidebar: sidebar 
keywords: enterprise application, entra id, single sign on, sso 
summary: 'Puoi utilizzare Entra ID per creare un"applicazione aziendale per ogni nodo amministrativo del tuo sistema.' 
---
= Crea applicazioni aziendali in Entra ID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi utilizzare Entra ID per creare un'applicazione aziendale per ogni nodo amministrativo del tuo sistema.

.Prima di iniziare
* Hai iniziato a configurare l'accesso Single Sign-On per StorageGRID e hai selezionato *Entra ID* come tipo di SSO.
* Hailink:../admin/configure-sso.html#enter-sandbox-mode["entrato in modalità sandbox"] in Grid Manager.
* Per ogni nodo amministrativo del sistema è disponibile il *nome dell'applicazione aziendale*.  È possibile copiare questi valori dalla tabella dei dettagli del nodo di amministrazione nella pagina Configura SSO.
+

NOTE: È necessario creare un'applicazione aziendale per ciascun nodo amministratore nel sistema StorageGRID. La disponibilità di un'applicazione aziendale per ciascun nodo di amministrazione garantisce che gli utenti possano accedere e uscire in modo sicuro da qualsiasi nodo di amministrazione.

* Hai esperienza nella creazione di applicazioni aziendali in Entra ID.
* Hai un account Entra ID con un abbonamento attivo.
* Nell'account Entra ID ricopri uno dei seguenti ruoli: Amministratore globale, Amministratore dell'applicazione cloud, Amministratore dell'applicazione o proprietario del servizio principale.




== Accedi Entra ID

.Fasi
. Accedere a https://portal.azure.com["Portale Azure"^].
. Vai a https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade["Entra ID"^] .
. Selezionare https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/Overview/menuId/["Applicazioni aziendali"^].




== Creare applicazioni aziendali e salvare la configurazione SSO di StorageGRID

Per salvare la configurazione SSO per Entra ID in StorageGRID, è necessario utilizzare Entra ID per creare un'applicazione aziendale per ciascun nodo di amministrazione.  Copia gli URL dei metadati della federazione dall'ID Entra e incollali nei campi *URL metadati della federazione* corrispondenti nella pagina Configura SSO.

.Fasi
. Ripetere i passaggi seguenti per ciascun nodo di amministrazione.
+
.. Nel riquadro Applicazioni aziendali Entra ID, selezionare *Nuova applicazione*.
.. Selezionare *Crea la tua applicazione*.
.. Per il nome, inserisci il *Nome dell'applicazione aziendale* che hai copiato dalla tabella dei dettagli del nodo di amministrazione nella pagina Configura SSO.
.. Lasciare selezionato il pulsante di opzione *integra qualsiasi altra applicazione che non trovi nella galleria (non-gallery)*.
.. Selezionare *Crea*.
.. Selezionare il collegamento *Get Started* nel campo *2. Impostare la casella Single Sign on* (accesso singolo) oppure selezionare il collegamento *Single Sign-on* (accesso singolo) nel margine sinistro.
.. Selezionare la casella *SAML*.
.. Copiare l'URL * dei metadati dell'App Federation, disponibile nella sezione *fase 3 certificato di firma SAML*.
.. Vai alla pagina Configura SSO e incolla l'URL nel campo *URL metadati federazione* che corrisponde al *Nome applicazione aziendale* utilizzato.


. Dopo aver incollato un URL dei metadati della federazione per ciascun nodo di amministrazione e aver apportato tutte le altre modifiche necessarie alla configurazione SSO, seleziona *Salva* nella pagina Configura SSO.




== Scarica i metadati SAML per ogni nodo di amministrazione

Una volta salvata la configurazione SSO, è possibile scaricare un file di metadati SAML per ciascun nodo amministratore nel sistema StorageGRID.

.Fasi
. Ripetere questi passaggi per ciascun nodo di amministrazione.
+
.. Accedere a StorageGRID dal nodo di amministrazione.
.. Selezionare *Configurazione* > *Controllo accessi* > *Single sign-on*.
.. Selezionare il pulsante per scaricare i metadati SAML per il nodo di amministrazione.
.. Salva il file che caricherai in Entra ID.






== Carica i metadati SAML in ogni applicazione aziendale

Dopo aver scaricato un file di metadati SAML per ciascun nodo di amministrazione StorageGRID , eseguire i seguenti passaggi in Entra ID:

.Fasi
. Tornare al portale Azure.
. Ripetere questi passaggi per ogni applicazione aziendale:
+

NOTE: Potrebbe essere necessario aggiornare la pagina Enterprise Applications (applicazioni aziendali) per visualizzare le applicazioni aggiunte in precedenza nell'elenco.

+
.. Accedere alla pagina Proprietà dell'applicazione aziendale.
.. Impostare *assegnazione richiesta* su *No* (a meno che non si desideri configurare separatamente le assegnazioni).
.. Vai alla pagina Single Sign-on.
.. Completare la configurazione SAML.
.. Selezionare il pulsante *carica file di metadati* e selezionare il file di metadati SAML scaricato per il nodo di amministrazione corrispondente.
.. Una volta caricato il file, selezionare *Salva*, quindi selezionare *X* per chiudere il riquadro. Viene visualizzata nuovamente la pagina Set up Single Sign-on with SAML (Configura Single Sign-on con SAML).


. link:../admin/configure-sso.html#test-sso["Testare ogni applicazione"] .

