---
permalink: admin/creating-enterprise-application-entra-id.html 
sidebar: sidebar 
keywords: enterprise application, entra id, single sign on, sso 
summary: 'Si utilizza Entra ID per creare un"applicazione aziendale per ogni nodo amministrativo nel sistema.' 
---
= Creare applicazioni aziendali in Entra ID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utilizza Entra ID per creare un'applicazione aziendale per ogni nodo amministrativo nel sistema.

.Prima di iniziare
* È stata avviata la configurazione del single sign-on per StorageGRID ed è stato selezionato *Entra ID* come tipo di SSO.
* link:../admin/configure-sso.html#enter-sandbox-mode["è stata attivata la modalità sandbox"]In Grid Manager.
* Si dispone del nome dell'applicazione aziendale* per ciascun nodo di amministrazione nel sistema. È possibile copiare questi valori dalla tabella dei dettagli del nodo amministrativo nella pagina Configura SSO.
+

NOTE: È necessario creare un'applicazione aziendale per ciascun nodo amministratore nel sistema StorageGRID. La disponibilità di un'applicazione aziendale per ciascun nodo di amministrazione garantisce che gli utenti possano accedere e uscire in modo sicuro da qualsiasi nodo di amministrazione.

* Hai esperienza nella creazione di applicazioni aziendali in Entra ID.
* Hai un account Azure con un abbonamento attivo.
* Nell'account Entra ID è presente uno dei seguenti ruoli: Global Administrator, Cloud Application Administrator, Application Administrator o proprietario dell'entità del servizio.




== Accedere a Entra ID

.Fasi
. Accedere a https://portal.azure.com["Portale Azure"^].
. Passare a https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade["ID entra"^].
. Selezionare https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/Overview/menuId/["Applicazioni aziendali"^].




== Creare applicazioni aziendali e salvare la configurazione SSO di StorageGRID

Per salvare la configurazione SSO per Entra ID in StorageGRID, è necessario utilizzare Entra ID per creare un'applicazione aziendale per ogni nodo amministrativo. Copierete gli URL dei metadati della federazione da Entra ID e li incollerete nei corrispondenti campi *Federation metadata URL* della pagina Configura SSO.

.Fasi
. Ripetere i passaggi seguenti per ciascun nodo di amministrazione.
+
.. Nel riquadro Entra ID Enterprise Applications, selezionare *Nuova applicazione*.
.. Selezionare *Crea la tua applicazione*.
.. Per il nome, immettere il nome dell'applicazione *Enterprise* copiato dalla tabella dei dettagli del nodo amministrativo nella pagina Configura SSO.
.. Lasciare selezionato il pulsante di opzione *integra qualsiasi altra applicazione che non trovi nella galleria (non-gallery)*.
.. Selezionare *Crea*.
.. Selezionare il collegamento *Get Started* nel campo *2. Impostare la casella Single Sign on* (accesso singolo) oppure selezionare il collegamento *Single Sign-on* (accesso singolo) nel margine sinistro.
.. Selezionare la casella *SAML*.
.. Copiare l'URL * dei metadati dell'App Federation, disponibile nella sezione *fase 3 certificato di firma SAML*.
.. Accedere alla pagina Configura SSO e incollare l'URL nel campo *Federation metadata URL* corrispondente al nome *Enterprise application* utilizzato.


. Dopo aver incollato un URL dei metadati di federazione per ogni nodo amministrativo e aver apportato tutte le altre modifiche necessarie alla configurazione SSO, selezionare *Salva* nella pagina Configura SSO.




== Scarica i metadati SAML per ogni nodo di amministrazione

Una volta salvata la configurazione SSO, è possibile scaricare un file di metadati SAML per ciascun nodo amministratore nel sistema StorageGRID.

.Fasi
. Ripetere questi passaggi per ciascun nodo di amministrazione.
+
.. Accedere a StorageGRID dal nodo di amministrazione.
.. Selezionare *CONFIGURATION* > *Access control* > *Single Sign-on*.
.. Selezionare il pulsante per scaricare i metadati SAML per il nodo di amministrazione.
.. Salvare il file che verrà caricato in Entra ID.






== Carica i metadati SAML in ogni applicazione aziendale

Dopo aver scaricato un file di metadati SAML per ogni nodo amministrativo StorageGRID, eseguire i seguenti passaggi in Entra ID:

.Fasi
. Tornare al portale Azure.
. Ripetere questi passaggi per ogni applicazione aziendale:
+

NOTE: Potrebbe essere necessario aggiornare la pagina Enterprise Applications (applicazioni aziendali) per visualizzare le applicazioni aggiunte in precedenza nell'elenco.

+
.. Accedere alla pagina Proprietà dell'applicazione aziendale.
.. Impostare *assegnazione richiesta* su *No* (a meno che non si desideri configurare separatamente le assegnazioni).
.. Vai alla pagina Single Sign-on.
.. Completare la configurazione SAML.
.. Selezionare il pulsante *carica file di metadati* e selezionare il file di metadati SAML scaricato per il nodo di amministrazione corrispondente.
.. Una volta caricato il file, selezionare *Salva*, quindi selezionare *X* per chiudere il riquadro. Viene visualizzata nuovamente la pagina Set up Single Sign-on with SAML (Configura Single Sign-on con SAML).


. link:../admin/configure-sso.html#test-sso["Testare ogni applicazione"].

