---
permalink: admin/creating-traffic-classification-policies.html 
sidebar: sidebar 
keywords: traffic classification, network traffic, traffic limits, policy 
summary: È possibile creare criteri di classificazione del traffico se si desidera monitorare e, facoltativamente, limitare il traffico di rete per bucket, tenant, subnet IP o endpoint del bilanciamento del carico. Facoltativamente, è possibile impostare limiti per una policy in base alla larghezza di banda, al numero di richieste simultanee o alla velocità di richiesta. 
---
= Creare policy di classificazione del traffico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare policy di classificazione del traffico se si desidera monitorare e, facoltativamente, limitare il traffico di rete per bucket, bucket regex, CIDR, endpoint del bilanciamento del carico o tenant. Facoltativamente, è possibile impostare limiti per una policy in base alla larghezza di banda, al numero di richieste simultanee o alla velocità di richiesta.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone di link:admin-group-permissions.html["Autorizzazione di accesso root"].
* Sono stati creati endpoint di bilanciamento del carico che si desidera associare.
* Hai creato i tenant che desideri abbinare.


.Fasi
. Selezionare *CONFIGURAZIONE* > *rete* > *classificazione del traffico*.
. Selezionare *Crea*.
. Inserire un nome e una descrizione (opzionale) per la policy e selezionare *continua*.
+
Ad esempio, descrivi a cosa si applica questa policy di classificazione del traffico e a cosa limiterà.

. Selezionare *Aggiungi regola* e specificare i seguenti dettagli per creare una o più regole corrispondenti per il criterio. I criteri creati devono avere almeno una regola corrispondente. Selezionare *continua*.
+
[cols="1a,3a"]
|===
| Campo | Descrizione 


 a| 
Tipo
 a| 
Selezionare i tipi di traffico a cui si applica la regola corrispondente. I tipi di traffico sono bucket, bucket regex, CIDR, endpoint del bilanciamento del carico e tenant.



 a| 
Valore corrispondente
 a| 
Inserire il valore corrispondente al tipo selezionato.

** Bucket: Immettere uno o più nomi di bucket.
** Secchio regex: Immettere una o più espressioni regolari utilizzate per far corrispondere un insieme di nomi di bucket.
+
L'espressione regolare non è ancorata. USA l'ancora ^ per trovare la corrispondenza all'inizio del nome del bucket e usa l'ancora per la corrispondenza alla fine del nome. La corrispondenza delle espressioni regolari supporta un sottoinsieme della sintassi PCRE (Perl Compatible Regular Expression).

** CIDR: Inserire una o più subnet IPv4, nella notazione CIDR, che corrispondono alla subnet desiderata.
** Endpoint del bilanciamento del carico: Selezionare il nome di un endpoint. Questi sono gli endpoint del bilanciamento del carico definiti in link:../admin/configuring-load-balancer-endpoints.html["Configurare gli endpoint del bilanciamento del carico"].
** Tenant: Il tenant matching utilizza l'ID della chiave di accesso. Se la richiesta non contiene un ID della chiave di accesso (ad esempio, l'accesso anonimo), viene utilizzata la proprietà del bucket a cui si accede per determinare il tenant.




 a| 
Corrispondenza inversa
 a| 
Se si desidera far corrispondere tutto il traffico di rete _tranne_ coerente con il valore Type and Match appena definito, selezionare la casella di controllo *Inverse Match* (corrispondenza inversa). In caso contrario, lasciare deselezionata la casella di controllo.

Ad esempio, se si desidera applicare questo criterio a tutti gli endpoint del bilanciamento del carico tranne uno, specificare l'endpoint del bilanciamento del carico da escludere e selezionare *corrispondenza inversa*.

Per un criterio contenente più adattatori in cui almeno uno è un adattatore inverso, fare attenzione a non creare un criterio che corrisponda a tutte le richieste.

|===
. Facoltativamente, selezionare *Aggiungi un limite* e selezionare i seguenti dettagli per aggiungere uno o più limiti per controllare il traffico di rete associato a una regola.
+

NOTE: StorageGRID raccoglie le metriche anche se non si aggiungono limiti, in modo da poter comprendere le tendenze del traffico.

+
[cols="1a,3a"]
|===
| Campo | Descrizione 


 a| 
Tipo
 a| 
Il tipo di limite che si desidera applicare al traffico di rete associato alla regola. Ad esempio, è possibile limitare la larghezza di banda o il tasso di richiesta.

*Nota*: È possibile creare policy per limitare la larghezza di banda aggregata o per limitare la larghezza di banda per richiesta. Tuttavia, StorageGRID non può limitare entrambi i tipi di larghezza di banda contemporaneamente. Quando la larghezza di banda aggregata è in uso, la larghezza di banda per richiesta non è disponibile. Al contrario, quando viene utilizzata la larghezza di banda per richiesta, la larghezza di banda aggregata non è disponibile. I limiti di larghezza di banda aggregati potrebbero imporre un ulteriore impatto minore sulle performance sul traffico non limitato.

Per i limiti di larghezza di banda, StorageGRID applica la policy che meglio corrisponde al tipo di limite impostato. Ad esempio, se si dispone di una policy che limita il traffico in una sola direzione, il traffico nella direzione opposta sarà illimitato, anche se il traffico corrisponde a criteri aggiuntivi con limiti di larghezza di banda. StorageGRID implementa le corrispondenze "migliori" per i limiti di larghezza di banda nel seguente ordine:

** Indirizzo IP esatto (/32 mask)
** Nome esatto del bucket
** Regex. Bucket
** Tenant
** Endpoint
** Corrispondenze CIDR non esatte (non /32)
** Corrispondenze inverse




 a| 
Valido per
 a| 
Se questo limite si applica alle richieste di lettura del client (GET o HEAD) o alle richieste di scrittura (PUT, POST o DELETE).



 a| 
Valore
 a| 
Il valore a cui il traffico di rete sarà limitato, in base all'unità selezionata. Ad esempio, immettere 10 e selezionare MiB/s per impedire che il traffico di rete associato a questa regola superi i 10 MiB/s.

*Nota*: A seconda dell'impostazione delle unità, le unità disponibili saranno binarie (ad esempio, GiB) o decimali (ad esempio, GB). Per modificare l'impostazione delle unità, selezionare l'elenco a discesa User (utente) in alto a destra in Grid Manager, quindi selezionare *User Preferences* (Preferenze utente).



 a| 
Unità
 a| 
L'unità che descrive il valore immesso.

|===
+
Ad esempio, se si desidera creare un limite di larghezza di banda di 40 GB/s per un livello SLA, creare due limiti di larghezza di banda aggregati: GET/HEAD a 40 GB/s e PUT/POST/DELETE a 40 GB/s.

. Selezionare *continua*.
. Leggere e rivedere la policy di classificazione del traffico. Utilizzare il pulsante *precedente* per tornare indietro e apportare le modifiche necessarie. Quando si è soddisfatti della policy, selezionare *Salva e continua*.
+
Il traffico client S3 viene ora gestito in base alla politica di classificazione del traffico.



.Al termine
link:viewing-network-traffic-metrics.html["Visualizzare le metriche del traffico di rete"] per verificare che i criteri applichino i limiti di traffico previsti.
