---
permalink: admin/creating-enterprise-application-azure.html 
sidebar: sidebar 
keywords: enterprise application, azure ad, single sign on, sso 
summary: 'Azure ad consente di creare un"applicazione aziendale per ciascun nodo di amministrazione del sistema.' 
---
= Creare applicazioni aziendali in Azure ad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Azure ad consente di creare un'applicazione aziendale per ciascun nodo di amministrazione del sistema.

.Prima di iniziare
* È stata avviata la configurazione del single sign-on per StorageGRID ed è stato selezionato *Azure* come tipo di SSO.
* *La modalità Sandbox* è selezionata nella pagina Single Sign-on di Grid Manager. Vedere link:../admin/using-sandbox-mode.html["USA la modalità sandbox"].
* Si dispone del nome dell'applicazione aziendale* per ciascun nodo di amministrazione nel sistema. È possibile copiare questi valori dalla tabella Dettagli nodo amministratore nella pagina accesso singolo StorageGRID.
+

NOTE: È necessario creare un'applicazione aziendale per ciascun nodo amministratore nel sistema StorageGRID. La disponibilità di un'applicazione aziendale per ciascun nodo di amministrazione garantisce che gli utenti possano accedere e uscire in modo sicuro da qualsiasi nodo di amministrazione.

* Hai esperienza nella creazione di applicazioni aziendali in Azure Active Directory.
* Hai un account Azure con un abbonamento attivo.
* Nell'account Azure hai uno dei seguenti ruoli: Amministratore globale, amministratore dell'applicazione cloud, amministratore dell'applicazione o proprietario del service principal.




== Accedere ad Azure ad

.Fasi
. Accedere a https://portal.azure.com["Portale Azure"^].
. Passare a https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade["Azure Active Directory"^].
. Selezionare https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/Overview/menuId/["Applicazioni aziendali"^].




== Creare applicazioni aziendali e salvare la configurazione SSO di StorageGRID

Per salvare la configurazione SSO per Azure in StorageGRID, è necessario utilizzare Azure per creare un'applicazione aziendale per ciascun nodo di amministrazione. Copiare gli URL dei metadati della federazione da Azure e incollarli nei corrispondenti campi *URL metadati federazione* nella pagina di accesso singolo di StorageGRID.

.Fasi
. Ripetere i passaggi seguenti per ciascun nodo di amministrazione.
+
.. Nel riquadro Azure Enterprise Applications (applicazioni aziendali Azure), selezionare *New application* (Nuova applicazione).
.. Selezionare *Crea la tua applicazione*.
.. Per il nome, inserire il nome dell'applicazione aziendale copiato dalla tabella dei dettagli del nodo amministrativo nella pagina accesso singolo StorageGRID.
.. Lasciare selezionato il pulsante di opzione *integra qualsiasi altra applicazione che non trovi nella galleria (non-gallery)*.
.. Selezionare *Crea*.
.. Selezionare il collegamento *Get Started* nel campo *2. Impostare la casella Single Sign on* (accesso singolo) oppure selezionare il collegamento *Single Sign-on* (accesso singolo) nel margine sinistro.
.. Selezionare la casella *SAML*.
.. Copiare l'URL * dei metadati dell'App Federation, disponibile nella sezione *fase 3 certificato di firma SAML*.
.. Accedere alla pagina Single Sign-on di StorageGRID e incollare l'URL nel campo *Federation metadata URL* che corrisponde al *nome dell'applicazione aziendale* utilizzato.


. Dopo aver incollato un URL dei metadati della federazione per ciascun nodo amministratore e aver apportato tutte le altre modifiche necessarie alla configurazione SSO, selezionare *Salva* nella pagina accesso singolo StorageGRID.




== Scarica i metadati SAML per ogni nodo di amministrazione

Una volta salvata la configurazione SSO, è possibile scaricare un file di metadati SAML per ciascun nodo amministratore nel sistema StorageGRID.

.Fasi
. Ripetere questi passaggi per ciascun nodo di amministrazione.
+
.. Accedere a StorageGRID dal nodo di amministrazione.
.. Selezionare *CONFIGURATION* > *Access control* > *Single Sign-on*.
.. Selezionare il pulsante per scaricare i metadati SAML per il nodo di amministrazione.
.. Salvare il file che verrà caricato in Azure ad.






== Carica i metadati SAML in ogni applicazione aziendale

Dopo aver scaricato un file di metadati SAML per ciascun nodo amministrativo StorageGRID, eseguire la seguente procedura in Azure ad:

.Fasi
. Tornare al portale Azure.
. Ripetere questi passaggi per ogni applicazione aziendale:
+

NOTE: Potrebbe essere necessario aggiornare la pagina Enterprise Applications (applicazioni aziendali) per visualizzare le applicazioni aggiunte in precedenza nell'elenco.

+
.. Accedere alla pagina Proprietà dell'applicazione aziendale.
.. Impostare *assegnazione richiesta* su *No* (a meno che non si desideri configurare separatamente le assegnazioni).
.. Vai alla pagina Single Sign-on.
.. Completare la configurazione SAML.
.. Selezionare il pulsante *carica file di metadati* e selezionare il file di metadati SAML scaricato per il nodo di amministrazione corrispondente.
.. Una volta caricato il file, selezionare *Salva*, quindi selezionare *X* per chiudere il riquadro. Viene visualizzata nuovamente la pagina Set up Single Sign-on with SAML (Configura Single Sign-on con SAML).


. Seguire i passaggi descritti in link:../admin/using-sandbox-mode.html["USA la modalità sandbox"] per testare ciascuna applicazione.

