---
permalink: admin/how-sso-works.html 
sidebar: sidebar 
keywords: single sign on, sso, SAML 
summary: 'Quando è abilitato l"accesso Single Sign-On (SSO), gli utenti possono accedere a Grid Manager, Tenant Manager, Grid Management API o Tenant Management API solo se le loro credenziali sono autorizzate tramite il processo di accesso SSO implementato dalla tua organizzazione.  Gli utenti locali non possono accedere a StorageGRID.' 
---
= Come funziona SSO
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando è abilitato l'accesso Single Sign-On (SSO), gli utenti possono accedere a Grid Manager, Tenant Manager, Grid Management API o Tenant Management API solo se le loro credenziali sono autorizzate tramite il processo di accesso SSO implementato dalla tua organizzazione.  Gli utenti locali non possono accedere a StorageGRID.

Il sistema StorageGRID supporta SSO (Single Sign-on) utilizzando lo standard SAML 2.0 (Security Assertion Markup Language 2.0).

Prima di attivare SSO (Single Sign-on), esaminare in che modo i processi di accesso e disconnessione di StorageGRID vengono influenzati quando SSO è attivato.



== Effettuare l'accesso quando SSO è attivato

Quando SSO è attivato e si accede a StorageGRID, si viene reindirizzati alla pagina SSO dell'organizzazione per convalidare le credenziali.

.Fasi
. Immettere il nome di dominio completo o l'indirizzo IP di qualsiasi nodo di amministrazione StorageGRID in un browser Web.
+
Viene visualizzata la pagina di accesso a StorageGRID.

+
** Se è la prima volta che accedi all'URL su questo browser, ti verrà richiesto un ID account.
** Se hai già effettuato l'accesso a Grid Manager o Tenant Manager, ti verrà chiesto di selezionare un account recente o di immettere un ID account.
+

NOTE: La pagina di accesso a StorageGRID non viene visualizzata quando si immette l'URL completo per un account tenant (ovvero un nome di dominio completo o un indirizzo IP seguito da `/?accountId=_20-digit-account-id_`). Al contrario, l'utente viene immediatamente reindirizzato alla pagina di accesso SSO dell'organizzazione, in cui è possibile <<signin_sso,Accedi con le tue credenziali SSO>>.



. Indicare se si desidera accedere a Grid Manager o al tenant Manager:
+
** Per accedere a Grid Manager, lasciare vuoto il campo *ID account*, inserire *0* come ID account o selezionare *Grid Manager* se compare nell'elenco degli account recenti.
** Per accedere al tenant Manager, inserire l'ID account tenant di 20 cifre o selezionare un tenant in base al nome, se visualizzato nell'elenco degli account recenti.


. Selezionare *Accedi*
+
StorageGRID reindirizza l'utente alla pagina di accesso SSO della propria organizzazione. Ad esempio:

. [[signin_sso]]Accedi con le tue credenziali SSO.
+
Se le credenziali SSO sono corrette:

+
.. Il provider di identità (IdP) fornisce una risposta di autenticazione a StorageGRID.
.. StorageGRID convalida la risposta di autenticazione.
.. Se la risposta è valida e l'utente appartiene a un gruppo federato con autorizzazioni di accesso StorageGRID, l'utente ha effettuato l'accesso a Gestione griglia o a Gestione tenant, a seconda dell'account selezionato.
+

NOTE: Se l'account del servizio non è accessibile, è comunque possibile effettuare l'accesso, purché si sia un utente esistente che appartiene a un gruppo federato con autorizzazioni di accesso StorageGRID.



. Se si dispone di autorizzazioni adeguate, è possibile accedere ad altri nodi di amministrazione o a Grid Manager o Tenant Manager.
+
Non è necessario immettere nuovamente le credenziali SSO.





== Disconnettersi quando SSO è attivato

Quando SSO è abilitato per StorageGRID, ciò che accade quando si effettua la disconnessione dipende da ciò che si effettua l'accesso e da dove si effettua la disconnessione.

.Fasi
. Individuare il collegamento *Disconnetti* nell'angolo in alto a destra dell'interfaccia utente.
. Selezionare *Disconnetti*.
+
Viene visualizzata la pagina di accesso a StorageGRID. Il menu a discesa *Recent Accounts* (account recenti) viene aggiornato per includere *Grid Manager* o il nome del tenant, in modo da poter accedere a queste interfacce utente più rapidamente in futuro.

+

TIP: La tabella riassume ciò che accade quando si effettua la disconnessione se si utilizza una singola sessione del browser. Se hai effettuato l'accesso a StorageGRID in più sessioni del browser, devi disconnetterti separatamente da tutte le sessioni del browser.

+
[cols="1a,1a,1a"]
|===
| Se hai effettuato l'accesso a... | E ti disconnetterai da... | Sei disconnesso da... 


 a| 
Grid Manager su uno o più nodi di amministrazione
 a| 
Grid Manager su qualsiasi nodo di amministrazione
 a| 
Grid Manager su tutti i nodi di amministrazione

*Nota:* se si utilizza l'ID Entra per SSO, potrebbero essere necessari alcuni minuti per uscire da tutti i nodi amministrativi.



 a| 
Tenant Manager su uno o più nodi di amministrazione
 a| 
Tenant Manager su qualsiasi nodo di amministrazione
 a| 
Tenant Manager su tutti i nodi di amministrazione



 a| 
Sia Grid Manager che tenant Manager
 a| 
Grid Manager
 a| 
Solo Grid Manager. Per disconnettersi da SSO, devi anche disconnetterti da Tenant Manager.



 a| 
Manager tenant
 a| 
Solo il tenant manager. Per disconnettersi da SSO, è inoltre necessario disconnettersi da Grid Manager.

|===

