---
permalink: admin/increasing-metadata-reserved-space-setting.html 
sidebar: sidebar 
keywords: increase metadata reserved space setting 
summary: 'È possibile aumentare l"impostazione del sistema spazio riservato metadati se i nodi di archiviazione soddisfano requisiti specifici per la RAM e lo spazio disponibile.' 
---
= Aumentare l'impostazione spazio riservato metadati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aumentare l'impostazione del sistema spazio riservato metadati se i nodi di archiviazione soddisfano requisiti specifici per la RAM e lo spazio disponibile.

.Di cosa hai bisogno
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:web-browser-requirements.html["browser web supportato"].
* Si dispone di link:admin-group-permissions.html["Autorizzazione di accesso root o configurazione pagina topologia griglia e altre autorizzazioni di configurazione griglia"].



NOTE: La pagina della topologia della griglia è stata obsoleta e verrà rimossa in una versione futura.

.A proposito di questa attività
Potrebbe essere possibile aumentare manualmente l'impostazione dello spazio riservato dei metadati a livello di sistema fino a 8 TB.

È possibile aumentare il valore dell'impostazione spazio riservato metadati a livello di sistema solo se entrambe le istruzioni sono vere:

* I nodi di storage di qualsiasi sito del sistema dispongono ciascuno di almeno 128 GB di RAM.
* I nodi di storage di qualsiasi sito del sistema dispongono ciascuno di spazio disponibile sufficiente sul volume di storage 0.


Se si aumenta questa impostazione, si riduce contemporaneamente lo spazio disponibile per lo storage a oggetti sul volume di storage 0 di tutti i nodi di storage. Per questo motivo, potrebbe essere preferibile impostare Metadata Reserved Space su un valore inferiore a 8 TB, in base ai requisiti previsti per i metadati degli oggetti.


NOTE: In generale, è meglio utilizzare un valore più alto invece di un valore più basso. Se l'impostazione spazio riservato metadati è troppo grande, è possibile ridurla in un secondo momento. Al contrario, se si aumenta il valore in un secondo momento, il sistema potrebbe dover spostare i dati dell'oggetto per liberare spazio.

Per una spiegazione dettagliata del modo in cui l'impostazione spazio riservato metadati influisce sullo spazio consentito per l'archiviazione dei metadati dell'oggetto su un nodo di archiviazione specifico, vedere link:managing-object-metadata-storage.html["Gestire lo storage dei metadati degli oggetti"].

.Fasi
. Determinare l'impostazione corrente di Metadata Reserved Space.
+
.. Selezionare *CONFIGURAZIONE* > *sistema* > *Impostazioni archiviazione*.
.. Annotare il valore di *spazio riservato metadati*.


. Assicurarsi di disporre di spazio disponibile sufficiente sul volume di storage 0 di ciascun nodo di storage per aumentare questo valore.
+
.. Selezionare *NODI*.
.. Selezionare il primo nodo di storage nella griglia.
.. Selezionare la scheda Storage (archiviazione).
.. Nella sezione Volumes (volumi), individuare la voce */var/local/rangedb/0*.
.. Verificare che il valore disponibile sia uguale o superiore alla differenza tra il nuovo valore che si desidera utilizzare e il valore corrente dello spazio riservato dei metadati.
+
Ad esempio, se l'impostazione spazio riservato metadati è attualmente di 4 TB e si desidera aumentarla a 6 TB, il valore disponibile deve essere pari o superiore a 2 TB.

.. Ripetere questi passaggi per tutti i nodi di storage.
+
*** Se uno o più nodi di storage non dispongono di spazio disponibile sufficiente, non è possibile aumentare il valore Metadata Reserved Space (spazio riservato metadati). Non continuare con questa procedura.
*** Se ogni nodo di storage dispone di spazio disponibile sufficiente sul volume 0, passare alla fase successiva.




. Assicurarsi di disporre di almeno 128 GB di RAM su ciascun nodo di storage.
+
.. Selezionare *NODI*.
.. Selezionare il primo nodo di storage nella griglia.
.. Selezionare la scheda *hardware*.
.. Posizionare il cursore del mouse sul grafico utilizzo memoria. Assicurarsi che la memoria totale sia di almeno 128 GB.
.. Ripetere questi passaggi per tutti i nodi di storage.
+
*** Se uno o più nodi di storage non dispongono di memoria totale sufficiente, non è possibile aumentare il valore Metadata Reserved Space (spazio riservato metadati). Non continuare con questa procedura.
*** Se ciascun nodo di storage dispone di almeno 128 GB di memoria totale, passare alla fase successiva.




. Aggiornare l'impostazione Metadata Reserved Space (spazio riservato metadati).
+
.. Selezionare *CONFIGURAZIONE* > *sistema* > *Impostazioni archiviazione*.
.. Selezionare *spazio riservato metadati*.
.. Inserire il nuovo valore.
+
Ad esempio, per inserire 8 TB, che è il valore massimo supportato, inserire *8000000000000* (8, seguito da 12 zeri)

.. Selezionare *Salva*.



