---
permalink: admin/manually-triggering-autosupport-message.html 
sidebar: sidebar 
keywords: autosupport, how to send asup message 
summary: 'Per assistere il supporto tecnico nella risoluzione dei problemi del sistema StorageGRID, è possibile attivare manualmente l"invio di un pacchetto AutoSupport.' 
---
= Attivare manualmente un pacchetto AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per assistere il supporto tecnico nella risoluzione dei problemi del sistema StorageGRID, è possibile attivare manualmente l'invio di un pacchetto AutoSupport.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone dell'autorizzazione di accesso root o di altra configurazione della griglia.


.Fasi
. Selezionare *SUPPORTO* > *Strumenti* > *AutoSupport*.
. Nella scheda *azioni*, selezionare *Invia AutoSupport* attivato dall'utente.
+
StorageGRID tenta di inviare un pacchetto AutoSupport al sito di supporto NetApp. Se il tentativo ha esito positivo, i valori *risultato più recente* e *tempo ultimo successo* nella scheda *risultati* vengono aggiornati. Se si verifica un problema, il valore *risultato più recente* viene aggiornato a "non riuscito" e StorageGRID non tenta di inviare nuovamente il pacchetto AutoSupport.

. Dopo 1 minuto, aggiornare la pagina AutoSupport nel browser per accedere ai risultati più recenti.



TIP: Inoltre, è possibile link:../monitor/collecting-log-files-and-system-data.html["raccolta di file di registro e dati di sistema più estesi"]inviarli al sito di assistenza NetApp.
