---
permalink: admin/manually-triggering-autosupport-message.html 
sidebar: sidebar 
keywords: autosupport, how to send asup message 
summary: 'Per assistere il supporto tecnico nella risoluzione dei problemi del sistema StorageGRID, è possibile attivare manualmente l"invio di un pacchetto AutoSupport.' 
---
= Attivare manualmente un pacchetto AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per assistere il supporto tecnico nella risoluzione dei problemi del sistema StorageGRID, è possibile attivare manualmente l'invio di un pacchetto AutoSupport.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Hai l'autorizzazione di accesso Root o di altra configurazione della griglia.


.Fasi
. Selezionare *Supporto* > *Strumenti* > * AutoSupport*.
. Nella scheda *azioni*, selezionare *Invia AutoSupport* attivato dall'utente.
+
StorageGRID tenta di inviare un pacchetto AutoSupport al sito di supporto NetApp .  Se il tentativo ha esito positivo, i valori *Risultato più recente* e *Ultima volta riuscita* nella scheda *Risultati* vengono aggiornati.  Se si verifica un problema, il valore *Risultato più recente* viene aggiornato in "Non riuscito" e StorageGRID non tenta più di inviare il pacchetto AutoSupport .

. Dopo 1 minuto, aggiorna la pagina AutoSupport nel tuo browser per accedere ai risultati più recenti.



TIP: Inoltre, puoilink:../monitor/collecting-log-files-and-system-data.html["raccogliere file di registro e dati di sistema più estesi"] e inviarli al sito di supporto NetApp .
