---
permalink: admin/manually-triggering-autosupport-message.html 
sidebar: sidebar 
keywords: autosupport, how to send asup message 
summary: 'Per assistere il supporto tecnico nella risoluzione dei problemi del sistema StorageGRID, è possibile attivare manualmente l"invio di un pacchetto AutoSupport.' 
---
= Attivare manualmente un pacchetto AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per assistere il supporto tecnico nella risoluzione dei problemi del sistema StorageGRID, è possibile attivare manualmente l'invio di un pacchetto AutoSupport.

.Prima di iniziare
* È necessario accedere a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* È necessario disporre dell'autorizzazione di accesso root o di altra configurazione della griglia.


.Fasi
. Selezionare *SUPPORTO* > *Strumenti* > *AutoSupport*.
. Nella scheda *azioni*, selezionare *Invia AutoSupport* attivato dall'utente.
+
StorageGRID tenta di inviare un pacchetto AutoSupport al sito di supporto NetApp. Se il tentativo ha esito positivo, i valori *risultato più recente* e *tempo ultimo successo* nella scheda *risultati* vengono aggiornati. Se si verifica un problema, il valore *risultato più recente* viene aggiornato a "non riuscito" e StorageGRID non tenta di inviare nuovamente il pacchetto AutoSupport.

+

TIP: Dopo aver inviato un pacchetto AutoSupport attivato dall'utente, aggiornare la pagina AutoSupport nel browser dopo 1 minuto per accedere ai risultati più recenti.


