---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: 'Per memorizzare o recuperare oggetti, le applicazioni client S3 si connettono al servizio Load Balancer, incluso in tutti i nodi Admin e Gateway, o al servizio Local Distribution Router (LDR), incluso in tutti i nodi Storage.' 
---
= Riepilogo: Indirizzi IP e porte per le connessioni client
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per memorizzare o recuperare oggetti, le applicazioni client S3 si connettono al servizio Load Balancer, incluso in tutti i nodi Admin e Gateway, o al servizio Local Distribution Router (LDR), incluso in tutti i nodi Storage.

Le applicazioni client possono connettersi a StorageGRID utilizzando l'indirizzo IP di un nodo Grid e il numero di porta del servizio su tale nodo. Facoltativamente, è possibile creare gruppi ad alta disponibilità (ha) di nodi di bilanciamento del carico per fornire connessioni ad alta disponibilità che utilizzano indirizzi IP virtuali (VIP). Se si desidera connettersi a StorageGRID utilizzando un nome di dominio completo (FQDN) invece di un indirizzo IP o VIP, è possibile configurare le voci DNS.

Questa tabella riassume i diversi modi in cui i client possono connettersi a StorageGRID e gli indirizzi IP e le porte utilizzati per ciascun tipo di connessione. Se sono già stati creati endpoint di bilanciamento del carico e gruppi ha (High Availability), vedere <<Dove trovare gli indirizzi IP>> per individuare questi valori in Grid Manager.

[cols="1a,1a,1a,1a"]
|===
| Dove viene stabilita la connessione | Servizio a cui si connette il client | Indirizzo IP | Porta 


 a| 
Gruppo HA
 a| 
Bilanciamento del carico
 a| 
Indirizzo IP virtuale di un gruppo ha
 a| 
Porta assegnata all'endpoint del bilanciamento del carico



 a| 
Nodo Admin
 a| 
Bilanciamento del carico
 a| 
Indirizzo IP del nodo di amministrazione
 a| 
Porta assegnata all'endpoint del bilanciamento del carico



 a| 
Nodo gateway
 a| 
Bilanciamento del carico
 a| 
Indirizzo IP del nodo gateway
 a| 
Porta assegnata all'endpoint del bilanciamento del carico



 a| 
Nodo di storage
 a| 
LDR
 a| 
Indirizzo IP del nodo di storage
 a| 
Porte S3 predefinite:

* HTTPS: 18082
* HTTP: 18084


|===


== URL di esempio

Per connettere un'applicazione client all'endpoint Load Balancer di un gruppo ha di nodi gateway, utilizzare un URL strutturato come mostrato di seguito:

`https://_VIP-of-HA-group:LB-endpoint-port_`

Ad esempio, se l'indirizzo IP virtuale del gruppo ha è 192.0.2.5 e il numero di porta dell'endpoint del bilanciamento del carico è 10443, un'applicazione potrebbe utilizzare il seguente URL per connettersi a StorageGRID:

`\https://192.0.2.5:10443`



== Dove trovare gli indirizzi IP

. Accedere a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
. Per trovare l'indirizzo IP di un nodo Grid:
+
.. Selezionare *NODI*.
.. Selezionare il nodo Admin, il nodo gateway o il nodo di storage a cui si desidera connettersi.
.. Selezionare la scheda *Panoramica*.
.. Nella sezione Node Information (informazioni sul nodo), annotare gli indirizzi IP del nodo.
.. Selezionare *Mostra altro* per visualizzare gli indirizzi IPv6 e le mappature dell'interfaccia.
+
È possibile stabilire connessioni dalle applicazioni client a uno qualsiasi degli indirizzi IP presenti nell'elenco:

+
*** *Eth0:* Grid Network
*** *Eth1:* Admin Network (opzionale)
*** *Eth2:* rete client (opzionale)
+

NOTE: Se si sta visualizzando un nodo Admin o un nodo Gateway e si tratta del nodo attivo di un gruppo ad alta disponibilità, l'indirizzo IP virtuale del gruppo ha viene visualizzato su eth2.





. Per trovare l'indirizzo IP virtuale di un gruppo ad alta disponibilità:
+
.. Selezionare *CONFIGURATION* > *Network* > *High Availability groups*.
.. Nella tabella, annotare l'indirizzo IP virtuale del gruppo ha.


. Per trovare il numero di porta di un endpoint Load Balancer:
+
.. Selezionare *CONFIGURATION* > *Network* > *Load Balancer Endpoints*.
.. Annotare il numero di porta dell'endpoint che si desidera utilizzare.
+

NOTE: Se il numero di porta è 80 o 443, l'endpoint viene configurato solo sui nodi gateway, poiché tali porte sono riservate sui nodi Admin. Tutte le altre porte sono configurate sia sui nodi Gateway che sui nodi Admin.

.. Selezionare il nome dell'endpoint dalla tabella.
.. Verificare che il tipo *Client* (S3) corrisponda all'applicazione client che utilizzerà l'endpoint.



