---
permalink: admin/supported-ciphers-for-outgoing-tls-connections.html 
sidebar: sidebar 
keywords: tls cipher suites, transport layer security connections 
summary: 'Il sistema StorageGRID supporta un set limitato di suite di crittografia per le connessioni TLS (Transport Layer Security) ai sistemi esterni utilizzati per la federazione di identità e i pool di storage cloud.' 
---
= Crittografia supportata per le connessioni TLS in uscita
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il sistema StorageGRID supporta un set limitato di suite di crittografia per le connessioni TLS (Transport Layer Security) ai sistemi esterni utilizzati per la federazione di identità e i pool di storage cloud.



== Versioni supportate di TLS

StorageGRID supporta TLS 1.2 e TLS 1.3 per le connessioni a sistemi esterni utilizzati per la federazione delle identità e i pool di storage cloud.

I cifrari TLS supportati per l'utilizzo con sistemi esterni sono stati selezionati per garantire la compatibilità con una vasta gamma di sistemi esterni. L'elenco è più grande dell'elenco di cifrari supportati per l'uso con le applicazioni client S3. Per configurare le crittografia, andare a *CONFIGURATION* > *Security* > *Security settings* e selezionare *TLS and SSH policy*.


NOTE: Le opzioni di configurazione TLS, come versioni di protocollo, crittografia, algoritmi di scambio delle chiavi e algoritmi MAC, non sono configurabili in StorageGRID. Se hai richieste specifiche su queste impostazioni, contatta il tuo rappresentante NetApp.
