---
permalink: admin/what-is-autosupport.html 
sidebar: sidebar 
keywords: autosupport, technical support, storagegrid health, system status, Active IQ 
summary: La funzione AutoSupport consente a StorageGRID di inviare pacchetti di stato e integrità al supporto tecnico NetApp. 
---
= Che cos'è AutoSupport?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La funzione AutoSupport consente a StorageGRID di inviare pacchetti di stato e integrità al supporto tecnico NetApp.

L'utilizzo di AutoSupport può accelerare notevolmente la determinazione e la risoluzione dei problemi. Il supporto tecnico può anche monitorare le esigenze di storage del sistema e aiutare a determinare se è necessario aggiungere nuovi nodi o siti. In alternativa, è possibile configurare i pacchetti AutoSupport da inviare a una destinazione aggiuntiva.

StorageGRID dispone di due tipi di AutoSupport:

* *StorageGRID AutoSupport* segnala problemi di software StorageGRID. Attivato per impostazione predefinita quando si installa StorageGRID per la prima volta. È possibilelink:configure-autosupport-grid-manager.html["Modificare la configurazione AutoSupport predefinita"], se necessario.
+

NOTE: Se StorageGRID AutoSupport non è abilitato, viene visualizzato un messaggio sul dashboard di Gestione griglia. Il messaggio include un collegamento alla pagina di configurazione di AutoSupport. Se si chiude il messaggio, questo non viene visualizzato fino a quando la cache del browser non viene cancellata, anche se AutoSupport rimane disattivato.

* *Hardware appliance AutoSupport* segnala problemi relativi all'appliance StorageGRID. È necessario link:configure-autosupport-grid-manager.html#autosupport-for-appliances["Configura AutoSupport hardware su ogni appliance"].




== Che cos'è Active IQ?

Active IQ è un consulente digitale basato sul cloud che sfrutta l'analisi predittiva e la saggezza della community della base installata di NetApp. Le valutazioni continue dei rischi, gli avvisi predittivi, le indicazioni prescrittive e le azioni automatizzate consentono di prevenire i problemi prima che si verifichino, migliorando lo stato di salute del sistema e la disponibilità del sistema.

Se si desidera utilizzare le dashboard e le funzionalità di Active IQ nel sito di supporto NetApp, è necessario attivare AutoSupport.

https://docs.netapp.com/us-en/active-iq/index.html["Documentazione di Active IQ Digital Advisor"^]



== Informazioni incluse nel pacchetto AutoSupport

Un pacchetto AutoSupport contiene i seguenti file e dettagli.

[cols="2a,2a,3a"]
|===
| Nome del file | Campi | Descrizione 


 a| 
AUTOSUPPORT-HISTORY.XML
 a| 
Numero di sequenza AutoSupport + destinazione per questo AutoSupport + Stato di consegna + tentativi di consegna + oggetto AutoSupport + URI di consegna + ultimo errore + Nome file AutoSupport + tempo di generazione + dimensione compressa AutoSupport + dimensione decompressa AutoSupport + tempo totale di raccolta (ms)
 a| 
File di cronologia AutoSupport.



 a| 
AUTOSUPPORT.XML
 a| 
Nodo + protocollo per contattare il supporto + URL di supporto per HTTP/HTTPS + Indirizzo di supporto + Stato ondemand AutoSupport + URL server ondemand AutoSupport + intervallo di polling ondemand AutoSupport
 a| 
File di stato AutoSupport. Fornisce i dettagli del protocollo utilizzato, dell'URL e dell'indirizzo del supporto tecnico, dell'intervallo di polling e di OnDemand AutoSupport, se attivato o disattivato.



 a| 
BUCKET.XML
 a| 
ID bucket + ID account + versione build + Configurazione vincolo posizione + conformità abilitata + Configurazione conformità + blocco oggetto S3 abilitato + Configurazione blocco oggetto S3 + Configurazione coerenza + CORS abilitato + Configurazione CORS + tempo ultimo accesso abilitato + Policy abilitato + Configurazione criterio + Notifiche abilitate + Configurazione Cloud Mirror abilitato + Configurazione Cloud Mirror + Ricerca abilitata + Configurazione controllo bucket abilitato + Configurazione bucket con tag + Configurazione bucket
 a| 
Fornisce dettagli di configurazione e statistiche a livello di bucket. Esempi di configurazioni bucket includono servizi di piattaforma, conformità e coerenza dei bucket.



 a| 
GRID-CONFIGURATIONS.XML
 a| 
ID attributo + Nome attributo + valore + Indice + ID tabella + Nome tabella
 a| 
File di informazioni sulla configurazione a livello di griglia. Contiene informazioni sui certificati Grid, lo spazio riservato ai metadati, le impostazioni di configurazione a livello di griglia (conformità, blocco degli oggetti S3, compressione degli oggetti, avvisi, configurazione syslog e ILM), i dettagli del profilo di erasure coding, il nome DNS e link:../primer/nodes-and-services.html#storagegrid-services["Nome NMS"].



 a| 
GRID-SPEC.XML
 a| 
Specifiche della griglia, XML non elaborato
 a| 
Utilizzato per la configurazione e la distribuzione di StorageGRID. Contiene le specifiche della griglia, l'IP del server NTP, l'IP del server DNS, la topologia di rete e i profili hardware dei nodi.



 a| 
GRID-TASKS.XML
 a| 
Nodo + percorso servizio + ID attributo + nome attributo + valore + indice + ID tabella + nome tabella
 a| 
File di stato delle attività della griglia (procedure di manutenzione). Fornisce i dettagli delle attività attive, terminate, completate, non riuscite e in sospeso della griglia.



 a| 
GRID.JSON
 a| 
Griglia + Revisione + versione software + Descrizione + licenza + password + DNS + NTP + Siti + nodi
 a| 
Informazioni sulla griglia.



 a| 
ILM-CONFIGURATION.XML
 a| 
ID attributo + Nome attributo + valore + Indice + ID tabella + Nome tabella
 a| 
Elenco degli attributi per le configurazioni ILM.



 a| 
ILM-STATUS.XML
 a| 
Nodo + percorso servizio + ID attributo + nome attributo + valore + indice + ID tabella + nome tabella
 a| 
File di informazioni sulle metriche ILM. Contiene le velocità di valutazione ILM per ogni nodo e le metriche a livello di grid.



 a| 
ILM.XML
 a| 
XML raw ILM
 a| 
File di criteri ILM attivo. Contiene dettagli sulle policy ILM attive, come ID del pool di storage, comportamento di acquisizione, filtri, regole e descrizione.



 a| 
LOG.TGZ
 a| 
_n/a_
 a| 
File di registro scaricabile. Contiene `bycast-err.log` e `servermanager.log` da ciascun nodo.



 a| 
MANIFEST.XML
 a| 
Ordine di raccolta + nome file contenuto AutoSupport per questi dati + Descrizione di questo elemento dati + numero di byte raccolti + tempo impiegato nella raccolta + Stato di questo elemento dati + Descrizione dell'errore + tipo di contenuto AutoSupport per questi dati +
 a| 
Contiene metadati AutoSupport e brevi descrizioni di tutti i file AutoSupport.



 a| 
NMS-ENTITIES.XML
 a| 
Indice attributo + OID entità + ID nodo + ID modello dispositivo + versione modello dispositivo + Nome entità
 a| 
Raggruppa le entità di servizio in link:../primer/nodes-and-services.html#storagegrid-services["Albero NMS"]. Fornisce dettagli sulla topologia della griglia. Il nodo può essere determinato in base ai servizi in esecuzione sul nodo.



 a| 
OBJECTS-STATUS.XML
 a| 
Nodo + percorso servizio + ID attributo + nome attributo + valore + indice + ID tabella + nome tabella
 a| 
Stato dell'oggetto, inclusi lo stato della scansione in background, il trasferimento attivo, la velocità di trasferimento, i trasferimenti totali, la velocità di eliminazione, i frammenti corrotti, gli oggetti persi, gli oggetti mancanti, il tentativo di riparazione, la velocità di scansione, il periodo di scansione stimato e lo stato di completamento della riparazione.



 a| 
SERVER-STATUS.XML
 a| 
Nodo + percorso servizio + ID attributo + nome attributo + valore + indice + ID tabella + nome tabella
 a| 
Configurazioni server Contiene questi dettagli per ogni nodo: Tipo di piattaforma, sistema operativo, memoria installata, memoria disponibile, connettività storage, numero di serie dello chassis dell'appliance di storage, numero di dischi guasti dello storage controller, temperatura dello chassis del controller di calcolo, hardware di calcolo, numero di serie del controller di calcolo, alimentatore, dimensioni dei dischi e tipo di disco.



 a| 
SERVICE-STATUS.XML
 a| 
Nodo + percorso servizio + ID attributo + nome attributo + valore + indice + ID tabella + nome tabella
 a| 
File di informazioni sul nodo di servizio. Contiene dettagli quali spazio tabella allocato, spazio tabella libero, metriche Reaper del database, durata riparazione segmento, durata lavoro di riparazione, riavvii processo automatici e terminazione processo automatica.



 a| 
STORAGE-GRADE.XML
 a| 
ID grado storage + Nome grado storage + ID nodo storage + percorso del nodo storage
 a| 
File di definizioni di livello di archiviazione per ogni nodo di archiviazione.



 a| 
SUMMARY-ATTRIBUTES.XML
 a| 
OID gruppo + percorso gruppo + ID attributo riepilogo + nome attributo riepilogo + valore + indice + ID tabella + nome tabella
 a| 
Dati di stato del sistema di alto livello che riassumono le informazioni sull'utilizzo di StorageGRID. Fornisce dettagli quali nome della griglia, nomi dei siti, numero di nodi storage per grid e per sito, tipo di licenza, capacità e utilizzo della licenza, termini del supporto software e dettagli sulle operazioni di S3.



 a| 
SYSTEM-ALERTS.XML
 a| 
Nome + gravità + Nome nodo + Stato avviso + Nome sito + tempo di attivazione avviso + tempo di risoluzione avviso + ID regola + ID nodo + ID sito + tacitato + altre annotazioni + altre etichette
 a| 
Avvisi di sistema correnti che indicano potenziali problemi nel sistema StorageGRID.



 a| 
USERAGENTS.XML
 a| 
Agente utente + numero di giorni + richieste HTTP totali + byte totali acquisiti + byte totali recuperati + richieste PUT + richieste GET + richieste DELETE + richieste HEAD + richieste POST + richieste OPZIONI + tempo medio richiesta (ms) + tempo medio richiesta PUT (ms) + tempo medio richiesta GET (ms) + tempo medio richiesta ELIMINAZIONE (ms) + tempo medio richiesta HEAD (ms) + tempo medio richiesta POST (ms) + tempo medio richiesta OPZIONI (ms)
 a| 
Statistiche basate sugli agenti utente dell'applicazione. Ad esempio, il numero di operazioni PUT/GET/DELETE/HEAD per agente utente e la dimensione totale dei byte di ciascuna operazione.



 a| 
X-HEADER-DATA
 a| 
X-NetApp-asup-generated-on + X-NetApp-asup-hostname + X-NetApp-asup-os-version + X-NetApp-asup-serial-num + X-NetApp-asup-subject + X-NetApp-asup-system-id + X-NetApp-asup-model-name +
 a| 
Dati di intestazione AutoSupport.

|===