---
permalink: s3/deprecated-put-bucket-request-modifications-for-compliance.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, deprecated bucket requests for compliance 
summary: 'L"elemento XML SGCompliance è obsoleto. In precedenza, è possibile includere questo elemento personalizzato StorageGRID nel corpo di richiesta XML opzionale delle richieste CreateBucket per creare un bucket conforme.' 
---
= Obsoleto: CreateBucket richiede modifiche per la conformità
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'elemento XML SGCompliance è obsoleto. In precedenza, è possibile includere questo elemento personalizzato StorageGRID nel corpo di richiesta XML opzionale delle richieste CreateBucket per creare un bucket conforme.

[NOTE]
====
La funzionalità di conformità StorageGRID, disponibile nelle versioni precedenti di StorageGRID, è obsoleta ed è stata sostituita da blocco oggetti S3. Per ulteriori informazioni, vedere quanto segue:

* link:../s3/use-s3-api-for-s3-object-lock.html["Utilizzare l'API REST S3 per configurare il blocco oggetti S3"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["Knowledge base di NetApp: Come gestire i bucket conformi alle versioni precedenti in StorageGRID 11.5"^]


====
Non è più possibile creare nuovi bucket con Compliance abilitata. Se si tenta di utilizzare le modifiche della richiesta CreateBucket per la conformità per creare un nuovo bucket conforme, viene visualizzato il seguente messaggio di errore:

[listing]
----
The Compliance feature is deprecated.
Contact your StorageGRID administrator if you need to create new Compliant buckets.
----