---
permalink: s3/upload-part.html 
sidebar: sidebar 
keywords: s3 UploadPart operation 
summary: 'L"operazione UploadPart carica una parte in un upload multiparte per un oggetto.' 
---
= Intestazioni di richiesta supportate e non supportate per le operazioni S3 UploadPart in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'operazione UploadPart carica una parte in un upload multiparte per un oggetto.



[[supported-request-headers]]
== Intestazioni di richiesta supportate

Sono supportate le seguenti intestazioni di richiesta:

* Intestazioni della richiesta di checksum:
+
--
** `x-amz-checksum-crc32`
** `x-amz-checksum-crc32c`
** `x-amz-checksum-crc64nvme`
** `x-amz-checksum-sha256`


--
+
Se hai specificato un checksum CRC-32, CRC-32C, CRC-64/NVME o SHA-256 durante la richiesta CreateMultipartUpload, devi anche includere l'intestazione della richiesta di checksum in ogni richiesta UploadPart.

+

NOTE: Se una richiesta CreateMultipartUpload non specifica un checksum, StorageGRID non calcola un checksum CRC-64/NVME predefinito per un oggetto.

* `Content-Length`
* `Content-MD5`




[[request-headers-for-server-side-encryption]]
== Intestazioni di richiesta per la crittografia lato server

Se è stata specificata la crittografia SSE-C per la richiesta CreateMultipartUpload, è necessario includere anche le seguenti intestazioni di richiesta in ogni richiesta UploadPart:

* `x-amz-server-side-encryption-customer-algorithm`: Specificare `AES256`.
* `x-amz-server-side-encryption-customer-key`: Specificare la stessa chiave di crittografia fornita nella richiesta CreateMultipartUpload.
* `x-amz-server-side-encryption-customer-key-MD5`: Specificare lo stesso digest MD5 fornito nella richiesta CreateMultipartUpload.



CAUTION: Le chiavi di crittografia fornite non vengono mai memorizzate. Se si perde una chiave di crittografia, si perde l'oggetto corrispondente. Prima di utilizzare le chiavi fornite dal cliente per proteggere i dati degli oggetti, esaminare le considerazioni riportate in link:using-server-side-encryption.html["Utilizzare la crittografia lato server"].



[[unsupported-request-headers]]
== Intestazioni di richiesta non supportate

Le seguenti intestazioni di richiesta non sono supportate:

* `x-amz-sdk-checksum-algorithm`
* `x-amz-trailer`
* `x-amz-checksum-md5`
* `x-amz-checksum-sha1`
* `x-amz-checksum-sha512`
* `x-amz-checksum-xxhash3`
* `x-amz-checksum-xxhash64`
* `x-amz-checksum-xxhash128`




[[versioning]]
== Versione

Il caricamento multiparte consiste in operazioni separate per l'avvio del caricamento, l'elenco dei caricamenti, il caricamento delle parti, l'assemblaggio delle parti caricate e il completamento del caricamento. Quando si esegue l'operazione CompleteMultipartUpload, gli oggetti vengono creati (e, se applicabile, vengono aggiornati).
