---
permalink: s3/use-s3-select.html 
sidebar: sidebar 
keywords: use S3 Select, S3 Select 
summary: StorageGRID supporta le seguenti condizioni, tipi di dati, operatori e parole chiave riservate Amazon S3 Select per il comando SelectObjectContent. 
---
= Operazioni Amazon S3 Select supportate in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID supporta le seguenti condizioni, tipi di dati e operatori Amazon S3 Select per link:select-object-content.html["Comando SelectObjectContent"].


NOTE: Gli elementi non elencati non sono supportati.

Per la sintassi, vedere link:select-object-content.html["SelectObjectContent"]. Per ulteriori informazioni su S3 Select, vedere https://docs.aws.amazon.com/AmazonS3/latest/userguide/selecting-content-from-objects.html["Documentazione AWS per S3 Select"^] .

Solo gli account tenant con S3 Select abilitato possono eseguire query SelectObjectContent. Consultare la link:../admin/manage-s3-select-for-tenant-accounts.html["Considerazioni e requisiti per l'utilizzo di S3 Select"].



[[clauses]]
== Clausole

* SELEZIONARE l'elenco
* CLAUSOLA FROM
* Clausola WHERE
* Clausola di LIMITAZIONE




[[data-types]]
== Tipi di dati

* bool
* intero
* stringa
* fluttuare
* decimale, numerico
* data e ora




[[operators]]
== Operatori



[[logical-operators]]
=== Operatori logici

* E.
* NO
* OPPURE




[[comparison-operators]]
=== Operatori di confronto

* <
* >
* <=
* >=
* =
* =
* <>
* !=
* TRA
* POLL




[[pattern-matching-operators]]
=== Operatori di corrispondenza dei modelli

* MI PIACE
* _
* %




[[unitary-operators]]
=== Operatori unitari

* È NULL
* NON È NULL




[[math-operators]]
=== Operatori matematici

* +
* -
* *
* /
* %


StorageGRID segue la precedenza dell'operatore Amazon S3 Select.



[[aggregate-functions]]
== Funzioni di aggregazione

* MEDIA()
* CONTEGGIO(*)
* MAX()
* MIN()
* SOMMA()




[[conditional-functions]]
== Funzioni condizionali

* CASO
* COALESCE
* NULLIF




[[conversion-functions]]
== Funzioni di conversione

* CAST (per il tipo di dati supportato)




[[date-functions]]
== Funzioni di data

* DATA_ADD
* DATA_DIFF
* ESTRARRE
* TO_STRING
* TO_TIMESTAMP
* UTCNOW




[[string-functions]]
== Funzioni di stringa

* CHAR_LENGTH, CHARACTER_LENGTH
* ABBASSARE
* SOTTOSTRINGA
* TAGLIARE
* SUPERIORE

