---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: È possibile recuperare i file di log e i dati di sistema di StorageGRID, inclusi i dati di configurazione, e inviarli al supporto tecnico. 
---
= Raccogliere i file di log e i dati di sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile recuperare i file di log e i dati di sistema di StorageGRID, inclusi i dati di configurazione, e inviarli al supporto tecnico.

.Prima di iniziare
* L'utente ha effettuato l'accesso al Grid Manager sul nodo amministrativo principale utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone di link:../admin/admin-group-permissions.html["autorizzazioni di accesso specifiche"].
* Si dispone della passphrase di provisioning.


.A proposito di questa attività
Utilizzare Grid Manager per raccogliere link:logs-files-reference.html["file di log"], i dati di sistema e i dati di configurazione da qualsiasi nodo della griglia per il periodo di tempo selezionato. I dati vengono raccolti e archiviati in un `.tar.gz` file che è possibile scaricare sul computer locale o inviare al supporto tecnico.

In alternativa, è possibile modificare la destinazione dei registri di controllo e inviare le informazioni di controllo a un server syslog esterno. I registri locali dei record di controllo continuano a essere generati e memorizzati quando viene configurato un server syslog esterno. Vedere link:../monitor/configure-audit-messages.html["Configurare i messaggi di controllo e il server syslog esterno"].

.Fasi
. Selezionare *SUPPORT* > *Tools* > *Logs*. Viene visualizzata una tabella di nodi.
. Selezionare i nodi della griglia per i quali si desidera raccogliere i file di log.
+
È possibile ordinare in base al nome del nodo, al sito e al tipo di nodo. Le colonne Sito e tipo nodo contengono filtri per la selezione in base ai singoli siti e tipi di nodo.

. Selezionare *continua*.
. Selezionare la data e l'intervallo di tempo dei dati da includere nei file di registro.
+
Se si seleziona un periodo di tempo molto lungo o si raccolgono i registri da tutti i nodi di una griglia di grandi dimensioni, l'archivio del registro potrebbe diventare troppo grande per essere memorizzato su un nodo o troppo grande per essere raccolto nel nodo di amministrazione primario per il download. Se si verifica uno dei due scenari, riavviare la raccolta di log con una serie di dati più piccola.

. Selezionare i tipi di log che si desidera raccogliere.
+
** *Registri delle applicazioni*: Registri specifici delle applicazioni utilizzati più frequentemente dal supporto tecnico per la risoluzione dei problemi. I log raccolti sono un sottoinsieme dei log dell'applicazione disponibili.
** *Registri di controllo*: Registri contenenti i messaggi di controllo generati durante il normale funzionamento del sistema.
** *Network trace*: Registri utilizzati per il debug della rete.
** *Database Prometheus*: Metriche delle serie temporali dai servizi su tutti i nodi.


. Facoltativamente, utilizzare la casella di testo *Note* per inserire note sui file di registro che si stanno raccogliendo.
+
È possibile utilizzare queste note per fornire informazioni di supporto tecnico sul problema che ha richiesto di raccogliere i file di log. Le note vengono aggiunte a un file denominato `info.txt`, insieme ad altre informazioni sulla raccolta di file di registro. Il `info.txt` file viene salvato nel pacchetto di archiviazione del file di registro.

. Nella casella di testo *Provisioning Passphrase*, immettere la passphrase di provisioning per il sistema StorageGRID.
. Selezionare *Raccogli registri*.
+
È possibile utilizzare la pagina Logs per monitorare l'avanzamento della raccolta dei file di log per ciascun nodo della griglia.

+
Se viene visualizzato un messaggio di errore relativo alle dimensioni del registro, provare a raccogliere i registri per un periodo di tempo più breve o per un numero inferiore di nodi.

. Se la raccolta del registro non riesce:
+
** Se viene visualizzato il messaggio "raccolta registro non riuscita", è possibile riprovare la raccolta del registro o terminare la sessione senza riprovare.
** Se viene visualizzato il messaggio "raccolta registro parzialmente non riuscita", è possibile riprovare la raccolta del registro, terminare la sessione, scaricare il file di registro parziale o inviare il file di registro parziale a AutoSupport.


. Una volta completata la raccolta dei file di registro:
+
** Selezionare *Download* per scaricare il `.tar.gz` file.
** Selezionare *Invia a AutoSupport* per inviare il `.tar.gz` file al supporto tecnico.
+
Il `.tar.gz` file contiene tutti i file di registro di tutti i nodi della griglia in cui la raccolta dei log è stata eseguita correttamente. Il file combinato `.tar.gz` contiene un archivio di file di registro per ogni nodo della griglia.

+
L'oggetto del pacchetto AutoSupport è `USER_TRIGGERED_SUPPORT_BUNDLE`.



. Selezionare *fine*.
+

CAUTION: Il `.tar.gz` file viene eliminato quando si seleziona *fine*. Assicurarsi di scaricare o inviare prima il file.


