---
permalink: monitor/managing-alerts.html 
sidebar: sidebar 
keywords: alert rules, managing alerts, alerts, alert notifications. edit alert rules 
summary: 'Il sistema di avviso fornisce un"interfaccia di facile utilizzo per rilevare, valutare e risolvere i problemi che possono verificarsi durante il funzionamento di StorageGRID.' 
---
= Gestire gli avvisi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il sistema di avviso fornisce un'interfaccia di facile utilizzo per rilevare, valutare e risolvere i problemi che possono verificarsi durante il funzionamento di StorageGRID.

Gli avvisi vengono attivati a livelli di severità specifici quando le condizioni delle regole di avviso vengono valutate come vere. Quando viene attivato un avviso, si verificano le seguenti azioni:

* Sul dashboard di Grid Manager viene visualizzata un'icona di severità degli avvisi e il numero di avvisi correnti viene incrementato.
* L'avviso viene visualizzato nella pagina di riepilogo *Nodi* e nella scheda *Nodi* > *_nodo_* > *Panoramica*.
* Viene inviata una notifica e-mail, presupponendo che sia stato configurato un server SMTP e che siano stati forniti indirizzi e-mail per i destinatari.
* Viene inviata una notifica SNMP (Simple Network Management Protocol), presupponendo che l'agente SNMP StorageGRID sia stato configurato.


È possibile creare avvisi personalizzati, modificare o disattivare gli avvisi e gestire le notifiche degli avvisi.

Per saperne di più:

* Rivedi i video:
+
.Panoramica degli avvisi
video::2eea81c5-8323-417f-b0a0-b1ff008506c1[panopto]
+
.Avvisi personalizzati
video::54af90c4-9a38-4136-9621-b1ff008604a3[panopto]
* Fare riferimento allink:alerts-reference.html["Riferimenti agli avvisi"] .

