---
permalink: maintain/checking-data-repair-jobs.html 
sidebar: sidebar 
keywords: storagegrid, data repair 
summary: Prima di disattivare un nodo di rete, è necessario confermare che non sono attivi lavori di riparazione dei dati. Se le riparazioni non sono riuscite, è necessario riavviarle e lasciarle completare prima di eseguire la procedura di decommissionamento. 
---
= Verifica i job di riparazione dei dati in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di dismettere o espandere un nodo della griglia, è necessario confermare che non siano attivi processi di riparazione dei dati.  Se una riparazione non ha avuto successo, è necessario riavviarla e lasciarla completare prima di eseguire la procedura di dismissione.

* Fare riferimento alink:../expand/index.html["Tipi di espansione"] per i dettagli su come espandere un nodo della griglia.
* Usa Grid Manager per monitorare i processi di ripristino in corso e visualizzare la cronologia dei ripristini. Consulta queste procedure:
+
** link:../maintain/restoring-object-data-to-storage-volume-for-appliance.html["Ripristinare i dati dell'oggetto nel volume di storage per l'appliance"]
** link:../maintain/restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["Ripristinare i dati degli oggetti nel volume di storage in cui il disco di sistema è intatto"]
** link:../maintain/restoring-object-data-to-storage-volume.html["Ripristinare i dati dell'oggetto nel volume di storage (errore del disco di sistema)"]



