---
permalink: maintain/checking-storage-state-after-recovering-storage-node-system-drive.html 
sidebar: sidebar 
keywords: storagegrid, storage node recovery, system drive, storage state 
summary: 'Dopo aver ripristinato l"unità di sistema per un nodo di storage, è necessario verificare che lo stato desiderato del nodo di storage sia impostato su online e assicurarsi che lo stato sia online per impostazione predefinita ogni volta che il server del nodo di storage viene riavviato.' 
---
= Controllare lo stato dello storage dopo il ripristino del disco di sistema Storage Node
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver ripristinato l'unità di sistema per un nodo di storage, è necessario verificare che lo stato desiderato del nodo di storage sia impostato su online e assicurarsi che lo stato sia online per impostazione predefinita ogni volta che il server del nodo di storage viene riavviato.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Il nodo di storage è stato ripristinato e il ripristino dei dati è stato completato.


.Fasi
. Selezionare *Nodi* > *Nodo di archiviazione_* > *Attività*.
. Se l'elenco a discesa *Stato di archiviazione* è impostato su Sola lettura o Offline, selezionare *Online*.
. Selezionare *Salva*.

