---
permalink: maintain/checking-storage-state-after-recovering-storage-node-system-drive.html 
sidebar: sidebar 
keywords: storagegrid, storage node recovery, system drive, storage state 
summary: 'Dopo aver ripristinato l"unità di sistema per un nodo di storage, è necessario verificare che lo stato desiderato del nodo di storage sia impostato su online e assicurarsi che lo stato sia online per impostazione predefinita ogni volta che il server del nodo di storage viene riavviato.' 
---
= Controllare lo stato dello storage dopo il ripristino del disco di sistema Storage Node
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver ripristinato l'unità di sistema per un nodo di storage, è necessario verificare che lo stato desiderato del nodo di storage sia impostato su online e assicurarsi che lo stato sia online per impostazione predefinita ogni volta che il server del nodo di storage viene riavviato.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Il nodo di storage è stato ripristinato e il ripristino dei dati è stato completato.


.Fasi
. Selezionare *SUPPORT* > *Tools* > *Grid topology*.
. Controllare i valori di *Recovery Storage Node* > *LDR* > *Storage* > *Storage state -- Desired* e *Storage state -- Current*.
+
Il valore di entrambi gli attributi deve essere Online.

. Se lo stato di storage -- desiderato è impostato su sola lettura, attenersi alla seguente procedura:
+
.. Fare clic sulla scheda *Configurazione*.
.. Dall'elenco a discesa *Storage state -- Desired* (Stato storage -- desiderato*), selezionare *Online*.
.. Fare clic su *Applica modifiche*.
.. Fare clic sulla scheda *Panoramica* e verificare che i valori di *Stato dello storage -- desiderato* e *Stato dello storage -- corrente* siano aggiornati a Online.



