---
permalink: maintain/checking-storage-state-after-recovering-sga.html 
sidebar: sidebar 
keywords: storagegrid, recovery, node recovery, storage state 
summary: 'Dopo aver ripristinato un nodo di storage dell"appliance, è necessario verificare che lo stato desiderato del nodo di storage dell"appliance sia impostato su online e assicurarsi che lo stato sia online per impostazione predefinita ogni volta che si riavvia il server del nodo di storage.' 
---
= Controllare lo stato dello storage dopo il ripristino del nodo di storage dell'appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver ripristinato un nodo di storage dell'appliance, è necessario verificare che lo stato desiderato del nodo di storage dell'appliance sia impostato su online e assicurarsi che lo stato sia online per impostazione predefinita ogni volta che si riavvia il server del nodo di storage.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Il nodo di storage è stato ripristinato e il ripristino dei dati è stato completato.


.Fasi
. Selezionare *Nodi* > *Nodo di archiviazione_* > *Attività*.
. Se l'elenco a discesa *Stato di archiviazione* è impostato su Sola lettura o Offline, selezionare *Online*.
. Selezionare *Salva*.

