---
permalink: maintain/convert-to-data-only-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop services, power down host, power off host 
summary: Per aumentare le prestazioni, è possibile convertire i nodi di archiviazione non ADC più lenti in nodi di archiviazione solo dati. 
---
= Convertire un nodo di storage in un nodo solo dati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per aumentare le prestazioni, è possibile convertire i nodi di archiviazione non ADC più lenti in nodi di archiviazione solo dati.

L'utilizzo di un nodo di storage esclusivamente per i dati può essere utile se i nodi di storage hanno caratteristiche di prestazioni diverse. Ad esempio, per aumentare potenzialmente le performance, potrebbero esserci nodi di storage su disco rotante a elevata capacità e solo dati accompagnati da nodi di storage dalle performance elevate e solo metadati.

Inoltre, puoi ottenere una maggiore capacità di metadati rimuovendo i nodi a bassa RAM da Cassandra, cosa che aumenta il limite di capacità dei metadati per nodo. Fare riferimento alla link:../admin/managing-object-metadata-storage.html["Gestire lo storage dei metadati degli oggetti"].

Quando si installano nodi solo dati, la griglia deve contenere quanto segue:

* Un minimo di due nodi di storage combinati o solo dati per grid
* Almeno un nodo di storage combinato o solo dati per sito
* Un minimo di tre nodi di storage combinati o solo metadati per sito


.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone di link:admin-group-permissions.html["Autorizzazione di manutenzione o di accesso root"].
* Il nodo di archiviazione che si desidera convertire non contiene il servizio ADC o si deve utilizzare link:../maintain/move-adc-service.html["Spostato il servizio ADC"]un altro nodo.
* Il nodo di storage non è un nodo di soli metadati o un nodo di soli dati.
* Gli altri nodi del sito dispongono di spazio sufficiente per i metadati che verranno migrati dal nodo di storage che si sta convertendo.


.A proposito di questa attività
Utilizzare questa procedura per convertire uno o più nodi di archiviazione combinati o di solo metadati che non contengono il servizio ADC in nodi di solo dati. I nodi storage devono trovarsi nello stesso sito.

Oltre a convertire il nodo di storage, questa procedura decomprime Cassandra dal nodo. Tutti i metadati migreranno su nodi di storage combinati o solo metadati. A seconda della quantità di metadati da migrare, il completamento di questa procedura potrebbe richiedere fino a diversi giorni per nodo.


TIP: In genere, è possibile convertire fino a 10 nodi alla volta se l'utilizzo dei metadati per nodo è inferiore a 1 TB. Se l'utilizzo dei metadati per nodo è superiore a 1 TB, convertire invece fino a 5 nodi per procedura.

.Fasi
. Registrare gli ID dei nodi di archiviazione non ADC che si desidera convertire.
. Nella parte superiore di Grid Manager, selezionare l'icona della guida e selezionare *documentazione API*.
. Selezionare *Vai alla documentazione API privata*.
. Selezionare l' `POST /private/convert-to-data-only-node/start`operazione. Per ulteriori informazioni, fare riferimento link:../admin/using-grid-management-api.html#issue-api-requests["Emettere richieste API"] a.
+
Ciascun nodo viene riavviato durante la procedura.

. È possibile utilizzare `GET /private/convert-to-data-only-node` per monitorare la procedura. Se si verificano errori, selezionare `POST /private/convert-to-data-only-node/retry` per riprovare la procedura.
. link:../maintain/downloading-recovery-package.html["Scaricare un pacchetto di ripristino"] al termine di questa procedura.

