---
permalink: maintain/copying-audit-logs-from-failed-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, audit log, copy audit log, copying audit log, primary admin node, primary admin node 
summary: 'Se si riesce a copiare i registri di audit dal nodo di amministrazione principale guasto, è necessario conservarli per mantenere il record dell"attività e dell"utilizzo del sistema della griglia. È possibile ripristinare i registri di controllo conservati nel nodo di amministrazione primario recuperato dopo che è attivo e in esecuzione.' 
---
= Copia i registri di controllo dal nodo di amministrazione primario non riuscito
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se è possibile copiare i registri di controllo dal nodo di amministrazione primario guasto, è necessario conservarli per mantenere il record dell'attività e dell'utilizzo del sistema della griglia. È possibile ripristinare i registri di controllo conservati nel nodo di amministrazione primario recuperato dopo che è attivo e in esecuzione.

.A proposito di questa attività
Questa procedura copia i file di log di audit dal nodo di amministrazione non riuscito in una posizione temporanea su un nodo griglia separato. Questi registri di controllo conservati possono quindi essere copiati nel nodo di amministrazione sostitutivo. I registri di controllo non vengono copiati automaticamente nel nuovo nodo di amministrazione.

A seconda del tipo di errore, potrebbe non essere possibile copiare i registri di controllo da un nodo di amministrazione non riuscito. Se l'implementazione ha un solo nodo di amministrazione, il nodo di amministrazione recuperato avvia la registrazione degli eventi nel registro di controllo in un nuovo file vuoto e i dati precedentemente registrati vengono persi. Se l'implementazione include più di un nodo di amministrazione, è possibile ripristinare i registri di controllo da un altro nodo di amministrazione.


NOTE: Se i registri di controllo non sono ora accessibili sul nodo di amministrazione guasto, potrebbe essere possibile accedervi in un secondo momento, ad esempio dopo il ripristino dell'host.

.Fasi
. Se possibile, accedere al nodo di amministrazione primario non riuscito.  In caso contrario, accedi a qualsiasi nodo di amministrazione disponibile.
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Immettere la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla directory principale: `su -`
.. Immettere la password elencata nel `Passwords.txt` file.
+
Quando si è collegati come root, il prompt cambia da `$` a `#`.



. Arrestare il servizio AMS per evitare che crei un nuovo file di registro:``service ams stop``
. Accedere alla directory di esportazione della verifica:
+
`cd /var/local/audit/export`

+
(O `cd /var/local/log` sui sistemi precedenti)

. Rinominare il file di registro di origine con un nome di file numerato univoco.
+
[NOTE]
====
** Se il file di registro è in `/var/local/audit/export` directory, il suo nome è `audit.log` .
** Se il file di registro è in `/var/local/log` directory, il suo nome è `localaudit.log` .


====
+
Ad esempio, rinominare il `localaudit.log` file a `2025-10-22.txt.1` .

+
[listing]
----
ls -l
mv localaudit.log 2025-10-22.txt.1
----
. Riavviare il servizio AMS: `service ams start`
. Creare la directory per copiare tutti i file di log di controllo in una posizione temporanea su un nodo griglia separato: `ssh admin@_grid_node_IP_ mkdir -p /var/local/tmp/saved-audit-logs`
+
Quando richiesto, inserire la password per admin.

. Copiare tutti i file di log di controllo nella posizione temporanea: `scp -p * admin@_grid_node_IP_:/var/local/tmp/saved-audit-logs`
+
Quando richiesto, inserire la password per admin.

. Disconnettersi come root: `exit`

