---
permalink: maintain/copying-audit-logs-from-failed-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, audit log, copy audit log, copying audit log, non-primary admin node, non primary admin node 
summary: 'Se è possibile copiare i registri di controllo dal nodo di amministrazione non riuscito, è necessario conservarli per mantenere il record dell"attività e dell"utilizzo del sistema della griglia. È possibile ripristinare i registri di controllo conservati nel nodo di amministrazione non primario recuperato una volta attivato e in esecuzione.' 
---
= Copia i registri di controllo dal nodo di amministrazione non primario non riuscito
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se è possibile copiare i registri di controllo dal nodo di amministrazione non riuscito, è necessario conservarli per mantenere il record dell'attività e dell'utilizzo del sistema della griglia. È possibile ripristinare i registri di controllo conservati nel nodo di amministrazione non primario recuperato una volta attivato e in esecuzione.

Questa procedura copia i file di log di audit dal nodo di amministrazione non riuscito in una posizione temporanea su un nodo griglia separato. Questi registri di controllo conservati possono quindi essere copiati nel nodo di amministrazione sostitutivo. I registri di controllo non vengono copiati automaticamente nel nuovo nodo di amministrazione.

A seconda del tipo di errore, potrebbe non essere possibile copiare i registri di controllo da un nodo di amministrazione non riuscito. Se l'implementazione ha un solo nodo di amministrazione, il nodo di amministrazione recuperato avvia la registrazione degli eventi nel registro di controllo in un nuovo file vuoto e i dati precedentemente registrati vengono persi. Se l'implementazione include più di un nodo di amministrazione, è possibile ripristinare i registri di controllo da un altro nodo di amministrazione.


NOTE: Se i registri di controllo non sono ora accessibili sul nodo di amministrazione guasto, potrebbe essere possibile accedervi in un secondo momento, ad esempio dopo il ripristino dell'host.

. Se possibile, accedere al nodo Admin non riuscito. In caso contrario, accedere al nodo di amministrazione primario o a un altro nodo di amministrazione, se disponibile.
+
.. Immettere il seguente comando: `ssh admin@grid_node_IP`
.. Immettere la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla directory principale: `su -`
.. Immettere la password elencata nel `Passwords.txt` file.


+
Quando si è collegati come root, il prompt cambia da `$` a `#`.

. Arrestare il servizio AMS per evitare che crei un nuovo file di registro:``service ams stop``
. Accedere alla directory di esportazione della verifica:
+
`cd /var/local/audit/export/`

. Rinominare il file di origine audit.log con un nome di file numerato univoco. Ad esempio, rinominare il file audit.log in `2023-10-25.txt.1`.
+
[listing]
----
ls -l
mv audit.log 2023-10-25.txt.1
----
. Riavviare il servizio AMS: `service ams start`
. Creare la directory per copiare tutti i file di log di controllo in una posizione temporanea su un nodo griglia separato: `ssh admin@grid_node_IP mkdir -p /var/local/tmp/saved-audit-logs`
+
Quando richiesto, inserire la password per admin.

. Copiare tutti i file di log di controllo nella posizione temporanea: `scp -p * admin@grid_node_IP:/var/local/tmp/saved-audit-logs`
+
Quando richiesto, inserire la password per admin.

. Disconnettersi come root: `exit`

