---
permalink: maintain/gathering-required-materials-site-decom.html 
sidebar: sidebar 
keywords: storagegrid, decommission 
summary: Prima di decommissionare un sito, è necessario procurarsi i seguenti materiali. 
---
= Raccogliere il materiale necessario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di decommissionare un sito, è necessario procurarsi i seguenti materiali.

[cols="1a,2a"]
|===
| Elemento | Note 


 a| 
File pacchetto di ripristino `.zip`
 a| 
È necessario scaricare il file del pacchetto di ripristino più recente `.zip`(`sgws-recovery-package-id-revision.zip` ). È possibile utilizzare il file del pacchetto di ripristino per ripristinare il sistema in caso di errore.

link:downloading-recovery-package.html["Scaricare il pacchetto di ripristino"]



 a| 
`Passwords.txt` file
 a| 
Questo file contiene le password necessarie per accedere ai nodi della griglia sulla riga di comando ed è incluso nel pacchetto di ripristino.



 a| 
Passphrase di provisioning
 a| 
La passphrase viene creata e documentata al momento dell'installazione del sistema StorageGRID. La passphrase di provisioning non è contenuta nel `Passwords.txt` file.



 a| 
Descrizione della topologia del sistema StorageGRID prima dello smantellamento
 a| 
Se disponibile, procurarsi la documentazione che descrive la topologia corrente del sistema.

|===
.Informazioni correlate
link:../admin/web-browser-requirements.html["Requisiti del browser Web"]
