---
permalink: maintain/gathering-required-materials-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recovery, grid node recovery, node recovery 
summary: Prima di eseguire le procedure di manutenzione, assicurarsi di disporre dei materiali necessari per ripristinare un nodo della griglia guasto. 
---
= Raccogliere i materiali necessari per il ripristino dei nodi grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di eseguire le procedure di manutenzione, assicurarsi di disporre dei materiali necessari per ripristinare un nodo della griglia guasto.

[cols="1a,2a"]
|===
| Elemento | Note 


 a| 
Archivio di installazione di StorageGRID
 a| 
Se è necessario ripristinare un nodo grid, è necessario farlo <<download-and-extract-install-files-recover,Scaricare i file di installazione di StorageGRID>> per la piattaforma.

*Nota:* non è necessario scaricare i file se si stanno ripristinando volumi di storage guasti su un nodo di storage.



 a| 
Laptop di assistenza
 a| 
Il laptop di assistenza deve disporre di quanto segue:

* Porta di rete
* Client SSH (ad esempio, putty)
* link:../admin/web-browser-requirements.html["Browser Web supportato"]




 a| 
File pacchetto di ripristino `.zip`
 a| 
Ottenere una copia del file del pacchetto di ripristino più recente `.zip`:
`sgws-recovery-package-_id-revision_.zip`

Il contenuto del `.zip` file viene aggiornato ogni volta che il sistema viene modificato. Dopo aver apportato tali modifiche, viene richiesto di memorizzare la versione più recente del pacchetto di ripristino in una posizione sicura. Utilizzare la copia più recente per eseguire il ripristino in caso di errori della griglia.

Se il nodo di amministrazione primario funziona normalmente, è possibile scaricare il pacchetto di ripristino da Grid Manager. Selezionare *MANUTENZIONE* > *sistema* > *pacchetto di ripristino*.

Se non è possibile accedere a Grid Manager, è possibile trovare copie crittografate del pacchetto di ripristino su alcuni nodi di storage che contengono il servizio ADC. Su ogni nodo di archiviazione, esaminare questa posizione per il pacchetto di ripristino: `/var/local/install/sgws-recovery-package-_grid-id_-_revision_.zip.gpg` Utilizzare il pacchetto di ripristino con il numero di revisione più alto.



 a| 
`Passwords.txt` file
 a| 
Contiene le password necessarie per accedere ai nodi della griglia sulla riga di comando. Incluso nel pacchetto di ripristino.



 a| 
Passphrase di provisioning
 a| 
La passphrase viene creata e documentata al momento dell'installazione del sistema StorageGRID. La passphrase di provisioning non è contenuta nel `Passwords.txt` file.



 a| 
Documentazione aggiornata per la piattaforma
 a| 
Per la documentazione, visitare il sito Web del vendor della piattaforma.

Per le versioni attualmente supportate della piattaforma, vedere https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità NetApp"^] .

|===


== Scaricare ed estrarre i file di installazione di StorageGRID

.[[download-and-extract-install-files-recovery]]
Scaricare il software ed estrarre i file, a meno che non si sia link:recovering-from-storage-node-failures.html["Ripristino dei volumi di storage guasti in un nodo di storage"].

È necessario utilizzare la versione di StorageGRID attualmente in esecuzione sulla griglia.

.Fasi
. Determinare la versione del software attualmente installata. Nella parte superiore di Grid Manager, selezionare l'icona della guida e selezionare *About* (informazioni su).
. Andare a https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Pagina dei download NetApp per StorageGRID"^].
. Selezionare la versione di StorageGRID attualmente in esecuzione nella griglia.
+
Le versioni software StorageGRID hanno questo formato: `11.x.y`.

. Accedi con il nome utente e la password del tuo account NetApp.
. Leggere il Contratto di licenza con l'utente finale, selezionare la casella di controllo, quindi selezionare *Accept & Continue* (Accetta e continua).
. Nella colonna *Installa StorageGRID* della pagina di download, selezionare il `.tgz` file o `.zip` per la propria piattaforma.
+
La versione mostrata nel file di archivio dell'installazione deve corrispondere alla versione del software attualmente installato.

+
Utilizzare il `.zip` file se si utilizza Windows.

+
[cols="1a,2a"]
|===
| Piattaforma | Archivio di installazione 


 a| 
Red Hat Enterprise Linux
| `StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz` 


 a| 
Ubuntu o Debian o appliance
| `StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz` 


 a| 
VMware
| `StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-VMware-_uniqueID_.tgz` 
|===
. Scaricare ed estrarre il file di archivio.
. Segui la procedura appropriata per la tua piattaforma per scegliere i file di cui hai bisogno, in base alla piattaforma e ai nodi grid da ripristinare.
+
I percorsi elencati nella fase per ciascuna piattaforma sono relativi alla directory di primo livello installata dal file di archivio.

. Se si sta ripristinando un link:../rhel/index.html["Sistema Red Hat Enterprise Linux"], selezionare i file appropriati.


[cols="1a,1a"]
|===
| Percorso e nome del file | Descrizione 


| ./rpms/README  a| 
Un file di testo che descrive tutti i file contenuti nel file di download di StorageGRID.



| ./rpms/NLF000000.txt  a| 
Licenza gratuita che non fornisce alcun diritto di supporto per il prodotto.



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
Pacchetto RPM per l'installazione delle immagini del nodo StorageGRID sui vostri host RHEL.



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
Pacchetto RPM per l'installazione del servizio host StorageGRID sugli host RHEL.



| Tool di scripting per la distribuzione | Descrizione 


| ./rpms/configure-storagegrid.py  a| 
Script Python utilizzato per automatizzare la configurazione di un sistema StorageGRID.



| ./rpms/configure-sga.py  a| 
Script Python utilizzato per automatizzare la configurazione delle appliance StorageGRID.



| ./rpms/configure-storagegrid.sample.json  a| 
Un file di configurazione di esempio da utilizzare con `configure-storagegrid.py` lo script.



| ./rpms/storagegrid-ssoauth.py  a| 
Script Python di esempio che è possibile utilizzare per accedere all'API Grid Management quando è attivato il single sign-on. È anche possibile utilizzare questo script per l'integrazione federate Ping.



| ./rpms/configure-storagegrid.blank.json  a| 
Un file di configurazione vuoto da utilizzare con `configure-storagegrid.py` lo script.



| ./rpms/extra/ansible  a| 
Esempio di ruolo e playbook Ansible per la configurazione degli host RHEL per l'implementazione dei container StorageGRID. È possibile personalizzare il ruolo o il manuale in base alle esigenze.



| ./rpms/storagegrid-ssoauth-azure.py  a| 
Esempio di script Python che è possibile utilizzare per accedere all'API Grid Management quando SSO (Single Sign-on) è attivato utilizzando Active Directory o Ping Federate.



| ./rpms/storagegrid-ssoauth-azure.js  a| 
Uno script di supporto chiamato dallo script Python associato `storagegrid-ssoauth-azure.py` per eseguire interazioni SSO con Azure.



| ./rpms/extra/schemi-api  a| 
Schemi API per StorageGRID.

*Nota*: Prima di eseguire un aggiornamento, è possibile utilizzare questi schemi per confermare che qualsiasi codice scritto per utilizzare le API di gestione StorageGRID sarà compatibile con la nuova release di StorageGRID se non si dispone di un ambiente StorageGRID non in produzione per il test di compatibilità degli aggiornamenti.

|===
. Se si sta ripristinando un link:../ubuntu/index.html["Ubuntu o sistema Debian"], selezionare i file appropriati.


[cols="1a,1a"]
|===
| Percorso e nome del file | Descrizione 


| ./debs/README  a| 
Un file di testo che descrive tutti i file contenuti nel file di download di StorageGRID.



| ./debs/NLF000000.txt  a| 
Un file di licenza NetApp non in produzione che è possibile utilizzare per le implementazioni di test e proof of concept.



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
PACCHETTO DEB per l'installazione delle immagini dei nodi StorageGRID su host Ubuntu o Debian.



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
MD5 checksum per il file `/debs/storagegrid-webscale-images-version-SHA.deb`.



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
PACCHETTO DEB per l'installazione del servizio host StorageGRID su host Ubuntu o Debian.



| Tool di scripting per la distribuzione | Descrizione 


| ./debs/configure-storagegrid.py  a| 
Script Python utilizzato per automatizzare la configurazione di un sistema StorageGRID.



| ./debs/configure-sga.py  a| 
Script Python utilizzato per automatizzare la configurazione delle appliance StorageGRID.



| ./debs/storagegrid-ssoauth.py  a| 
Script Python di esempio che è possibile utilizzare per accedere all'API Grid Management quando è attivato il single sign-on. È anche possibile utilizzare questo script per l'integrazione federate Ping.



| ./debs/configure-storagegrid.sample.json  a| 
Un file di configurazione di esempio da utilizzare con `configure-storagegrid.py` lo script.



| ./debs/configure-storagegrid.blank.json  a| 
Un file di configurazione vuoto da utilizzare con `configure-storagegrid.py` lo script.



| ./debs/extra/ansible  a| 
Esempio di manuale e ruolo Ansible per la configurazione di host Ubuntu o Debian per la distribuzione di container StorageGRID. È possibile personalizzare il ruolo o il manuale in base alle esigenze.



| ./debs/storagegrid-ssoauth-azure.py  a| 
Esempio di script Python che è possibile utilizzare per accedere all'API Grid Management quando SSO (Single Sign-on) è attivato utilizzando Active Directory o Ping Federate.



| ./debrs/storagegrid-ssoauth-azure.js  a| 
Uno script di supporto chiamato dallo script Python associato `storagegrid-ssoauth-azure.py` per eseguire interazioni SSO con Azure.



| ./debs/extra/schemi api  a| 
Schemi API per StorageGRID.

*Nota*: Prima di eseguire un aggiornamento, è possibile utilizzare questi schemi per confermare che qualsiasi codice scritto per utilizzare le API di gestione StorageGRID sarà compatibile con la nuova release di StorageGRID se non si dispone di un ambiente StorageGRID non in produzione per il test di compatibilità degli aggiornamenti.

|===
. Se si sta ripristinando un link:../vmware/index.html["Sistema VMware"], selezionare i file appropriati.


[cols="1a,1a"]
|===
| Percorso e nome del file | Descrizione 


| ./vsphere/README  a| 
Un file di testo che descrive tutti i file contenuti nel file di download di StorageGRID.



| ./vsphere/NLF000000.txt  a| 
Licenza gratuita che non fornisce alcun diritto di supporto per il prodotto.



| ./vsphere/NetApp-SG-version-SHA.vmdk  a| 
Il file del disco della macchina virtuale utilizzato come modello per la creazione di macchine virtuali con nodo grid.



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
Il file modello Open Virtualization Format (`.ovf`) e il file manifest ) (`.mf`per la distribuzione del nodo amministrativo primario.



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
Il file modello (`.ovf`) e il file manifesto ) (`.mf`per la distribuzione di nodi Admin non primari.



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
Il file modello (`.ovf`) e il file manifesto ) (`.mf`per la distribuzione dei nodi Gateway.



| ./vsphere/vsphere-storage.ovf ./vsphere/vsphere-storage.mf  a| 
Il file modello (`.ovf`) e il file manifesto ) (`.mf`per la distribuzione dei nodi di archiviazione basati su macchine virtuali.



| Tool di scripting per la distribuzione | Descrizione 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
Uno script della shell Bash utilizzato per automatizzare l'implementazione dei nodi virtual grid.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
Un file di configurazione di esempio da utilizzare con `deploy-vsphere-ovftool.sh` lo script.



| ./vsphere/configure-storagegrid.py  a| 
Script Python utilizzato per automatizzare la configurazione di un sistema StorageGRID.



| ./vsphere/configure-sga.py  a| 
Script Python utilizzato per automatizzare la configurazione delle appliance StorageGRID.



| ./vsphere/storagegrid-ssoauth.py  a| 
Esempio di script Python che è possibile utilizzare per accedere all'API Grid Management quando è attivato il Single Sign-on (SSO). È anche possibile utilizzare questo script per l'integrazione federate Ping.



| ./vsphere/configure-storagegrid.sample.json  a| 
Un file di configurazione di esempio da utilizzare con `configure-storagegrid.py` lo script.



| ./vsphere/configure-storagegrid.blank.json  a| 
Un file di configurazione vuoto da utilizzare con `configure-storagegrid.py` lo script.



| ./vsphere/storagegrid-ssoauth-azure.py  a| 
Esempio di script Python che è possibile utilizzare per accedere all'API Grid Management quando SSO (Single Sign-on) è attivato utilizzando Active Directory o Ping Federate.



| ./vsphere/storagegrid-ssoauth-azure.js  a| 
Uno script di supporto chiamato dallo script Python associato `storagegrid-ssoauth-azure.py` per eseguire interazioni SSO con Azure.



| ./vsphere/extra/schemi api  a| 
Schemi API per StorageGRID.

*Nota*: Prima di eseguire un aggiornamento, è possibile utilizzare questi schemi per confermare che qualsiasi codice scritto per utilizzare le API di gestione StorageGRID sarà compatibile con la nuova release di StorageGRID se non si dispone di un ambiente StorageGRID non in produzione per il test di compatibilità degli aggiornamenti.

|===
. Se si sta ripristinando un sistema basato su appliance StorageGRID, selezionare i file appropriati.


[cols="1a,1a"]
|===
| Percorso e nome del file | Descrizione 


| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
PACCHETTO DEB per l'installazione delle immagini del nodo StorageGRID sulle appliance.



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
MD5 checksum per il file `/debs/storagegridwebscale-
images-version-SHA.deb`.

|===

NOTE: Per l'installazione dell'appliance, questi file sono necessari solo se è necessario evitare il traffico di rete. L'appliance può scaricare i file richiesti dal nodo di amministrazione principale.
