---
permalink: maintain/modifying-dns-configuration-for-single-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, dns, modify dns 
summary: 'Invece di configurare il DNS a livello globale per l"intera implementazione, è possibile eseguire uno script per configurare il DNS in modo diverso per ciascun nodo della griglia.' 
---
= Modificare la configurazione DNS per un nodo griglia singolo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Invece di configurare il DNS a livello globale per l'intera implementazione, è possibile eseguire uno script per configurare il DNS in modo diverso per ciascun nodo della griglia.

In generale, utilizzare l'opzione *MANUTENZIONE* > *rete* > *server DNS* in Grid Manager per configurare i server DNS. Utilizzare il seguente script solo se è necessario utilizzare server DNS diversi per nodi griglia diversi.

.Fasi
. Accedere al nodo di amministrazione principale:
+
.. Immettere il seguente comando: `ssh admin@_primary_Admin_Node_IP_`
.. Immettere la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla directory principale: `su -`
.. Immettere la password elencata nel `Passwords.txt` file.
+
Quando si è collegati come root, il prompt cambia da `$` a `#`.

.. Aggiungere la chiave privata SSH all'agente SSH. Immettere: `ssh-add`
.. Immettere la password di accesso SSH elencata nel `Passwords.txt` file.


. [[log_in_to_node]]accedere al nodo da aggiornare con una configurazione DNS personalizzata: `ssh _node_IP_address_`
. Eseguire lo script di installazione DNS: `setup_resolv.rb.`
+
Lo script risponde con l'elenco dei comandi supportati.

+
[listing]
----
Tool to modify external name servers

available commands:
  add search <domain>
               add a specified domain to search list
               e.g.> add search netapp.com
  remove search <domain>
               remove a specified domain from list
               e.g.> remove search netapp.com
  add nameserver <ip>
               add a specified IP address to the name server list
               e.g.> add nameserver 192.0.2.65
  remove nameserver <ip>
               remove a specified IP address from list
               e.g.> remove nameserver 192.0.2.65
  remove nameserver all
               remove all nameservers from list
  save         write configuration to disk and quit
  abort        quit without saving changes
  help         display this help message


Current list of name servers:
    192.0.2.64
Name servers inherited from global DNS configuration:
    192.0.2.126
    192.0.2.127
Current list of search entries:
    netapp.com

Enter command [`add search <domain>|remove search <domain>|add nameserver <ip>`]
              [`remove nameserver <ip>|remove nameserver all|save|abort|help`]
----
. Aggiungere l'indirizzo IPv4 di un server che fornisce il servizio dei nomi di dominio per la rete: `add <nameserver IP_address>`
. Ripetere il `add nameserver` comando per aggiungere i server dei nomi.
. Seguire le istruzioni richieste per altri comandi.
. Salvare le modifiche e uscire dall'applicazione: `save`
. [[close_cmd_shell]]chiudere la shell dei comandi sul server: `exit`
. Per ciascun nodo della griglia, ripetere i passaggi da <<log_in_to_node,accesso al nodo>> a <<close_cmd_shell,chiudere la shell dei comandi>>.
. Se non si richiede più l'accesso senza password ad altri server, rimuovere la chiave privata dall'agente SSH. Immettere: `ssh-add -D`

