---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: È possibile spostare il servizio ADC in un altro nodo di archiviazione nello stesso sito. 
---
= Spostare il servizio ADC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile spostare il servizio ADC in un altro nodo di archiviazione nello stesso sito.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone di link:admin-group-permissions.html["Autorizzazione di manutenzione o di accesso root"].
* Il nodo di origine contiene il servizio ADC.
* Il nodo di destinazione non contiene il servizio ADC.
* Il nodo di destinazione è un nodo solo metadati o combinato (dati di oggetti e metadati).
* Il nodo di origine e il nodo di destinazione si trovano sullo stesso sito.


.A proposito di questa attività
Utilizzare la procedura Sposta ADC quando si desidera:

* Decommissionamento di un nodo di storage che contiene il servizio ADC
* Convertire un nodo ADC in un nodo solo dati
* Aggiungere un nodo per eseguire le attività correlate ad ADC


Quando si desidera smantellare un nodo di archiviazione o link:../maintain/convert-to-data-only-node.html["Convertire un nodo di storage in un nodo solo dati"], potrebbe essere necessario utilizzare prima la procedura Sposta ADC. È necessario assicurarsi che link:../maintain/understanding-adc-service-quorum.html["Il quorum ADC viene mantenuto"].

Questa procedura sposta i servizi ADC, IDNT, ACCT e RSM da un nodo di archiviazione a un altro nello stesso sito. I servizi RSM e ACCT dipendono dal servizio ADC, quindi si spostano automaticamente quando il servizio ADC si sposta.

.Fasi
. Registrare gli ID dei nodi di origine e di destinazione.
+
Nell'API di gestione griglia, l'ID del nodo di origine viene indicato come `sourceNodeId`. L'ID del nodo di destinazione è indicato come `targetNodeId`.

. Nella parte superiore di Grid Manager, selezionare l'icona della guida e selezionare *documentazione API*.
. Selezionare *Vai alla documentazione API privata*.
. Selezionare l' `POST /private/move-adc/start`operazione. Per ulteriori informazioni, fare riferimento link:../admin/using-grid-management-api.html#issue-api-requests["Emettere richieste API"] a.
+
Ciascun nodo viene riavviato durante la procedura.

. È possibile utilizzare `GET /private/move-adc` per monitorare la procedura. Se si verificano errori, selezionare `POST /private/move-adc/retry` per riprovare la procedura.
. link:../maintain/downloading-recovery-package.html["Scaricare un pacchetto di ripristino"] al termine di questa procedura.

