---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: È possibile spostare il servizio ADC su un altro nodo di archiviazione nello stesso sito. 
---
= Spostare il servizio ADC in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile spostare il servizio ADC su un altro nodo di archiviazione nello stesso sito.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Hailink:../admin/admin-group-permissions.html["Autorizzazione di manutenzione o di accesso root"] .
* Il nodo sorgente contiene il servizio ADC.
* Il nodo di destinazione non contiene il servizio ADC.
* Il nodo di destinazione è un nodo contenente solo metadati o un nodo combinato (metadati e dati oggetto).
* Il nodo sorgente e il nodo di destinazione si trovano nello stesso sito.


.A proposito di questa attività
Usa la procedura Sposta ADC per spostare manualmente il servizio ADC tra i nodi di storage. Ad esempio, potresti voler ridistribuire i servizi ADC tra i nodi o spostare il servizio ADC su un nodo con prestazioni superiori.

Questa procedura sposta i servizi ADC, IDNT, ACCT e RSM da un nodo di archiviazione a un altro nello stesso sito.  I servizi RSM, IDNT e ACCT dipendono dal servizio ADC, pertanto vengono spostati automaticamente quando si sposta il servizio ADC.

[NOTE]
====
* Non devi spostare manualmente il servizio ADC prima di link:../maintain/convert-to-data-only-node.html["conversione di un nodo di archiviazione in un nodo solo dati"] o decommissionare un Storage Node. Queste procedure spostano automaticamente il servizio ADC quando richiesto. Consulta link:../maintain/understanding-adc-service-quorum.html["Che cos'è il quorum dell'ADC?"] per i dettagli sui requisiti.
* StorageGRID sposta il servizio ADC sui nodi di storage più recenti che soddisfano i requisiti per l'hosting del servizio.


====
.Fasi
. Registrare gli ID dei nodi di origine e di destinazione.
+
Nell'API di gestione della griglia, l'ID del nodo sorgente è denominato `sourceNodeId` .  L'ID del nodo di destinazione è denominato `targetNodeId` .

. Nella parte superiore di Grid Manager, selezionare l'icona della guida e selezionare *documentazione API*.
. Selezionare *Vai alla documentazione API privata*.
. Seleziona il `POST /private/move-adc/start` operazione. Fare riferimento a link:../admin/using-grid-management-api.html#issue-api-requests["Emettere richieste API"] per maggiori informazioni.
+
Durante la procedura, i due nodi si riavvieranno in sequenza.  Il nodo sorgente si riavvia per primo, seguito dal nodo di destinazione.

. Puoi usare `GET /private/move-adc` per monitorare la procedura.  Se si verificano errori, selezionare `POST /private/move-adc/retry` per riprovare la procedura.
. link:../maintain/downloading-recovery-package.html["Scarica un pacchetto di ripristino"]dopo aver completato questa procedura.

