---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: È possibile spostare il servizio ADC su un altro nodo di archiviazione nello stesso sito. 
---
= Spostare il servizio ADC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile spostare il servizio ADC su un altro nodo di archiviazione nello stesso sito.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Hailink:../admin/admin-group-permissions.html["Autorizzazione di manutenzione o di accesso root"] .
* Il nodo sorgente contiene il servizio ADC.
* Il nodo di destinazione non contiene il servizio ADC.
* Il nodo di destinazione è un nodo contenente solo metadati o un nodo combinato (metadati e dati oggetto).
* Il nodo sorgente e il nodo di destinazione si trovano nello stesso sito.


.A proposito di questa attività
Utilizzare la procedura Sposta ADC quando si desidera:

* Disattivare un nodo di archiviazione che ospita il servizio ADC
* Convertire un nodo di archiviazione che ospita il servizio ADC in un nodo di archiviazione solo dati


Quando si desidera dismettere un nodo di archiviazione olink:../maintain/convert-to-data-only-node.html["convertire un nodo di archiviazione in un nodo solo dati"] , potrebbe essere necessario prima utilizzare la procedura Sposta ADC.  Dovrai assicurarti che illink:../maintain/understanding-adc-service-quorum.html["Il quorum dell'ADC è mantenuto"] .

Questa procedura sposta i servizi ADC, IDNT, ACCT e RSM da un nodo di archiviazione a un altro nello stesso sito.  I servizi RSM, IDNT e ACCT dipendono dal servizio ADC, pertanto vengono spostati automaticamente quando si sposta il servizio ADC.

.Fasi
. Registrare gli ID dei nodi di origine e di destinazione.
+
Nell'API di gestione della griglia, l'ID del nodo sorgente è denominato `sourceNodeId` .  L'ID del nodo di destinazione è denominato `targetNodeId` .

. Nella parte superiore di Grid Manager, selezionare l'icona della guida e selezionare *documentazione API*.
. Selezionare *Vai alla documentazione API privata*.
. Seleziona il `POST /private/move-adc/start` operazione. Fare riferimento a link:../admin/using-grid-management-api.html#issue-api-requests["Emettere richieste API"] per maggiori informazioni.
+
Durante la procedura, i due nodi si riavvieranno in sequenza.  Il nodo sorgente si riavvia per primo, seguito dal nodo di destinazione.

. Puoi usare `GET /private/move-adc` per monitorare la procedura.  Se si verificano errori, selezionare `POST /private/move-adc/retry` per riprovare la procedura.
. link:../maintain/downloading-recovery-package.html["Scarica un pacchetto di ripristino"]dopo aver completato questa procedura.

