---
permalink: maintain/preparing-appliance-for-reinstallation-platform-replacement-only.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, reinstallation appliance, reinstall appliance 
summary: 'Durante il ripristino di un nodo Grid ospitato su un"appliance di servizi, è necessario preparare l"appliance per la reinstallazione del software StorageGRID.' 
---
= Preparazione dell'appliance per la reinstallazione (solo sostituzione della piattaforma)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante il ripristino di un nodo Grid ospitato su un'appliance di servizi, è necessario preparare l'appliance per la reinstallazione del software StorageGRID.

Eseguire questa procedura solo se si sta sostituendo un nodo guasto ospitato su un'appliance di servizi. Non seguire questi passaggi se il nodo guasto era originariamente ospitato su un host VMware o Linux.

.Fasi
. Accedere al nodo Grid guasto:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Immettere la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla directory principale: `su -`
.. Immettere la password elencata nel `Passwords.txt` file.


+
Quando si è collegati come root, il prompt cambia da `$` a `#`.

. Preparare l'appliance per l'installazione del software StorageGRID. Immettere: `sgareinstall`
. Quando viene richiesto di continuare, immettere: `y`
+
L'apparecchio si riavvia e la sessione SSH termina. In genere, il programma di installazione dell'appliance StorageGRID richiede circa 5 minuti, anche se in alcuni casi potrebbe essere necessario attendere fino a 30 minuti.

+
L'appliance di servizi viene reimpostata e i dati sul nodo Grid non sono più accessibili. Gli indirizzi IP configurati durante il processo di installazione originale devono rimanere intatti; tuttavia, si consiglia di confermarli al termine della procedura.

+
Dopo aver eseguito il `sgareinstall` comando, tutti gli account, le password e le chiavi SSH con provisioning StorageGRID vengono rimossi e vengono generate nuove chiavi host.


