---
permalink: maintain/recovering-from-primary-admin-node-failures.html 
sidebar: sidebar 
keywords: storagegrid, recover, primary admin node failure 
summary: 'È necessario completare un set specifico di attività per eseguire il ripristino da un guasto primario del nodo di amministrazione. Il nodo di amministrazione primario ospita il servizio CMN (Configuration Management Node) per la griglia.' 
---
= Ripristina il nodo Admin primario di StorageGRID utilizzando lo stesso nodo Admin primario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario completare un set specifico di attività per eseguire il ripristino da un guasto primario del nodo di amministrazione. Il nodo di amministrazione primario ospita il servizio CMN (Configuration Management Node) per la griglia.


CAUTION: Devi riparare o sostituire tempestivamente un nodo di amministrazione primario guasto, altrimenti potresti non riuscire a eseguire alcune procedure di manutenzione.

Seguire questi passaggi di alto livello per ripristinare un nodo amministrativo primario:

. link:copying-audit-logs-from-failed-primary-admin-node.html["Copia i registri di controllo dal nodo di amministrazione primario non riuscito"]
. link:replacing-primary-admin-node.html["Sostituire il nodo amministrativo primario"]
. link:configuring-replacement-primary-admin-node.html["Configurare il nodo amministrativo primario sostitutivo"]
. link:assess-hotfix-requirement-during-primary-admin-node-recovery.html["Determinare se esiste un requisito di hotfix per il nodo amministrativo primario recuperato"]
. link:restoring-audit-log-on-recovered-primary-admin-node.html["Ripristinare il registro di controllo sul nodo amministrativo primario recuperato"]
. link:restoring-admin-node-database-primary-admin-node.html["Ripristinare il database del nodo amministrativo quando si ripristina un nodo amministrativo primario"]
. link:restoring-prometheus-metrics-primary-admin-node.html["Ripristinare le metriche Prometheus durante il ripristino di un nodo amministrativo primario"]

