---
permalink: maintain/reviewing-warnings-about-storage-volume-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, volume warning 
summary: Prima di ripristinare i volumi di storage guasti per un nodo di storage, è necessario esaminare i seguenti avvisi. 
---
= Avvertenze per il ripristino del volume di archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di ripristinare volumi di archiviazione non riusciti per un nodo di archiviazione, esaminare i seguenti avvisi.

I volumi di storage (o rangedb) in un nodo di storage sono identificati da un numero esadecimale, noto come ID del volume. Ad esempio, 0000 è il primo volume e 000F è il sedicesimo volume. Il primo archivio di oggetti (volume 0) su ciascun nodo di storage utilizza fino a 4 TB di spazio per i metadati degli oggetti e le operazioni del database Cassandra; qualsiasi spazio rimanente su tale volume viene utilizzato per i dati degli oggetti. Tutti gli altri volumi di storage vengono utilizzati esclusivamente per i dati a oggetti.

Il database Cassandra potrebbe essere ricostruito come parte della procedura di ripristino del volume se:

* Il volume 0 non funziona e viene recuperato.
* Il disco di sistema e uno o più volumi di storage si guastano e vengono ripristinati.


Quando Cassandra viene ricostruita, il sistema utilizza le informazioni provenienti da altri nodi di archiviazione.  Se Cassandra è stata ricostruita di recente, i dati di Cassandra potrebbero non essere ancora coerenti in tutta la griglia.  Se troppi nodi di archiviazione sono offline:

* Alcuni dati di Cassandra potrebbero non essere disponibili.
* Potrebbe verificarsi una perdita di dati.



CAUTION: Se più di un nodo di archiviazione è guasto (o è offline), contattare l'assistenza tecnica.  Non eseguire la seguente procedura di ripristino.  Potrebbe verificarsi una perdita di dati. Per ulteriori informazioni, fare riferimento a link:how-site-recovery-is-performed-by-technical-support.html["Come il supporto tecnico recupera un sito"] .


CAUTION: Se le regole ILM sono configurate per archiviare una sola copia replicata e la copia esiste su un volume di archiviazione che ha subito un errore, non sarà possibile ripristinare l'oggetto.

.Informazioni correlate
link:warnings-and-considerations-for-grid-node-recovery.html["Avvertenze e considerazioni per il ripristino del nodo grid"]
