---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: Prima di ripristinare un disco di sistema guasto di un nodo di storage, esaminare gli avvisi e le considerazioni generali per il ripristino del nodo di rete e i seguenti avvisi specifici. 
---
= Avvisi per il ripristino delle unità del sistema Storage Node
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di ripristinare un'unità di sistema guasta di un nodo di archiviazione, esaminare le avvertenze generali link:warnings-and-considerations-for-grid-node-recovery.html["avvertenze e considerazioni per il ripristino del nodo grid"] e specifiche riportate di seguito.

I nodi di archiviazione dispongono di un database Cassandra che include metadati degli oggetti.  Il database Cassandra potrebbe essere ricostruito se:

* Un volume di archiviazione si guasta e viene recuperato.
* Il disco di sistema e uno o più volumi di storage si guastano e vengono ripristinati.


Quando Cassandra viene ricostruita, il sistema utilizza le informazioni provenienti da altri nodi di archiviazione.  Se Cassandra è stata ricostruita di recente, i dati di Cassandra potrebbero non essere ancora coerenti in tutta la griglia.  Se troppi nodi di archiviazione sono offline:

* Alcuni dati di Cassandra potrebbero non essere disponibili.
* Potrebbe verificarsi una perdita di dati.



CAUTION: Se più di un nodo di archiviazione è guasto (o è offline), contattare l'assistenza tecnica.  Non eseguire la seguente procedura di ripristino.  Potrebbe verificarsi una perdita di dati. Per ulteriori informazioni, fare riferimento a link:how-site-recovery-is-performed-by-technical-support.html["Come il supporto tecnico recupera un sito"] .


CAUTION: Se questo nodo di storage è in modalità di manutenzione in sola lettura per consentire il recupero di oggetti da parte di un altro nodo di storage con volumi di storage guasti, ripristinare i volumi sul nodo di storage con volumi di storage guasti prima di ripristinare questo nodo di storage guasto. Vedere le istruzioni per link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["ripristino in seguito a un errore del volume di storage in cui il disco di sistema è intatto"].


CAUTION: Se le regole ILM sono configurate in modo da memorizzare una sola copia replicata e la copia esiste su un volume di storage che ha avuto esito negativo, non sarà possibile ripristinare l'oggetto.
