---
permalink: maintain/selecting-node-recovery-procedure.html 
sidebar: sidebar 
keywords: storagegrid, recover, procedure 
summary: Seleziona la procedura di ripristino corretta per il tipo di nodo che ha avuto un guasto. 
---
= Selezionare la procedura di ripristino del nodo StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seleziona la procedura di ripristino corretta per il tipo di nodo che ha avuto un guasto.

[cols="1a,2a"]
|===
| Nodo della griglia | Procedura di recovery 


 a| 
Nodo di storage
 a| 
La procedura di ripristino dello Storage Node dipende dal tipo di errore.

link:recovering-from-storage-node-failures.html["Ripristino da guasti del nodo di storage"]



 a| 
Nodo Admin
 a| 
La procedura Admin Node (nodo amministratore) dipende dalla necessità di ripristinare il nodo amministratore primario o un nodo amministratore non primario.

link:recovering-from-admin-node-failures.html["Ripristino da errori del nodo di amministrazione"]



 a| 
Nodo gateway
 a| 
link:replacing-gateway-node.html["Ripristino da guasti del nodo gateway"]



 a| 
Nodo di archiviazione
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/recovering-from-archive-node-failures.html["Ripristino da guasti al nodo di archivio (sito di documentazione StorageGRID 11,8)"^]

|===

NOTE: Se un server che ospita più di un nodo della griglia si guasta, puoi ripristinare i nodi in qualsiasi ordine. Tuttavia, se il server guasto ospita il nodo di amministrazione primario e non esistono nodi di amministrazione non primari, devi ripristinare prima il nodo di amministrazione primario. Ripristinare prima il nodo di amministrazione primario impedisce che il ripristino degli altri nodi si blocchi mentre cercano di contattare il nodo di amministrazione primario. Se è disponibile un nodo di amministrazione non primario, puoi usarlo per ripristinare gli altri nodi, così quei ripristini possono procedere senza contattare il nodo di amministrazione primario.
