---
permalink: maintain/selecting-start-recovery-to-configure-storage-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage node 
summary: Dopo aver sostituito un nodo di storage, selezionare Avvia ripristino in Grid Manager per configurare il nuovo nodo come sostituzione del nodo guasto. 
---
= Seleziona Avvia ripristino per configurare il nodo di archiviazione StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver sostituito un nodo di storage, selezionare Avvia ripristino in Grid Manager per configurare il nuovo nodo come sostituzione del nodo guasto.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone di link:../admin/admin-group-permissions.html["Autorizzazione di manutenzione o di accesso root"].
* Si dispone della passphrase di provisioning.
* Il nodo sostitutivo è stato implementato e configurato.
* Si dispone della data di inizio di qualsiasi intervento di riparazione per i dati codificati per la cancellazione.


.A proposito di questa attività
Se Storage Node è installato come container su un host Linux, eseguire questa operazione solo se si verifica una delle seguenti condizioni:

* È stato necessario utilizzare il `--force` flag per importare il nodo o è stato emesso `storagegrid node force-recovery _node-name_`
* Era necessario eseguire una reinstallazione completa del nodo oppure ripristinare /var/local.


.Fasi
. Accedi al nodo amministratore principale. Se il nodo amministratore principale non è disponibile, usa un nodo amministratore non primario, se presente.
. Dal Grid Manager, seleziona *Manutenzione* > *Attività* > *Ripristino nodo*.
. Selezionare il nodo della griglia che si desidera ripristinare nell'elenco Pending Nodes (nodi in sospeso).
+
I nodi vengono visualizzati nell'elenco dopo un errore, ma non è possibile selezionare un nodo fino a quando non è stato reinstallato e pronto per il ripristino.

. Inserisci la *passphrase di provisioning*.
. Fai clic su *Avvia ripristino*.
. Monitora l'avanzamento del ripristino selezionando *Manutenzione* > *Attività* > *Ripristino nodo* e visualizzando l'avanzamento del ripristino.
+
** Se il nodo della griglia raggiunge la fase "In attesa di passaggi manuali", devi link:../maintain/remounting-and-reformatting-storage-volumes-manual-steps.html["rimontare e riformattare manualmente i volumi di archiviazione"]. Al termine dei passaggi manuali, procedi a link:../maintain/restoring-object-data-to-storage-volume.html["ripristinare i dati degli oggetti nei volumi"].
** Se il ripristino del nodo della griglia è passato dallo stato *In corso* allo stato *Ripristinato* senza passare attraverso la fase "In attesa di interventi manuali", non è richiesta alcuna ulteriore azione.
+
[NOTE]
====
In qualsiasi momento durante il ripristino, puoi selezionare *Reset* per avviare un nuovo ripristino. Viene visualizzata una finestra di dialogo che indica che il nodo rimarrà in uno stato indeterminato se resetti la procedura.

Se vuoi riprovare il ripristino dopo aver reimpostato la procedura, devi riportare il nodo dell'appliance a uno stato pre-installazione, come segue:

*** *VMware*: Eliminare il nodo virtual grid implementato. Quindi, quando si è pronti per riavviare il ripristino, ridistribuire il nodo.
*** *Linux*: Riavviare il nodo eseguendo questo comando sull'host Linux: `storagegrid node force-recovery _node-name_`


====



