---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: 'Il quorum ADC garantisce che un numero minimo di servizi Administrative Domain Controller (ADC) rimanga disponibile in ogni sito. StorageGRID sposta automaticamente il servizio ADC durante il decommission quando necessario.' 
---
= Cos'è il quorum ADC di StorageGRID?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il quorum ADC garantisce che un numero minimo di servizi Administrative Domain Controller (ADC) rimanga disponibile in ogni sito. StorageGRID sposta automaticamente il servizio ADC durante il decommission quando necessario.

Il servizio ADC, presente in alcuni nodi di archiviazione, mantiene le informazioni sulla topologia della griglia e fornisce servizi di configurazione alla griglia. Il sistema StorageGRID richiede un quorum di servizi ADC per essere sempre disponibile in ogni sito.

Non è possibile decommissionare un nodo di storage se la rimozione del nodo causerebbe il mancato rispetto del quorum di ADC. Per soddisfare il quorum ADC durante una disattivazione, è necessario che almeno tre nodi di archiviazione in ogni sito dispongano del servizio ADC. Se in un sito sono presenti più di tre nodi di archiviazione con il servizio ADC, la maggior parte di questi nodi deve rimanere disponibile dopo lo smantellamento: `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: Prestare attenzione quando si disattivano i nodi di storage in un grid che contiene nodi solo metadati basati su software. Se tutti i nodi configurati per l'archiviazione di _entrambi_ oggetti e metadati vengono dismessi, la possibilità di archiviare oggetti viene rimossa dalla griglia. Per ulteriori informazioni sui nodi di storage solo per metadati, vedere link:../primer/what-storage-node-is.html#types-of-storage-nodes["Tipi di nodi storage"].

Ad esempio, si supponga che un sito attualmente includa sei nodi di storage con servizi ADC e che si desideri smantellare tre nodi di storage. A causa del requisito di quorum di ADC, è necessario completare due procedure di decommissionamento, come indicato di seguito:

* Nella prima procedura di decommissionamento, è necessario assicurarsi che siano disponibili quattro nodi di archiviazione con servizi ADC: `((0.5 * 6) + 1)`. Ciò significa che all'inizio è possibile decommissionare solo due nodi di storage.
* Nella seconda procedura di dismissione, è possibile rimuovere il terzo nodo di archiviazione perché il quorum ADC richiede ora che rimangano disponibili solo tre servizi ADC: `((0.5 * 4) + 1)` .


Quando decommissioni un nodo di archiviazione che ospita il servizio ADC, StorageGRID sposta automaticamente il servizio ADC su un altro nodo di archiviazione nello stesso sito se la decommission portasse il numero di nodi ADC del sito al di sotto del quorum. Lo spostamento automatico richiede che tutti i nodi della grid siano connessi e che siano disponibili nodi di archiviazione non ADC nello stesso sito per ricevere il servizio. La procedura di decommission mantiene un minimo di tre nodi di archiviazione ADC per sito. Ad esempio, se decommissioni quattro o sei nodi ADC in un sito, dopo la procedura rimarranno tre nodi di archiviazione ADC, a condizione che siano presenti nodi non ADC disponibili nello stesso sito.

Se il servizio ADC non può essere spostato automaticamente, puoi link:move-adc-service.html["spostare manualmente il servizio ADC"] su un altro Storage Node nello stesso sito oppure link:../expand/index.html["aggiungi un nuovo Storage Node in un'espansione"] e specificare che debba avere un servizio ADC. Poi puoi decommissionare lo Storage Node esistente senza influire sul quorum.
