---
permalink: expand/adding-grid-nodes-to-add-capabilities.html 
sidebar: sidebar 
keywords: grid nodes, expand, expansion, site, add 
summary: È possibile aggiungere ridondanza o funzionalità aggiuntive a un sistema StorageGRID aggiungendo nuovi nodi grid ai siti esistenti. 
---
= Aggiungi nodi grid per aggiungere funzionalità al tuo sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere ridondanza o funzionalità aggiuntive a un sistema StorageGRID aggiungendo nuovi nodi grid ai siti esistenti.

Ad esempio, è possibile scegliere di aggiungere nodi gateway da utilizzare in un gruppo ad alta disponibilità (ha) oppure aggiungere un nodo amministratore in un sito remoto per consentire il monitoraggio utilizzando un nodo locale.

È possibile aggiungere uno o più dei seguenti tipi di nodi a uno o più siti esistenti in una singola operazione di espansione:

* Nodi amministrativi non primari
* Nodi di storage
* Nodi gateway


Durante la preparazione all'aggiunta di nodi di rete, tenere presente le seguenti limitazioni:

* Il nodo di amministrazione primario viene implementato durante l'installazione iniziale. Non è possibile aggiungere un nodo amministratore primario durante un'espansione.
* È possibile aggiungere nodi di storage e altri tipi di nodi nella stessa espansione.
* Quando si aggiungono nodi di storage, è necessario pianificare attentamente il numero e la posizione dei nuovi nodi. Vedere link:../expand/guidelines-for-adding-object-capacity.html["Linee guida per l'aggiunta della capacità degli oggetti"].
* Se l'opzione *Imposta nuovo nodo predefinito* è *Non attendibile* nella scheda Reti client non attendibili nella pagina Controllo firewall, le applicazioni client che si connettono ai nodi di espansione tramite la rete client devono connettersi tramite una porta endpoint del bilanciatore del carico (*Configurazione* > *Sicurezza* > *Controllo firewall*).  Vedi le istruzioni perlink:../admin/configure-firewall-controls.html["modificare l'impostazione di sicurezza per il nuovo nodo"] e alink:../admin/configuring-load-balancer-endpoints.html["configurare gli endpoint del bilanciamento del carico"] .

