---
sidebar: sidebar 
permalink: expand/copying-audit-logs.html 
keywords: copy audit log, Admin Node expansion, 
summary: 'Quando si aggiunge un nuovo nodo amministrativo tramite una procedura di espansione, il suo servizio AMS registra solo gli eventi e le azioni che si verificano dopo l"adesione al sistema.  Se necessario, è possibile copiare i registri di controllo da un nodo di amministrazione installato in precedenza al nuovo nodo di amministrazione di espansione, in modo che sia sincronizzato con il resto del sistema StorageGRID .' 
---
= Copia dei registri di audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si aggiunge un nuovo nodo amministrativo tramite una procedura di espansione, il suo servizio AMS registra solo gli eventi e le azioni che si verificano dopo l'adesione al sistema.  Se necessario, è possibile copiare i registri di controllo da un nodo di amministrazione installato in precedenza al nuovo nodo di amministrazione di espansione, in modo che sia sincronizzato con il resto del sistema StorageGRID .

.Prima di iniziare
* Sono state completate le fasi di espansione richieste per aggiungere un nodo di amministrazione.
* Si dispone del `Passwords.txt` file.


.A proposito di questa attività
Per rendere disponibili i messaggi di audit storici su un nuovo nodo di amministrazione, è necessario copiare manualmente i file di log di audit da un nodo di amministrazione esistente al nodo di amministrazione dell'espansione.

[NOTE]
====
Per impostazione predefinita, le informazioni di controllo vengono inviate a `localaudit` accedi a ciascun nodo.  Per utilizzare questa procedura, è necessario aver configurato i nodi di amministrazione come destinazione di controllo come segue:

* Hai configurato *Nodi amministrativi/nodi locali* come destinazione del registro.
* Hai configurato *Admin Nodes e server syslog esterno* come destinazione del registro.


Fare riferimento alink:../monitor/configure-audit-messages.html["Configurare i messaggi di controllo e il server syslog esterno"] per i dettagli.

====
.Fasi
. Accedere al nodo di amministrazione principale:
+
.. Immettere il seguente comando: `ssh _admin@_primary_Admin_Node_IP_`
.. Immettere la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla directory principale: `su -`
.. Immettere la password elencata nel `Passwords.txt` file.
+
Quando si è collegati come root, il prompt cambia da `$` a `#`.



. Arrestare il servizio AMS per evitare che crei un nuovo file: `service ams stop`
. Accedere alla directory di esportazione della verifica:
+
`cd /var/local/audit/export/`

. Rinomina la fonte `audit.log` file per garantire che non sovrascriva il file sul nodo di amministrazione di espansione in cui lo stai copiando:
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. Copiare tutti i file di registro di controllo nella posizione di destinazione sul nodo di amministrazione di espansione:
+
`scp -p * _IP_address_:/var/local/audit/export/`

. Se viene richiesta la passphrase per `/root/.ssh/id_rsa`, immettere la password di accesso SSH per il nodo di amministrazione primario elencato nel `Passwords.txt` file.
. Ripristinare il file originale `audit.log`:
+
`mv _new_name_.txt audit.log`

. Avviare il servizio AMS:
+
`service ams start`

. Disconnettersi dal server:
+
`exit`

. Accedere al nodo di amministrazione dell'espansione:
+
.. Immettere il seguente comando: `ssh admin@_expansion_Admin_Node_IP_`
.. Immettere la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla directory principale: `su -`
.. Immettere la password elencata nel `Passwords.txt` file.
+
Quando si è collegati come root, il prompt cambia da `$` a `#`.



. Aggiornare le impostazioni dell'utente e del gruppo per i file di log di controllo:
+
`cd /var/local/audit/export/`

+
`chown ams-user:bycast *`

. Disconnettersi dal server:
+
`exit`


