---
permalink: expand/gather-required-materials.html 
sidebar: sidebar 
keywords: expand, expansion, planning, storagrid files 
summary: 'Prima di eseguire un"operazione di espansione, raccogliere i materiali e installare e configurare eventuali nuovi hardware e reti.' 
---
= Raccogliere il materiale necessario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di eseguire un'operazione di espansione, raccogliere i materiali e installare e configurare eventuali nuovi hardware e reti.

[cols="1a,2a"]
|===
| Elemento | Note 


 a| 
Archivio di installazione di StorageGRID
 a| 
Se si aggiungono nuovi nodi di griglia o un nuovo sito, è necessario scaricare ed estrarre l'archivio di installazione di StorageGRID. È necessario utilizzare la stessa versione attualmente in esecuzione sulla griglia.

Per ulteriori informazioni, vedere le istruzioni di <<download-and-extract-install-files,Download ed estrazione dei file di installazione di StorageGRID>>.

*Nota:* non è necessario scaricare i file se si aggiungono nuovi volumi di storage ai nodi di storage esistenti o si installa una nuova appliance StorageGRID.



 a| 
Laptop di assistenza
 a| 
Il laptop di assistenza dispone di quanto segue:

* Porta di rete
* Client SSH (ad esempio, putty)
* link:../admin/web-browser-requirements.html["Browser Web supportato"]




 a| 
`Passwords.txt` file
 a| 
Contiene le password necessarie per accedere ai nodi della griglia sulla riga di comando.  Incluso nel pacchetto di recupero.



 a| 
Passphrase di provisioning
 a| 
La passphrase viene creata e documentata al momento dell'installazione del sistema StorageGRID. La passphrase di provisioning non è contenuta nel `Passwords.txt` file.



 a| 
Documentazione StorageGRID
 a| 
* link:../admin/index.html["Amministrare StorageGRID"]
* link:../release-notes/index.html["Note di rilascio"]
* link:../swnodes/index.html["Istruzioni per l'installazione della piattaforma"]




 a| 
Documentazione aggiornata per la piattaforma
 a| 
Per le versioni supportate, vedere https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità (IMT)"^].

|===


== Scaricare ed estrarre i file di installazione di StorageGRID

.[[download-and-extract-install-files]]
Prima di poter aggiungere nuovi nodi grid o un nuovo sito, è necessario scaricare l'archivio di installazione StorageGRID appropriato ed estrarre i file.

.A proposito di questa attività
È necessario eseguire operazioni di espansione utilizzando la versione di StorageGRID attualmente in esecuzione sulla griglia.

.Fasi
. Andare a https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Download NetApp: StorageGRID"^].
. Selezionare la versione di StorageGRID attualmente in esecuzione nella griglia.
. Accedi con il nome utente e la password del tuo account NetApp.
. Leggere il Contratto di licenza con l'utente finale, selezionare la casella di controllo, quindi selezionare *Accept & Continue* (Accetta e continua).
. Nella colonna *Installa StorageGRID* della pagina di download, selezionare il `.tgz` file o `.zip` per la propria piattaforma.
+
La versione mostrata nel file di archivio dell'installazione deve corrispondere alla versione del software attualmente installato.

+
Utilizzare il `.zip` file se sul laptop di assistenza è in esecuzione Windows.

+
[cols="1a,2a"]
|===
| Piattaforma | Archivio di installazione 


 a| 
RHEL
| `StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz` 


 a| 
Ubuntu o Debian o appliance
| `StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz` 


 a| 
VMware
| `StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-VMware-_uniqueID_.tgz` 


 a| 
OpenStack/Altro hypervisor
 a| 
Per espandere una distribuzione esistente su OpenStack, è necessario implementare una macchina virtuale che esegue una delle distribuzioni Linux supportate elencate sopra e seguire le istruzioni appropriate per Linux.

|===
. Scaricare ed estrarre il file di archivio.
. Seguire la fase appropriata per la piattaforma per scegliere i file necessari, in base alla piattaforma, alla topologia della griglia pianificata e al modo in cui si espanderà il sistema StorageGRID.
+
I percorsi elencati nella fase per ciascuna piattaforma sono relativi alla directory di primo livello installata dal file di archivio.

. Se si sta espandendo un sistema RHEL, selezionare i file appropriati.


[cols="1a,1a"]
|===
| Percorso e nome del file | Descrizione 


| ./rpms/README  a| 
Un file di testo che descrive tutti i file contenuti nel file di download di StorageGRID.



| ./rpms/NLF000000.txt  a| 
Licenza gratuita che non fornisce alcun diritto di supporto per il prodotto.



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
Pacchetto RPM per l'installazione delle immagini del nodo StorageGRID sui vostri host RHEL.



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
Pacchetto RPM per l'installazione del servizio host StorageGRID sugli host RHEL.



| Tool di scripting per la distribuzione | Descrizione 


| ./rpms/configure-storagegrid.py  a| 
Script Python utilizzato per automatizzare la configurazione di un sistema StorageGRID.



| ./rpms/configure-sga.py  a| 
Script Python utilizzato per automatizzare la configurazione delle appliance StorageGRID.



| ./rpms/configure-storagegrid.sample.json  a| 
Un file di configurazione di esempio da utilizzare con `configure-storagegrid.py` lo script.



| ./rpms/storagegrid-ssoauth.py  a| 
Script Python di esempio che è possibile utilizzare per accedere all'API Grid Management quando è attivato il single sign-on. È anche possibile utilizzare questo script per l'integrazione federate Ping.



| ./rpms/configure-storagegrid.blank.json  a| 
Un file di configurazione vuoto da utilizzare con `configure-storagegrid.py` lo script.



| ./rpms/extra/ansible  a| 
Esempio di ruolo e playbook Ansible per la configurazione degli host RHEL per l'implementazione dei container StorageGRID. È possibile personalizzare il ruolo o il manuale in base alle esigenze.



| ./rpms/storagegrid-ssoauth-azure.py  a| 
Esempio di script Python che è possibile utilizzare per accedere all'API Grid Management quando SSO (Single Sign-on) è attivato utilizzando Active Directory o Ping Federate.



| ./rpms/storagegrid-ssoauth-azure.js  a| 
Uno script di supporto chiamato dallo script Python associato `storagegrid-ssoauth-azure.py` per eseguire interazioni SSO con Azure.



| ./rpms/extra/schemi-api  a| 
Schemi API per StorageGRID.

*Nota*: Prima di eseguire un aggiornamento, è possibile utilizzare questi schemi per confermare che qualsiasi codice scritto per utilizzare le API di gestione StorageGRID sarà compatibile con la nuova release di StorageGRID se non si dispone di un ambiente StorageGRID non in produzione per il test di compatibilità degli aggiornamenti.

|===
. Se si sta espandendo un sistema Ubuntu o Debian, selezionare i file appropriati.


[cols="1a,1a"]
|===
| Percorso e nome del file | Descrizione 


| ./debs/README  a| 
Un file di testo che descrive tutti i file contenuti nel file di download di StorageGRID.



| ./debs/NLF000000.txt  a| 
Un file di licenza NetApp non in produzione che è possibile utilizzare per le implementazioni di test e proof of concept.



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
PACCHETTO DEB per l'installazione delle immagini dei nodi StorageGRID su host Ubuntu o Debian.



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
MD5 checksum per il file `/debs/storagegrid-webscale-images-version-SHA.deb`.



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
PACCHETTO DEB per l'installazione del servizio host StorageGRID su host Ubuntu o Debian.



| Tool di scripting per la distribuzione | Descrizione 


| ./debs/configure-storagegrid.py  a| 
Script Python utilizzato per automatizzare la configurazione di un sistema StorageGRID.



| ./debs/configure-sga.py  a| 
Script Python utilizzato per automatizzare la configurazione delle appliance StorageGRID.



| ./debs/storagegrid-ssoauth.py  a| 
Script Python di esempio che è possibile utilizzare per accedere all'API Grid Management quando è attivato il single sign-on. È anche possibile utilizzare questo script per l'integrazione federate Ping.



| ./debs/configure-storagegrid.sample.json  a| 
Un file di configurazione di esempio da utilizzare con `configure-storagegrid.py` lo script.



| ./debs/configure-storagegrid.blank.json  a| 
Un file di configurazione vuoto da utilizzare con `configure-storagegrid.py` lo script.



| ./debs/extra/ansible  a| 
Esempio di manuale e ruolo Ansible per la configurazione di host Ubuntu o Debian per la distribuzione di container StorageGRID. È possibile personalizzare il ruolo o il manuale in base alle esigenze.



| ./debs/storagegrid-ssoauth-azure.py  a| 
Esempio di script Python che è possibile utilizzare per accedere all'API Grid Management quando SSO (Single Sign-on) è attivato utilizzando Active Directory o Ping Federate.



| ./debrs/storagegrid-ssoauth-azure.js  a| 
Uno script di supporto chiamato dallo script Python associato `storagegrid-ssoauth-azure.py` per eseguire interazioni SSO con Azure.



| ./debs/extra/schemi api  a| 
Schemi API per StorageGRID.

*Nota*: Prima di eseguire un aggiornamento, è possibile utilizzare questi schemi per confermare che qualsiasi codice scritto per utilizzare le API di gestione StorageGRID sarà compatibile con la nuova release di StorageGRID se non si dispone di un ambiente StorageGRID non in produzione per il test di compatibilità degli aggiornamenti.

|===
. Se si sta espandendo un sistema VMware, selezionare i file appropriati.


[cols="1a,1a"]
|===
| Percorso e nome del file | Descrizione 


| ./vsphere/README  a| 
Un file di testo che descrive tutti i file contenuti nel file di download di StorageGRID.



| ./vsphere/NLF000000.txt  a| 
Licenza gratuita che non fornisce alcun diritto di supporto per il prodotto.



| ./vsphere/NetApp-SG-version-SHA.vmdk  a| 
Il file del disco della macchina virtuale utilizzato come modello per la creazione di macchine virtuali con nodo grid.



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
Il file modello Open Virtualization Format (`.ovf`) e il file manifest ) (`.mf`per la distribuzione del nodo amministrativo primario.



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
Il file modello (`.ovf`) e il file manifesto ) (`.mf`per la distribuzione di nodi Admin non primari.



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
Il file modello (`.ovf`) e il file manifesto ) (`.mf`per la distribuzione dei nodi Gateway.



| ./vsphere/vsphere-storage.ovf ./vsphere/vsphere-storage.mf  a| 
Il file modello (`.ovf`) e il file manifesto ) (`.mf`per la distribuzione dei nodi di archiviazione basati su macchine virtuali.



| Tool di scripting per la distribuzione | Descrizione 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
Uno script della shell Bash utilizzato per automatizzare l'implementazione dei nodi virtual grid.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
Un file di configurazione di esempio da utilizzare con `deploy-vsphere-ovftool.sh` lo script.



| ./vsphere/configure-storagegrid.py  a| 
Script Python utilizzato per automatizzare la configurazione di un sistema StorageGRID.



| ./vsphere/configure-sga.py  a| 
Script Python utilizzato per automatizzare la configurazione delle appliance StorageGRID.



| ./vsphere/storagegrid-ssoauth.py  a| 
Esempio di script Python che è possibile utilizzare per accedere all'API Grid Management quando è attivato il Single Sign-on (SSO). È anche possibile utilizzare questo script per l'integrazione federate Ping.



| ./vsphere/configure-storagegrid.sample.json  a| 
Un file di configurazione di esempio da utilizzare con `configure-storagegrid.py` lo script.



| ./vsphere/configure-storagegrid.blank.json  a| 
Un file di configurazione vuoto da utilizzare con `configure-storagegrid.py` lo script.



| ./vsphere/storagegrid-ssoauth-azure.py  a| 
Esempio di script Python che è possibile utilizzare per accedere all'API Grid Management quando SSO (Single Sign-on) è attivato utilizzando Active Directory o Ping Federate.



| ./vsphere/storagegrid-ssoauth-azure.js  a| 
Uno script di supporto chiamato dallo script Python associato `storagegrid-ssoauth-azure.py` per eseguire interazioni SSO con Azure.



| ./vsphere/extra/schemi api  a| 
Schemi API per StorageGRID.

*Nota*: Prima di eseguire un aggiornamento, è possibile utilizzare questi schemi per confermare che qualsiasi codice scritto per utilizzare le API di gestione StorageGRID sarà compatibile con la nuova release di StorageGRID se non si dispone di un ambiente StorageGRID non in produzione per il test di compatibilità degli aggiornamenti.

|===
. Se si sta espandendo un sistema basato su appliance StorageGRID, selezionare i file appropriati.



NOTE: Per l'installazione dell'appliance, questi file sono necessari solo se si desidera evitare il traffico di rete.  L'appliance può scaricare i file richiesti dal nodo di amministrazione in cui si esegue la procedura di ripristino.

[cols="1a,1a"]
|===
| Percorso e nome del file | Descrizione 


| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
PACCHETTO DEB per l'installazione delle immagini del nodo StorageGRID sulle appliance.



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
MD5 checksum per il file `/debs/storagegridwebscale-
images-version-SHA.deb`.

|===


== Verificare l'hardware e il collegamento in rete

Prima di iniziare l'espansione del sistema StorageGRID, verificare quanto segue:

* L'hardware necessario per supportare i nuovi nodi di rete o il nuovo sito è stato installato e configurato.
* Tutti i nuovi nodi dispongono di percorsi di comunicazione bidirezionali per tutti i nodi esistenti e nuovi (un requisito per la Grid Network). In particolare, verificare che le seguenti porte TCP siano aperte tra i nuovi nodi che si stanno aggiungendo nell'espansione e il nodo di amministrazione primario:
+
** 1055
** 7443
** 8011
** 10342


+
Vedere link:../network/internal-grid-node-communications.html["Comunicazioni interne al nodo di rete"].

* Il nodo di amministrazione primario può comunicare con tutti i server di espansione destinati a ospitare il sistema StorageGRID.
* Se uno dei nuovi nodi dispone di un indirizzo IP di rete su una subnet non utilizzata in precedenza, è già presente link:updating-subnets-for-grid-network.html["aggiunta della nuova subnet"]l'elenco delle subnet di rete griglia. In caso contrario, sarà necessario annullare l'espansione, aggiungere la nuova subnet e avviare nuovamente la procedura.
* Non stai utilizzando la conversione degli indirizzi di rete (NAT) sulla rete di rete tra nodi di rete o tra siti StorageGRID. Quando si utilizzano indirizzi IPv4 privati per Grid Network, tali indirizzi devono essere direttamente instradabili da ogni nodo di griglia in ogni sito. L'utilizzo di NAT per il bridge della rete Grid attraverso un segmento di rete pubblica è supportato solo se si utilizza un'applicazione di tunneling trasparente per tutti i nodi della griglia, il che significa che i nodi della griglia non richiedono alcuna conoscenza degli indirizzi IP pubblici.
+
Questa restrizione NAT è specifica per i nodi di griglia e la rete di griglia. Se necessario, è possibile utilizzare NAT tra client esterni e nodi di rete, ad esempio per fornire un indirizzo IP pubblico per un nodo gateway.


