---
permalink: expand/updating-subnets-for-grid-network.html 
sidebar: sidebar 
keywords: expand, expansion, add subnets, Grid Network 
summary: 'Quando si aggiungono nodi griglia o un nuovo sito in un"espansione, potrebbe essere necessario aggiornare o aggiungere sottoreti alla rete Grid.' 
---
= Aggiornare le subnet per Grid Network
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si aggiungono nodi griglia o un nuovo sito in un'espansione, potrebbe essere necessario aggiornare o aggiungere sottoreti alla rete Grid.

StorageGRID mantiene un elenco delle subnet di rete utilizzate per comunicare tra i nodi della griglia sulla rete (eth0). Queste voci includono le subnet utilizzate per la rete griglia da ciascun sito nel sistema StorageGRID, nonché le subnet utilizzate per NTP, DNS, LDAP o altri server esterni a cui si accede tramite il gateway della rete griglia.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone di link:../admin/admin-group-permissions.html["Autorizzazione di manutenzione o di accesso root"].
* Si dispone della passphrase di provisioning.
* Si dispone degli indirizzi di rete, in notazione CIDR, delle subnet che si desidera configurare.


.A proposito di questa attività
Se uno dei nuovi nodi ha un indirizzo IP Grid Network su una subnet non utilizzata in precedenza, è necessario aggiungere la nuova subnet all'elenco Grid Network subnet prima di avviare l'espansione. In caso contrario, sarà necessario annullare l'espansione, aggiungere la nuova subnet e avviare nuovamente la procedura.

[NOTE]
====
Non utilizzare subnet che contengono i seguenti indirizzi IPv4 per la rete Grid, la rete di amministrazione o la rete client di alcun nodo:

* 192.168.130.101
* 192.168.131.101
* 192.168.130.102
* 192.168.131.102
* 198.51.100.2
* 198.51.100.4


Ad esempio, non utilizzare i seguenti intervalli di subnet per la rete Grid, la rete amministrativa o la rete client di alcun nodo:

* 192.168.130.0/24 perché questo intervallo di subnet contiene gli indirizzi IP 192.168.130.101 e 192.168.130.102
* 192.168.131.0/24 perché questo intervallo di subnet contiene gli indirizzi IP 192.168.131.101 e 192.168.131.102
* 198.51.100.0/24 perché questo intervallo di subnet contiene gli indirizzi IP 198.51.100.2 e 198.51.100.4


====
.Fasi
. Selezionare *MANUTENZIONE* > *rete* > *rete griglia*.
. Selezionare *Aggiungi un'altra subnet* per aggiungere una nuova subnet nella notazione CIDR.
+
Ad esempio, immettere `10.96.104.0/22`.

. Inserire la passphrase di provisioning e selezionare *Save* (Salva).
. Attendere che le modifiche vengano applicate, quindi scaricare un nuovo pacchetto di ripristino.
+
.. Selezionare *MANUTENZIONE* > *sistema* > *pacchetto di ripristino*.
.. Immettere la *Provisioning Passphrase*.
+

CAUTION: Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID. Viene inoltre utilizzato per ripristinare il nodo di amministrazione primario.





Le subnet specificate vengono configurate automaticamente per il sistema StorageGRID.
