---
permalink: troubleshoot/troubleshooting-lost-and-missing-object-data.html 
sidebar: sidebar 
keywords: how to troubleshoot lost object data, how to troubleshoot missing object data 
summary: 'Gli oggetti possono essere recuperati per diversi motivi, tra cui le richieste di lettura da un"applicazione client, le verifiche in background dei dati degli oggetti replicati, le rivalutazioni ILM e il ripristino dei dati degli oggetti durante il ripristino di un nodo di storage.' 
---
= Risolvere i problemi relativi ai dati degli oggetti persi e mancanti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli oggetti possono essere recuperati per diversi motivi, tra cui le richieste di lettura da un'applicazione client, le verifiche in background dei dati degli oggetti replicati, le rivalutazioni ILM e il ripristino dei dati degli oggetti durante il ripristino di un nodo di storage.

Il sistema StorageGRID utilizza le informazioni sulla posizione contenute nei metadati di un oggetto per determinare da quale posizione recuperare l'oggetto.  Se non viene trovata una copia dell'oggetto nella posizione prevista, il sistema tenta di recuperare un'altra copia dell'oggetto da un'altra posizione nel sistema, presupponendo che la policy ILM contenga una regola per creare due o più copie dell'oggetto.

Se il recupero ha esito positivo, il sistema StorageGRID sostituisce la copia mancante dell'oggetto.  In caso contrario, viene attivato l'avviso *Oggetti potenzialmente persi*, come segue:

* Per le copie replicate, se non è possibile recuperare un'altra copia, l'oggetto viene considerato perso e viene attivato l'avviso.
* Per le copie con erasure coding, se non è possibile recuperare una copia dalla posizione prevista, l'attributo copie danneggiate rilevate (ECOR) viene incrementato di uno prima di tentare di recuperare una copia da un'altra posizione. Se non viene trovata alcuna altra copia, viene attivato l'avviso.


È necessario esaminare immediatamente tutti gli avvisi di *Oggetti potenzialmente persi* per determinare la causa principale della perdita e per stabilire se l'oggetto potrebbe ancora esistere in un nodo di archiviazione offline o altrimenti non disponibile. Vedere link:../troubleshoot/investigating-potentially-lost-objects.html["Indagare su oggetti potenzialmente persi"] .  Gli avvisi di oggetti smarriti potrebbero essere attivati erroneamente per precauzione.

Nel caso in cui i dati degli oggetti senza copie vengano persi, non esiste alcuna soluzione di recupero.  Tuttavia, è necessariolink:../troubleshoot/investigating-potentially-lost-objects.html#reset-lost-obj-count["azzera il contatore degli oggetti potenzialmente persi"] per evitare che oggetti smarriti noti mascherino nuovi oggetti smarriti.
