---
permalink: ilm/creating-cloud-storage-pool.html 
sidebar: sidebar 
keywords: how to create cloud storage pool 
summary: Un Cloud Storage Pool specifica un singolo bucket esterno Amazon S3 o un altro provider compatibile con S3 o un container di storage BLOB di Azure. 
---
= Creare un pool di storage cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un Cloud Storage Pool specifica un singolo bucket esterno Amazon S3 o un altro provider compatibile con S3 o un container di storage BLOB di Azure.

Quando crei un pool di storage cloud, specifica il nome e la posizione del bucket o del container esterno che StorageGRID utilizzerà per memorizzare gli oggetti, il tipo di provider cloud (storage Amazon S3/GCP o Azure Blob) e le informazioni StorageGRID necessarie per accedere al bucket o al container esterno.

StorageGRID convalida il pool di storage cloud non appena viene salvato, quindi devi assicurarti che il bucket o il container specificato nel pool di storage cloud esista e sia raggiungibile.

.Prima di iniziare
* L'utente ha effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone di link:../admin/admin-group-permissions.html["autorizzazioni di accesso richieste"].
* È stata esaminata la link:considerations-for-cloud-storage-pools.html["Considerazioni per i Cloud Storage Pools"].
* Il bucket o contenitore esterno a cui fa riferimento il Cloud Storage Pool esiste già e si dispone di <<service-endpoint-info,informazioni sull'endpoint di servizio>>.
* Per accedere al secchio o al contenitore, è <<authentication-account-info,informazioni sull'account per il tipo di autenticazione>>possibile scegliere.


.Fasi
. Selezionare *ILM* > *Storage Pools* > *Cloud Storage Pools*.
. Selezionare *Crea*, quindi immettere le seguenti informazioni:
+
[cols="1a,3a"]
|===
| Campo | Descrizione 


 a| 
Nome del pool di cloud storage
 a| 
Un nome che descrive brevemente il Cloud Storage Pool e il suo scopo. Utilizzare un nome che sia facile da identificare quando si configurano le regole ILM.



 a| 
Tipo di provider
 a| 
Quale cloud provider utilizzerai per questo Cloud Storage Pool:

** *Amazon S3/GCP*: Selezionare questa opzione per Amazon S3, Commercial Cloud Services (C2S) S3, Google Cloud Platform (GCP) o altri provider compatibili con S3.
** *Azure Blob Storage*




 a| 
Bucket o container
 a| 
Il nome del bucket S3 esterno o del container Azure. Non puoi modificare questo valore dopo il salvataggio del Cloud Storage Pool.

|===
. [[service-endpoint-info]]in base alla selezione del tipo di provider, immettere le informazioni sull'endpoint del servizio.
+
[role="tabbed-block"]
====
.Amazon S3/GCP
--
.. Per il protocollo, selezionare HTTPS o HTTP.
+

NOTE: Non utilizzare connessioni HTTP per dati sensibili.

.. Inserire il nome host. Esempio:
+
`s3-_aws-region_.amazonaws.com`

.. Selezionare lo stile URL:
+
[cols="1a,3a"]
|===
| Opzione | Descrizione 


 a| 
Rilevamento automatico
 a| 
Tentare di rilevare automaticamente lo stile URL da utilizzare, in base alle informazioni fornite. Ad esempio, se si specifica un indirizzo IP, StorageGRID utilizzerà un URL di tipo path. Selezionare questa opzione solo se non si conosce lo stile specifico da utilizzare.



 a| 
Stile virtual-hosted
 a| 
Utilizza un URL di tipo virtual-hosted per accedere al bucket. Gli URL in stile virtual-hosted includono il nome del bucket come parte del nome di dominio. Esempio: `+https://bucket-name.s3.company.com/key-name+`



 a| 
Stile di percorso
 a| 
Utilizzare un URL stile percorso per accedere al bucket. Gli URL stile percorso includono il nome del bucket alla fine Esempio: `+https://s3.company.com/bucket-name/key-name+`

*Nota:* l'opzione URL stile percorso non è consigliata e sarà obsoleta in una release futura di StorageGRID.

|===
.. Se si desidera, inserire il numero della porta o utilizzare la porta predefinita: 443 per HTTPS o 80 per HTTP.


--
.Azure Blob Storage
--
.. Utilizzando uno dei seguenti formati, immettere l'URI per l'endpoint del servizio.
+
*** `+https://host:port+`
*** `+http://host:port+`




Esempio: `https://_myaccount_.blob.core.windows.net:443`

Se non si specifica una porta, per impostazione predefinita viene utilizzata la porta 443 per HTTPS e la porta 80 per HTTP.

--
====


. [[Authentication-account-info]]selezionare *Continue*. Quindi, selezionare il tipo di autenticazione e immettere le informazioni richieste per l'endpoint del Cloud Storage Pool:
+
[role="tabbed-block"]
====
.Tasto di accesso
--
_Per Amazon S3/GCP o altro provider compatibile con S3_

.. *ID chiave di accesso*: Immettere l'ID della chiave di accesso per l'account proprietario del bucket esterno.
.. *Chiave di accesso segreta*: Immettere la chiave di accesso segreta.


--
.Ruoli IAM ovunque
--
_Per AWS IAM Roles Anywhere service_

StorageGRID utilizza AWS Security Token Service (STS) per generare dinamicamente un token di breve durata per accedere alle risorse AWS.

.. *AWS IAM Roles Anywhere Region*: Selezionare la regione per il Cloud Storage Pool. Ad esempio, `us-east-1`.
.. *Trust anchor URN*: Immettere l'URN dell'ancoraggio trust che convalida le richieste per le credenziali STS di breve durata. Può essere una CA principale o intermedia.
.. *URN profilo*: Immettere l'URN del profilo IAM Roles Anywhere che elenca i ruoli che possono essere assunti da chiunque sia attendibile.
.. *Role URN*: Inserire l'URN del ruolo IAM che può essere assunto da chiunque sia attendibile.
.. *Durata sessione*: Immettere la durata delle credenziali di protezione temporanee e della sessione ruolo. Immettere almeno 15 minuti e non più di 12 ore.
.. *Certificato CA del server* (opzionale): Uno o più certificati CA attendibili, in formato PEM, per la verifica del server IAM Roles Anywhere. Se omesso, il server non verrà verificato.
.. *Certificato dell'entità finale*: La chiave pubblica, in formato PEM, del certificato X509 firmato dall'ancoraggio trust. AWS IAM Roles Anywhere utilizza questa chiave per emettere un token STS.
.. *Chiave privata dell'entità finale*: La chiave privata per il certificato dell'entità finale.


--
.CAP (portale di accesso C2S)
--
_Per il servizio Commercial Cloud Services (C2S) S3_

.. *URL credenziali temporanee*: Immettere l'URL completo che StorageGRID utilizzerà per ottenere le credenziali temporanee dal server CAP, inclusi tutti i parametri API obbligatori e facoltativi assegnati all'account C2S.
.. *Certificato CA del server*: Selezionare *Sfoglia* e caricare il certificato CA utilizzato da StorageGRID per verificare il CAP server. Il certificato deve essere codificato PEM ed emesso da un'autorità di certificazione pubblica competente (CA).
.. *Certificato client*: Selezionare *Sfoglia* e caricare il certificato che StorageGRID utilizzerà per identificarsi nel CAP server. Il certificato client deve essere codificato PEM, rilasciato da un'autorità di certificazione pubblica (CA) appropriata e deve essere concesso l'accesso al conto C2S.
.. *Chiave privata client*: Selezionare *Sfoglia* e caricare la chiave privata codificata PEM per il certificato client.
.. Se la chiave privata del client è crittografata, immettere la passphrase per la decrittografia della chiave privata del client. In caso contrario, lasciare vuoto il campo *Password chiave privata client*.



NOTE: Se il certificato client viene crittografato, utilizzare il formato tradizionale per la crittografia. Il formato crittografato PKCS n. 8 non è supportato.

--
.Azure Blob Storage
--
_Per l'archiviazione BLOB di Azure, solo chiave condivisa_

.. *Nome account*: Immettere il nome dell'account di archiviazione proprietario del contenitore esterno
.. *Codice account*: Immettere la chiave segreta per l'account di archiviazione


È possibile utilizzare il portale Azure per trovare questi valori.

--
.Anonimo
--
Non sono richieste informazioni aggiuntive.

--
====
. Selezionare *continua*. Quindi scegliere il tipo di verifica del server che si desidera utilizzare:
+
[cols="1a,2a"]
|===
| Opzione | Descrizione 


 a| 
Utilizzare i certificati della CA principale nel sistema operativo del nodo di storage
 a| 
Utilizzare i certificati Grid CA installati nel sistema operativo per proteggere le connessioni.



 a| 
USA certificato CA personalizzato
 a| 
Utilizzare un certificato CA personalizzato. Selezionare *Sfoglia* e caricare il certificato codificato PEM.



 a| 
Non verificare il certificato
 a| 
La selezione di questa opzione indica che le connessioni TLS al Cloud Storage Pool non sono sicure.

|===
. Selezionare *Salva*.
+
Quando si salva un pool di storage cloud, StorageGRID esegue le seguenti operazioni:

+
** Convalida l'esistenza del bucket o del container e dell'endpoint del servizio e la possibilità di raggiungerli utilizzando le credenziali specificate.
** Scrive un file marker nel bucket o nel container per identificarlo come pool di storage cloud. Non rimuovere mai questo file, che è denominato `x-ntap-sgws-cloud-pool-uuid`.
+
Se la convalida del Cloud Storage Pool non riesce, viene visualizzato un messaggio di errore che spiega perché la convalida non è riuscita. Ad esempio, se si verifica un errore nel certificato o se il bucket o il container specificato non esiste già, potrebbe essere visualizzato un errore.



. Se si verifica un errore, consultare la sezione link:troubleshooting-cloud-storage-pools.html["Istruzioni per la risoluzione dei problemi dei Cloud Storage Pools"], risolvere eventuali problemi, quindi provare a salvare nuovamente il Cloud Storage Pool.

