---
permalink: ilm/requirements-for-s3-object-lock.html 
sidebar: sidebar 
keywords: requirements, s3 object lock, compliant ilm rule, compliant ilm policy 
summary: 'È necessario esaminare i requisiti per l"attivazione dell"impostazione globale di blocco oggetti S3, i requisiti per la creazione di regole ILM e criteri ILM conformi e le restrizioni applicate da StorageGRID ai bucket e agli oggetti che utilizzano il blocco oggetti S3.' 
---
= Requisiti per il blocco oggetti S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario esaminare i requisiti per l'attivazione dell'impostazione globale di blocco oggetti S3, i requisiti per la creazione di regole ILM e criteri ILM conformi e le restrizioni applicate da StorageGRID ai bucket e agli oggetti che utilizzano il blocco oggetti S3.



== Requisiti per l'utilizzo dell'impostazione globale S3 Object Lock

* È necessario attivare l'impostazione globale S3 Object Lock utilizzando Grid Manager o l'API Grid Management prima che qualsiasi tenant S3 possa creare un bucket con S3 Object Lock attivato.
* L'attivazione dell'impostazione globale S3 Object Lock consente a tutti gli account tenant S3 di creare bucket con S3 Object Lock attivato.
* Dopo aver attivato l'impostazione di blocco oggetti S3 globale, non è possibile disattivare l'impostazione.
* Non è possibile attivare il blocco oggetto S3 globale a meno che la regola predefinita in tutti i criteri ILM attivi non sia _conforme_ (vale a dire, la regola predefinita deve essere conforme ai requisiti dei bucket con blocco oggetto S3 abilitato).
* Quando l'impostazione blocco oggetti S3 globale è attivata, non è possibile creare un nuovo criterio ILM o attivare un criterio ILM esistente a meno che la regola predefinita nel criterio non sia conforme. Una volta attivata l'impostazione globale S3 Object Lock, le pagine delle regole ILM e dei criteri ILM indicano quali regole ILM sono conformi.




== Requisiti per le regole ILM conformi

Se si desidera attivare l'impostazione blocco oggetto S3 globale, è necessario verificare che la regola predefinita in tutti i criteri ILM attivi sia conforme. Una regola conforme soddisfa i requisiti di entrambi i bucket con blocco oggetti S3 attivato e di tutti i bucket esistenti con conformità legacy attivata:

* Deve creare almeno due copie di oggetti replicate o una copia con codice di cancellazione.
* Queste copie devono esistere nei nodi di storage per l'intera durata di ciascuna riga nelle istruzioni di posizionamento.
* Impossibile salvare le copie degli oggetti in un Cloud Storage Pool.
* Almeno una riga delle istruzioni di posizionamento deve iniziare al giorno 0, utilizzando *Ingest Time* come ora di riferimento.
* Almeno una riga delle istruzioni di posizionamento deve essere "per sempre".




== Requisiti per le policy ILM

Quando l'impostazione blocco oggetto S3 globale è attivata, i criteri ILM attivi e inattivi possono includere regole conformi e non conformi.

* La regola predefinita in un criterio ILM attivo o inattivo deve essere conforme.
* Le regole non conformi si applicano solo agli oggetti nei bucket che non hanno attivato il blocco oggetti S3 o che non hanno la funzionalità Compliance legacy attivata.
* Le regole conformi possono essere applicate agli oggetti in qualsiasi bucket; non è necessario attivare il blocco oggetti S3 o la conformità legacy per il bucket.


link:example-7-compliant-ilm-policy-for-s3-object-lock.html["Esempio di un criterio ILM conforme per il blocco degli oggetti S3"]



== Requisiti per i bucket con S3 Object Lock attivato

* Se l'impostazione blocco oggetto S3 globale è attivata per il sistema StorageGRID, è possibile utilizzare Gestione tenant, API di gestione tenant o API REST S3 per creare bucket con blocco oggetto S3 attivato.
* Se si intende utilizzare il blocco oggetti S3, è necessario attivare il blocco oggetti S3 quando si crea il bucket. Impossibile attivare il blocco oggetti S3 per un bucket esistente.
* Quando il blocco oggetti S3 è attivato per un bucket, StorageGRID attiva automaticamente il controllo delle versioni per quel bucket. Non puoi disattivare il blocco oggetti S3 o sospendere il controllo delle versioni per il bucket.
* Facoltativamente, è possibile specificare una modalità di conservazione e un periodo di conservazione predefiniti per ciascun bucket utilizzando Tenant Manager, l'API di gestione tenant o l'API REST S3. Le impostazioni di conservazione predefinite del bucket si applicano solo ai nuovi oggetti aggiunti al bucket che non dispongono di proprie impostazioni di conservazione. È possibile eseguire l'override di queste impostazioni predefinite specificando una modalità di conservazione e conservarla fino alla data per ogni versione dell'oggetto al momento del caricamento.
* La configurazione del ciclo di vita del bucket è supportata per i bucket con blocco oggetti S3 attivato.
* La replica di CloudMirror non è supportata per i bucket con blocco oggetti S3 attivato.




== Requisiti per gli oggetti nei bucket con S3 Object Lock attivato

* Per proteggere una versione dell'oggetto, è possibile specificare le impostazioni di conservazione predefinite per il bucket oppure le impostazioni di conservazione per ciascuna versione dell'oggetto. È possibile specificare le impostazioni di conservazione a livello di oggetto utilizzando l'applicazione client S3 o l'API REST S3.
* Le impostazioni di conservazione si applicano alle singole versioni di oggetti. Una versione a oggetti può avere un'impostazione di conservazione fino alla data e un'impostazione di conservazione legale, una ma non l'altra o nessuna delle due. La specifica di un'impostazione di conservazione fino a data o di conservazione legale per un oggetto protegge solo la versione specificata nella richiesta. È possibile creare nuove versioni dell'oggetto, mentre la versione precedente rimane bloccata.




== Ciclo di vita degli oggetti nei bucket con S3 Object Lock attivato

Ogni oggetto salvato in un bucket con S3 Object Lock attivato passa attraverso le seguenti fasi:

. *Acquisizione oggetto*
+
Quando una versione dell'oggetto viene aggiunta al bucket con S3 Object Lock attivato, le impostazioni di conservazione vengono applicate come segue:

+
** Se per l'oggetto sono specificate le impostazioni di conservazione, vengono applicate le impostazioni a livello di oggetto. Tutte le impostazioni predefinite del bucket vengono ignorate.
** Se non sono specificate impostazioni di conservazione per l'oggetto, vengono applicate le impostazioni predefinite del bucket, se presenti.
** Se non sono specificate impostazioni di conservazione per l'oggetto o il bucket, l'oggetto non è protetto da S3 Object Lock.


+
Se vengono applicate le impostazioni di conservazione, vengono protetti sia l'oggetto che i metadati S3 definiti dall'utente.

. *Conservazione ed eliminazione degli oggetti*
+
StorageGRID memorizza più copie di ciascun oggetto protetto per il periodo di conservazione specificato. Il numero e il tipo esatti delle copie degli oggetti e le posizioni dello storage sono determinati dalle regole di conformità nelle policy ILM attive. La possibilità di eliminare un oggetto protetto prima che venga raggiunta la data di conservazione dipende dalla modalità di conservazione.

+
** Se un oggetto è sottoposto a un blocco legale, nessuno può eliminare l'oggetto, indipendentemente dalla modalità di conservazione.




.Informazioni correlate
* link:../tenant/creating-s3-bucket.html["Creare un bucket S3"]
* link:../tenant/update-default-retention-settings.html["Aggiorna la conservazione predefinita del blocco oggetti S3"]
* link:../s3/use-s3-api-for-s3-object-lock.html["Utilizzare l'API REST S3 per configurare il blocco oggetti S3"]
* link:example-7-compliant-ilm-policy-for-s3-object-lock.html["Esempio 7: Policy ILM conforme per il blocco oggetti S3"]

