---
permalink: ilm/what-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a storage pool 
summary: Un pool di storage è un raggruppamento logico di nodi storage. 
---
= Che cos'è un pool di storage?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un pool di storage è un raggruppamento logico di nodi storage.

Quando si installa StorageGRID, viene creato automaticamente un pool di storage per sito. È possibile configurare ulteriori pool di storage in base alle esigenze di storage.


NOTE: Durante l'installazione, è possibile configurare i nodi di archiviazione in modo che contengano dati e metadati di oggetti (nodo di archiviazione "combinato"), solo metadati di oggetti o solo dati di oggetti.  I nodi di archiviazione solo metadati non possono essere utilizzati nei pool di archiviazione. Per ulteriori informazioni, fare riferimento a link:../primer/what-storage-node-is.html#types-of-storage-nodes["Tipi di nodi storage"] .

I pool di storage hanno due attributi:

* *Storage grade*: Per i nodi di storage, le performance relative dello storage di backup.
* *Sito*: Il data center in cui verranno memorizzati gli oggetti.


I pool di storage vengono utilizzati nelle regole ILM per determinare dove sono memorizzati i dati degli oggetti e il tipo di storage utilizzato. Quando si configurano le regole ILM per la replica, si selezionano uno o più pool di storage.
