---
permalink: ilm/what-cloud-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a cloud storage pool 
summary: Un pool di cloud storage ti permette di usare ILM per spostare i dati degli oggetti al di fuori del tuo sistema StorageGRID. Ad esempio, potresti voler spostare oggetti a cui accedi raramente verso cloud storage a costo inferiore, come Amazon S3 Glacier, S3 Glacier Deep Archive, Google Cloud o il livello di accesso Archive in Microsoft Azure Blob Storage. Oppure, potresti voler mantenere un backup cloud degli oggetti StorageGRID per migliorare il disaster recovery. 
---
= Scopri i Cloud Storage Pool in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un pool di cloud storage ti permette di usare ILM per spostare i dati degli oggetti al di fuori del tuo sistema StorageGRID. Ad esempio, potresti voler spostare oggetti a cui accedi raramente verso cloud storage a costo inferiore, come Amazon S3 Glacier, S3 Glacier Deep Archive, Google Cloud o il livello di accesso Archive in Microsoft Azure Blob Storage. Oppure, potresti voler mantenere un backup cloud degli oggetti StorageGRID per migliorare il disaster recovery.

Dal punto di vista dell'ILM, un cloud storage pool è simile a un pool di storage. Per archiviare oggetti in entrambe le posizioni, selezioni il pool durante la creazione delle istruzioni di posizionamento per una regola ILM. Tuttavia, mentre i pool di storage sono costituiti da Storage Nodes all'interno del sistema StorageGRID, un cloud storage pool è costituito da un bucket esterno (S3) o container (Azure Blob Storage).

La tabella confronta i pool di storage con i pool di storage cloud e mostra le analogie e le differenze di alto livello.

[cols="1a,2a,5a"]
|===
|  | Pool di storage | Pool di cloud storage 


 a| 
Come viene creato?
 a| 
Utilizzando l'opzione *ILM* > *Storage Pools* in Grid Manager.
 a| 
Utilizzando l'opzione *ILM* > *Storage Pools* > *Cloud Storage Pools* in Grid Manager.

È necessario configurare il bucket o il container esterno prima di poter creare il Cloud Storage Pool.



 a| 
Quanti pool è possibile creare?
 a| 
Senza limiti.
 a| 
Fino a 10.



 a| 
Dove sono memorizzati gli oggetti?
 a| 
Su uno o più nodi storage all'interno di StorageGRID.
 a| 
In un bucket Amazon S3, in un container Azure Blob Storage o in Google Cloud esterno al sistema StorageGRID.

Se il Cloud Storage Pool è un bucket Amazon S3:

* È possibile configurare un ciclo di vita del bucket per la transizione di oggetti a storage a lungo termine e a basso costo, come Amazon S3 Glacier o S3 Glacier Deep Archive. Il sistema di storage esterno deve supportare la classe di storage Glacier e l'API S3 RestoreObject.
* È possibile creare pool di storage cloud da utilizzare con AWS Commercial Cloud Services (C2S), che supporta l'AWS Secret Region.


Se il pool di cloud storage è un container Azure Blob Storage, StorageGRID sposta l'oggetto al livello Archive.

*Nota:* In generale, non configurare la gestione del ciclo di vita di Azure Blob Storage per il container utilizzato per un Cloud Storage Pool. RestoreObject operazioni sugli oggetti nel Cloud Storage Pool possono essere influenzate dal ciclo di vita configurato.



 a| 
Cosa controlla il posizionamento degli oggetti?
 a| 
Una regola ILM nei criteri ILM attivi.
 a| 
Una regola ILM nei criteri ILM attivi.



 a| 
Quale metodo di protezione dei dati viene utilizzato?
 a| 
Replica o erasure coding.
 a| 
Replica.



 a| 
Quante copie di ciascun oggetto sono consentite?
 a| 
Multiplo.
 a| 
Una copia nel pool di storage cloud e, facoltativamente, una o più copie in StorageGRID.

*Nota:* non è possibile memorizzare un oggetto in più di un Cloud Storage Pool alla volta.



 a| 
Quali sono i vantaggi?
 a| 
Gli oggetti sono rapidamente accessibili in qualsiasi momento.
 a| 
Storage a basso costo.

*Nota*: Non è possibile eseguire il tiering dei dati FabricPool nei pool di storage cloud.

|===