---
permalink: release-notes/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: 'StorageGRID 12.1 utilizza la versione 4 dell"API di gestione della griglia. La versione 4 depreca la versione 3. Tuttavia, le versioni 1, 2 e 3 sono ancora supportate.' 
---
= Modifiche all'API di gestione della griglia in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1 utilizza la versione 4 della Grid Management API. La versione 4 rende obsoleta la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.


NOTE: Puoi continuare a usare le versioni obsolete dell'API di gestione con StorageGRID; tuttavia, il supporto per queste versioni dell'API verrà rimosso in una versione futura di StorageGRID. Dopo l'aggiornamento a StorageGRID 12.0 o versioni successive, puoi disattivare le API obsolete usando l' `PUT /grid/config/management`API.

Per ulteriori informazioni, visitare il sito Web all'indirizzo link:../admin/using-grid-management-api.html["Utilizzare l'API Grid Management"].



[[new-endpoints-for-changing-the-bmc-password-and-lan-ip-settings]]
== Nuovi endpoint per modificare la password BMC e le impostazioni IP della LAN

Il seguente endpoint è stato aggiunto per consentirti di link:../harden/hardening-guidelines-for-storagegrid-nodes.html#change-appliance-bmc-password["cambia la password BMC di un appliance"].

`PUT /bmc-configuration/root-password`

Sono stati aggiunti i seguenti endpoint per consentirti di link:../maintain/changing-nodes-network-configuration.html#change-appliance-node-bmc-lan-ip-settings["modificare o visualizzare le impostazioni IP LAN del BMC"].

`PUT /grid/bmc/{node-id}/lan-ip-config`

`GET /grid/bmc/{node-id}/lan-ip-config`
