---
permalink: release-notes/removed-or-deprecated-features.html 
sidebar: sidebar 
keywords:  
summary: 'Scopri le funzionalità e le capacità rimosse o deprecate in StorageGRID 12.1.0. Prima di eseguire l"aggiornamento, verifica se le funzionalità rimosse o deprecate influiscono sulle applicazioni client o sulla configurazione della grid.' 
---
= Funzionalità e funzionalità rimosse o deprecate in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le funzionalità e le capacità rimosse o deprecate in StorageGRID 12.1.0. Prima di eseguire l'aggiornamento, verifica se le funzionalità rimosse o deprecate influiscono sulle applicazioni client o sulla configurazione della grid.



[[definitions]]
== Definizioni

Obsoleto:: Non dovresti utilizzare questa funzionalità nei nuovi ambienti di produzione. Gli ambienti di produzione esistenti possono continuare a utilizzare questa funzionalità.
Fine del ciclo di vita:: Ultima versione fornita che supporta la funzione. In alcuni casi, la documentazione relativa alla funzione potrebbe essere rimossa in questa fase.
Rimosso:: Prima versione che *non* supporta la funzione.




[[storagegrid-end-of-feature-support]]
== Fine del supporto delle funzionalità di StorageGRID

Le funzioni obsolete verranno rimosse nelle versioni principali N+2. Ad esempio, se una funzione è deprecata nella versione N (ad esempio, 6,3), l'ultima versione in cui la funzione esisterà è N+1 (ad esempio, 6,4). La versione N+2 (ad esempio, 6,5) è la prima versione quando la funzione non esiste nel prodotto.

Per ulteriori informazioni, vedere la https://mysupport.netapp.com/site/info/version-support["Pagina supporto versione software"^] .


NOTE: In alcune situazioni, NetApp potrebbe interrompere il supporto per determinate funzioni prima di quanto indicato.

[cols="2a,1a,1a,1a,3a"]
|===
| Funzione | Obsoleto | Fine del ciclo di vita | Rimosso | Collegamenti alla documentazione precedente 


 a| 
Impostazione globale SSE per la crittografia AES-128
 a| 
12,1
 a| 
12,2
 a| 
12,3
 a| 
A partire da StorageGRID 12.1.0, il supporto per la crittografia AES-128 dei nuovi dati degli oggetti archiviati a riposo è deprecato. Il supporto continua per il recupero degli oggetti archiviati che erano stati originariamente crittografati con AES-128.



 a| 
Allarmi, legacy (non Alerts)
 a| 
11,7
 a| 
11,8
 a| 
11,9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/monitor/alarms-reference.html["Riferimento allarmi (StorageGRID 11,8)"^]



 a| 
Supporto nodo di archivio
 a| 
11,7
 a| 
11,8
 a| 
11,9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/considerations-for-decommissioning-admin-or-gateway-nodes.html["Considerazioni per il decommissionamento dei nodi di archivio (StorageGRID 11,8)"^]

*Nota*: Prima di iniziare l'aggiornamento, è necessario:

. Disattiva tutti i nodi di archivio. Consulta  https://docs.netapp.com/us-en/storagegrid-118/maintain/grid-node-decommissioning.html["Decommissionamento nodo griglia (sito doc StorageGRID 11,8)"^].
. Rimuovi tutti i riferimenti ai nodi di archivio dai pool di archiviazione e dalle policy ILM. Consulta  https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["Knowledge base NetApp: Guida alla risoluzione dell'aggiornamento del software StorageGRID 11,9"^].




 a| 
Esportazione di audit tramite CIFS/Samba
 a| 
11,1
 a| 
11,6
 a| 
11,7
 a| 



 a| 
Servizio CLB
 a| 
11,4
 a| 
11,6
 a| 
11,7
 a| 



 a| 
Motore container Docker
 a| 
11,8
 a| 
11,9
 a| 
DA DEFINIRE
 a| 
Il supporto per Docker come motore di container per distribuzioni esclusivamente software è deprecato.  Docker verrà sostituito con un altro motore di container in una versione futura.  Fare riferimento allink:../swnodes/software-requirements.html["requisiti software per i nodi basati su software"] per un elenco delle versioni di Docker attualmente supportate.



 a| 
Configurazione email (legacy)
 a| 
11,9
 a| 
12,0
 a| 
12,1
 a| 
https://docs.netapp.com/us-en/storagegrid-118/monitor/managing-alarms.html#configure-notifications-for-alarms-legacy-system["Configura le notifiche per gli allarmi (sistema legacy) (StorageGRID 11.8)"^]



 a| 
Esportazione con audit NFS
 a| 
11,8
 a| 
11,9
 a| 
12,0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-audit-client-access.html["Configurare l'accesso al client di controllo per NFS (StorageGRID 11,8)"^]



 a| 
Rimappatura delle porte
 a| 
12,0
 a| 
12,1
 a| 
12,2
 a| 



 a| 
Supporto API Swift
 a| 
11,7
 a| 
11,9
 a| 
12,0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/swift/index.html["Utilizzare l'API REST Swift (StorageGRID 11,8)"^]



 a| 
RHEL 8,8
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
RHEL 9,0
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
RHEL 9,2
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
Ubuntu 18.04
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
Ubuntu 20.04
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
Debian 11
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 

|===
Fare riferimento anche a:

* link:changes-to-grid-management-api.html["Modifiche all'API Grid Management"]
* link:changes-to-tenant-management-api.html["Modifiche all'API di gestione del tenant"]

