---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.1 
summary: Questa versione di StorageGRID introduce le seguenti funzionalità e modifiche. 
---
= Novità di StorageGRID 12.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1 introduce le seguenti funzionalità e modifiche.

Per informazioni dettagliate sui problemi risolti e sui problemi noti nelle versioni recenti di StorageGRID 12.1, consultare le  https://library.netapp.com/ecm/ecm_download_file/ECMLP3373065["StorageGRID 12.1 Note di rilascio"^]. È necessario accedere con il proprio account NetApp o crearne uno per accedere alle note di rilascio.



[[capacity]]
== Capacità



[[ec-rebalance-now-uses-free-space]]
=== Il riequilibrio EC ora utilizza lo spazio libero

Il ribilanciamento EC ora utilizza lo spazio libero invece dello spazio utilizzato. Consulta link:../expand/considerations-for-rebalancing-erasure-coded-data.html#what-is-ec-rebalancing["Scopri di più sul ribilanciamento EC dopo l'espansione in StorageGRID"].



[[metadata-allowed-space]]
=== Spazio consentito per i metadati

Ora puoi aumentare il valore massimo consentito per i metadati da 3,96 TB a 7,92 TB. Consulta link:../admin/managing-object-metadata-storage.html#allowed-metadata-space["Spazio consentito di metadati"].



[[control-access]]
== Controllo accessi



[[sso-using-oidc]]
=== SSO tramite OIDC

Ora puoi link:../admin/learn-about-setting-up-sso-oidc.html["Configura il single sign-on (SSO) in StorageGRID usando OpenID Connect (OIDC)"].



[[federation]]
== Federazione



[[global-namespace]]
=== Spazio dei nomi globale

Ora puoi configurare uno spazio dei nomi globale per consentire ai tenant di accedere ai bucket su più sistemi StorageGRID. Consulta link:../admin/learn-about-global-namespace.html["Scopri lo spazio dei nomi globale"].



[[manageability]]
== Gestibilità



[[auto-move-adc-service]]
=== Servizio di spostamento automatico ADC

link:../maintain/understanding-adc-service-quorum.html["Quando richiesto per raggiungere il quorum dell'ADC"], il servizio ADC verrà ora spostato automaticamente quando sei link:../maintain/convert-to-data-only-node.html["conversione di un nodo di archiviazione in un nodo solo dati"] o link:../maintain/considerations-for-decommissioning-storage-nodes.html["disattivare un nodo di archiviazione"].



[[primary-admin-node-recovery]]
=== Ripristino del nodo amministratore primario

Ora puoi ripristinare qualsiasi nodo da un nodo Admin non primario. Consulta link:../maintain/recovering-from-primary-admin-node-failures.html["Ripristino da guasti del nodo Admin primario"].



[[s3]]
== S3



[[enable-s3-object-lock-on-existing-buckets]]
=== Abilita il blocco degli oggetti S3 sui bucket esistenti

Quando l'impostazione "Consenti blocco oggetti S3 per bucket esistenti" è abilitata, un account tenant S3 può abilitare il blocco oggetti S3 per un bucket esistente. Dopo che un account tenant S3 ha abilitato il blocco oggetti S3 per un bucket esistente, non può essere disabilitato.



[[replication-allowed-for-s3-object-lock-enabled-buckets]]
=== Replica consentita per i bucket S3 con Object Lock abilitato

Ora puoi usare CloudMirror per replicare oggetti nei bucket S3 con Object Lock abilitato. Consulta link:../tenant/considerations-for-platform-services.html["Scopri i servizi della piattaforma"].



[[enable-cross-grid-replication-for-non-empty-buckets]]
=== Abilita la replica cross-grid per i bucket non vuoti

Ora puoi abilitare la replica tra griglie per i bucket che non sono vuoti. Consulta link:../admin/grid-federation-what-is-cross-grid-replication.html#requirements-for-cross-grid-replication["Requisiti per la replica cross-grid"].



[[s3-batch-operations-fpvr-only]]
=== Operazioni batch S3 (solo FPVR)

Puoi usare le operazioni batch di S3 per replicare oggetti esistenti in un bucket con controllo delle versioni abilitato che vuoi configurare per la replica tra griglie.

Questa funzionalità richiede l'approvazione FPVR per StorageGRID 12.1. Per utilizzare questa funzionalità, contatta il tuo referente commerciale.



[[non-functional-s3-rest-api-headers]]
=== Intestazioni non funzionali delle API REST S3

Le  `If-Match` e  `If-None-Match` intestazioni sono accettate ma non funzionali per l'API REST S3 link:../s3/put-object.html["PutObject"], link:../s3/complete-multipart-upload.html["CompleteMultipartUpload"], link:../s3/put-object-copy.html["Oggetto CopyObject"] e link:../s3/operations-on-objects.html["DeleteObject (Elimina oggetto)"].

Per ulteriori informazioni, fai riferimento a link:../release-notes/changes-to-s3-rest-api.html["Modifiche al supporto dell'API REST S3 di StorageGRID"].



[[support-for-pre-calculated-checksum-values]]
=== Supporto per valori di checksum precalcolati

L'interfaccia S3 REST SPI ora supporta i valori di checksum precalcolati e l' `x-amz-checksum-type`intestazione della richiesta. Consulta link:../s3/index.html#updates-to-rest-api-support["Aggiornamenti al supporto delle API REST"].



[[security]]
== Sicurezza



[[multi-admin-verification]]
=== Verifica multi-amministratore

La verifica multi-amministratore (MAV) aiuta a prevenire modifiche accidentali o non autorizzate al sistema StorageGRID. Fai riferimento a link:../admin/about-multi-admin-verify.html["Scopri la verifica multi-amministratore di StorageGRID"].



[[security-policy-updates-for-fips]]
=== Aggiornamenti delle policy di sicurezza per FIPS

I rigorosi criteri della politica FIPS sono stati aggiornati. Consulta link:../admin/manage-tls-ssh-policy.html#select-a-security-policy["Seleziona una policy di sicurezza in Gestisci la policy TLS e SSH"].



[[tenants]]
== Tenant



[[account-sync]]
=== Sincronizzazione account

La funzionalità _clonazione account_ ora si riferisce a una clonazione una tantum delle informazioni di un account tenant specifico.

_Account sync_ è una nuova funzionalità che ti permette di replicare automaticamente e continuamente tenant account, tenant group, tenant user e chiavi di accesso S3 tra i sistemi StorageGRID in una o più connessioni di federazione grid. Consulta link:../admin/grid-federation-what-is-account-sync.html["Scopri la sincronizzazione degli account in StorageGRID"].



[[kafka-endpoints-and-mtls-authentication]]
=== Endpoint Kafka e autenticazione mTLS

Il protocollo mTLS (Mutual Transport Layer Security) è ora supportato per gli endpoint Kafka. Fai riferimento a link:../tenant/configuring-platform-services-endpoints.html["Configurare gli endpoint dei servizi della piattaforma"].



[[maximum-number-of-buckets]]
=== Numero massimo di bucket

Un sistema StorageGRID ora supporta un massimo di 20.000 bucket per ogni account tenant S3.



[[upgrade]]
== Aggiornamento



[[time-to-enable-features-is-increased]]
=== Il tempo per abilitare le funzionalità è aumentato

Durante l'aggiornamento di StorageGRID alla versione 12.1, il tempo necessario per abilitare le funzionalità è aumentato da meno di cinque minuti a un'ora. Consulta link:../upgrade/estimating-time-to-complete-upgrade.html#estimate-time-to-upgrade["Stima il tempo necessario per completare un aggiornamento di StorageGRID"].



[[user-interface]]
== Interfaccia utente



[[bmc-settings-page]]
=== Pagina delle impostazioni BMC

È stata aggiunta una nuova scheda BMC Settings alla pagina Nodes in Grid Manager per consentire il reset della password BMC e le modifiche alle impostazioni IP LAN del BMC. Consulta link:../harden/hardening-guidelines-for-storagegrid-nodes.html["Cambia la password BMC dell'appliance"] e link:../maintain/changing-nodes-network-configuration.html#change-appliance-node-bmc-lan-ip-settings["Modifica le impostazioni IP LAN del nodo BMC dell'appliance"]. Sono stati aggiunti anche nuovi endpoint API per supportare queste funzioni. Consulta link:../release-notes/changes-to-grid-management-api.html["Nuovi endpoint per modificare la password BMC e le impostazioni IP della LAN"].



[[email-notifications]]
=== Notifiche email

Il Grid Manager ora dispone di una pagina e-mail comune per configurare e gestire le notifiche e-mail per gli avvisi, AutoSupport e la verifica multi-amministratore (MAV). Consulta link:../monitor/configure-email-server.html["Configura il server di posta elettronica"].



[[link-cost-page-update]]
=== Aggiornamento della pagina dei costi del collegamento

StorageGRID 12.1 fornisce informazioni e impostazioni più dettagliate sui costi dei collegamenti. Consulta link:../admin/manage-link-costs.html["Gestire i costi di collegamento"].



[[usb-port-control]]
=== controllo della porta USB

Ora puoi abilitare o disabilitare le porte USB tramite Grid Manager. Consulta link:../harden/hardening-guidelines-for-storagegrid-nodes.html#control-remote-access-through-usb-ports["Controlla l'accesso remoto tramite porte USB"].
